README.md

fixed a typo in the readme

---

src/app/feature/chat/chat.page.html
src/app/feature/chat/chat.page.ts

This let's us use a flag to automatically reply to messages every n milliseconds and display a count of messages sent and received. Will be used for very rough cost estimates.

Message count testing UI

---

src/app/shared/services/chat/chat.triggers.ts
src/app/shared/services/chat/offline/chat.flow.ts
src/app/shared/services/chat/offline/offline-chat.service.ts
src/assets/rapid-pro-flow-exports/idems-plh-app_3.json

Random and @ variable switch routers supported

Offline chat dev

---

src/app/app.component.ts
src/app/feature/home/home.page.ts
src/app/feature/settings/settings.page.html
src/app/feature/settings/settings.page.ts
src/app/shared/services/local-storage/local-storage.service.ts
src/assets/rapid-pro-flow-exports/idems-plh-app_3.json

Don't show welcome conversation flow or survey on app open any more. Instead show them via settings page

Home screen bug fixes

---

src/app/feature/theme/theme-service/theme.service.ts

When OS changes from Light to Dark mode switch theme colors instantly.

Switch colors on dark mode switch

---

src/app/app.component.ts
src/app/feature/home/home-buttons/home-buttons.component.html
src/app/feature/home/home-buttons/home-buttons.component.scss
src/app/feature/theme/built-in-themes.ts
src/app/feature/theme/theme-editor/theme-editor.component.html
src/app/feature/theme/theme-editor/theme-editor.component.scss
src/app/feature/theme/theme-editor/theme-editor.component.ts
src/app/feature/theme/theme-service/theme.service.ts
src/app/feature/theme/theme.model.ts

- Poulate theme using defaults
- Theme all home screen buttons
- Ensure default theme is plh teens 1
Also populate themes using base theme colors so different themes only have to specify colors that have changed.

Theming of home screen button colors

---

src/app/feature/theme/theme.model.ts

- Poulate theme using defaults
- Theme all home screen buttons
- Ensure default theme is plh teens 1
- Fix background var

Fix bg var

---

scripts/plh-xlsx-to-json/.gitignore
scripts/plh-xlsx-to-json/Readme.md
scripts/plh-xlsx-to-json/index.ts

PR Checklist
Update `plh-xlsx-to-json` script so that all xlsx files in any nested input folders will now be processed, merged with content list metadata and provide single output.
Work towards #122
[example-output-json.txt](https://github.com/IDEMSInternational/parenting-app-ui/files/5587578/example-output-json.txt)

update xlsx scripts

---

src/app/feature/chat/chat.module.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.html
src/app/feature/chat/components/chat-responses/chat-responses.component.scss
src/app/feature/chat/components/chat-responses/chat-responses.component.spec.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.ts
src/app/feature/chat/components/chat.page.html
src/app/feature/chat/components/chat.page.scss
src/app/feature/theme/built-in-themes.ts
src/app/feature/theme/theme.model.ts

- Message bubble styling to match designs
- Move chat responses into seperate component
PR Checklist
Changed message bubble colors.
Moved quick responses into it's own component.

Changed chat message bubble style to match Figma

---

src/app/feature/chat/chat.module.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.html
src/app/feature/chat/components/chat-responses/chat-responses.component.ts
src/app/feature/chat/components/chat-responses/responses-modal/responses-modal.component.html
src/app/feature/chat/components/chat-responses/responses-modal/responses-modal.component.scss
src/app/feature/chat/components/chat-responses/responses-modal/responses-modal.component.spec.ts
src/app/feature/chat/components/chat-responses/responses-modal/responses-modal.component.ts
src/app/feature/chat/components/chat.page.html
src/app/feature/settings/settings.page.html
src/app/feature/settings/settings.page.ts
src/global.scss

PR Checklist
Adds option in settings menu to change quick responses for chat so they show up in a modal.
_Closes #_

Modal quick responses can be enabled in settings

---

src/app/feature/chat/chat-routing.module.ts
src/app/feature/chat/chat.module.ts
src/app/feature/chat/guards/can-deactivate-chat.ts
src/app/feature/chat/services/offline/offline-chat.service.ts

PR Checklist
Show a warning alert popup when leaving the chat page part way through a flow.
Should not trigger for navigation actions that happen as part of chat.
_Closes #134

Show alert when leaving chat part way through flow

---

src/app/feature/chat/guards/can-deactivate-chat.ts
src/app/feature/settings/user.settings.model.ts

Spelling fixes

---

android/app/src/main/assets/capacitor.config.json
capacitor.config.json
src/app/shared/services/audio/audio.service.ts

PR Checklist
Fixes issue in Audio Service where audio plays twice when opening the same page with the same audio the second time.
Also fixes issue where audio not playing on Android by switching Android to use HTML5 audio player.
_Closes #163

Bug: Fix audio not playing (and playing twice in web)

---

src/app/feature/chat/components/chat.page.html
src/app/feature/chat/components/chat.page.ts
src/app/feature/chat/guards/can-deactivate-chat.ts
src/app/feature/chat/models/chat-service.models.ts
src/app/feature/chat/services/offline/offline-chat.service.ts
src/app/feature/chat/services/online/online-chat.service.ts
src/app/feature/settings/user.settings.model.ts

PR Checklist
Show flow name in my journey screen to aid with testing.

Show flow name in my journey screen for testing

---

scripts/plh-spreadsheet/conversation.translator.spec.ts
scripts/plh-spreadsheet/conversation.translator.ts
scripts/plh-spreadsheet/plh-spreadsheet.model.ts
scripts/plh-spreadsheet/process-content-spreadsheet.ts
scripts/plh-spreadsheet/toolbox.translator.ts

PR Checklist
- updated spreadsheet column names and fixed values to use `snake_case` as specified in [the documentation](https://docs.google.com/document/d/1zciubwEsHFsT7sKXhQvf4-yJsFGjTbEd-MLTBMr-6Cw/edit).
- updated converter to use `;` as the separator throughout and removed `,` as a separator
_Closes #_

Updated Excel converter in line with naming conventions and made semi-colon the separator consistently

---

src/app/feature/home/home.page.ts
src/app/feature/settings/settings.module.ts
src/app/feature/settings/settings.page.html
src/app/feature/settings/settings.page.ts
src/app/feature/settings/user-setting/user-setting.component.html
src/app/feature/settings/user-setting/user-setting.component.spec.ts
src/app/feature/settings/user-setting/user-setting.component.ts
src/app/feature/settings/user.settings.model.ts

PR Checklist
Splits user settings into actual end user settings, and development / testing settings.
_Closes #170

Development user settings section

---

.gitignore
README.md
android/app/build.gradle
package.json
scripts/package-lock.json
src/data/Conversation.ts
src/data/tips.ts

PR Checklist
Update with latest flowchart code from Google drive.

Updated content

---

src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/services/offline/offline-chat.service.ts

PR Checklist
Fixed bug where a parent flow entering a child flow, would not re-enter the parent flow when the child flow completed.

Fixed re-entering parent flows not working

---

src/app/feature/goals/components/goals.page.html
src/app/feature/settings/settings.page.ts

PR Checklist
Goes to correct welcome flow in settings. Also removes Today from "Things to do today"
_Closes #183 
_Closes #176

Go to correct welcome flow in settings

---

src/app/feature/chat/services/offline/offline-chat.service.ts
src/app/feature/settings/settings.page.html
src/app/feature/settings/settings.page.ts

PR Checklist
Provides a select flow option in the settings page that lets you see the list of chat flows in the app and launch any of them.
_Closes #184

Launch any flow from settings

---

src/app/app.component.html
src/app/app.component.scss
src/app/shared/components/plh-main-tabs.ts
src/app/shared/shared.module.ts

PR Checklist
- Add placeholder bottom bar
- Update container styles to support header and bottom nav
_Closes #_

add bottom tab bar

---

src/app/feature/module_list/skins/module-focus/components/habit-add.ts
src/app/feature/module_list/skins/module-focus/components/habit-tracker.ts
src/app/feature/module_list/skins/module-focus/components/slide-panel-bottom.ts
src/app/feature/module_list/skins/module-focus/components/slide-panel-right.ts
src/app/feature/module_list/skins/module-focus/module-focus.skin.html
src/app/feature/module_list/skins/module-focus/module-focus.skin.module.ts

PR Checklist
WiP - add basic bar, page and some extra styling
_Closes #_

Scaffold out habit tracker components

---

src/app/feature/chat/models/chat-msg.model.ts
src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/services/offline/router-case-matchers.ts
src/app/feature/chat/utils/message.converter.ts

PR Checklist
Fix bug with matching has only phrase router case.
Also fixed a typo in the continue flow method.

Fix bug with matching has only phrase

---

src/app/feature/module_page/flow-components/components/button.ts
src/app/feature/module_page/flow-components/components/description.ts
src/app/feature/module_page/flow-components/components/flow-components-common.scss
src/app/feature/module_page/flow-components/components/main_image.ts
src/app/feature/module_page/flow-components/components/step_group.ts
src/app/feature/module_page/flow-components/components/step_intro.ts
src/app/feature/module_page/flow-components/components/step_item.scss
src/app/feature/module_page/flow-components/components/step_item.ts
src/app/feature/module_page/flow-components/components/title.ts
src/app/feature/module_page/flow-components/flow-component.ts
src/app/feature/module_page/module-page.ts

PR Checklist
Shows the module steps on the module steps page

Show module steps on module steps page

---

src/app/feature/module_list/skins/module-focus/components/habit-add.ts
src/app/feature/module_list/skins/module-focus/components/module-select-circle/module-select-circle.component.html
src/app/feature/module_list/skins/module-focus/components/module-select-circle/module-select-circle.component.scss
src/app/feature/module_list/skins/module-focus/components/slide-panel-right.ts
src/app/feature/module_list/skins/module-focus/module-focus.skin.html
src/app/feature/module_list/skins/module-focus/module-focus.skin.scss
src/app/feature/module_page/flow-components/components/main_image.ts
src/app/feature/module_page/flow-components/components/step_item.scss
src/app/feature/module_page/skins/module-focus/module-focus.skin.html
src/app/feature/module_page/skins/module-focus/module-focus.skin.scss
src/app/shared/components/plh-main-header.ts
src/app/shared/components/plh-main-tabs.ts
src/theme/_layout.scss
src/theme/variables.scss

PR Checklist
- add global style functions
- improve styling of module_list and module_pages
_Closes #_

Global styles updates, module list and page styling

---

src/app/app.module.ts
src/app/feature/chat/chat.module.ts
src/app/feature/goals/components/task-reminder-item/task-reminder-item.component.ts
src/app/feature/goals/goals.module.ts
src/app/feature/module_list/module-list.html
src/app/feature/module_list/skins/module-focus/components/module-select-circle/module-select-circle.component.scss
src/app/feature/module_list/skins/module-focus/components/slide-panel-bottom.ts
src/app/feature/module_list/skins/module-focus/components/slide-panel-right.ts
src/app/feature/module_list/skins/module-focus/components/things-to-do-list.ts
src/app/feature/module_list/skins/module-focus/module-focus.skin.html
src/app/feature/module_list/skins/module-focus/module-focus.skin.module.ts
src/app/feature/module_list/skins/module-focus/module-focus.skin.scss
src/app/feature/module_list/skins/module-focus/module-focus.skin.ts

PR Checklist
Fix the styling of the bottom slider

Fix bottom slider styling

---

scripts/src/plh-data-convert/index.ts
scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.scss
src/app/feature/chat/components/chat-responses/chat-responses.component.ts
src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/components/chat.page.ts
src/app/feature/chat/services/offline/contact-field.service.ts
src/app/feature/chat/services/offline/offline-chat.service.ts
src/app/feature/chat/utils/message.converter.ts
src/app/pages/settings/settings.page.html
src/data/conversation.ts

PR Checklist
- add deploy_target to handle app and rapidpro builds differently
- revert uuid updates for rapidpro build (see #216)
- fix local image attachments bug and format image attachments
- fix end of flow bug
- fix example media and variable flows
_Closes #_

Chat system mixed fixes

---

src/app/feature/chat/components/chat.page.html

PR Checklist
Fixes a bug that could not render images for the "Neighbour" Character due to invalid asset name

match image with updated assets for Neighbour

---

src/app/feature/chat/services/offline/offline-chat.service.ts

PR Checklist
Before this fix a crash in one flow, would prevent the next flow from starting.
This was because the exception in the subscription to flow events caused the subscription for future events to unsubscribe.
_Closes #230

Stop a flow crash from breaking next flow open.

---

src/data/conversation.ts

data updates 2020-12-12

---

android/app/build.gradle
package.json

PR Checklist
new version for a new release
_Closes #_

Created new version: 0.6.1

---

src/data/conversation.ts

PR Checklist
Updated several spreadsheets to deal with errors before the release
fixes errors caused by inaccuracies in spreadsheets
_Closes #_

Updated stable data after correcting errors in spreadsheets

---

android/app/build.gradle
package.json
src/data/conversation.ts

PR Checklist
create new version: 0.6.2
_Closes #_

new version: 0.6.2

---

android/app/build.gradle
package.json
src/data/conversation.ts

V.0.6.4 prep

---

android/app/build.gradle
package.json

new release after build issues were resolved

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.html
src/app/feature/chat/components/chat.page.html
src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/components/chat.page.ts
src/app/feature/chat/models/chat-msg.model.ts
src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/utils/message.converter.ts
src/data/conversation.ts

PR Checklist
Re-adds ability to add images in response options.
Also adds ability to put images inside the chat message bubble.
_Closes #239

Images in response options

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat-responses/chat-responses.component.html
src/app/feature/chat/components/chat-responses/chat-responses.component.scss
src/app/feature/chat/components/chat-responses/chat-responses.component.ts
src/app/feature/chat/components/chat.page.html
src/app/feature/chat/models/chat-msg.model.ts
src/data/conversation.ts

PR Checklist
Show checkbox when spreadsheet asks for response options to be shown as a checkbox.
When checked only the button for the first response is show, when unchecked the second response is shown.
_Closes #238

Show checkbox in response options

---

src/app/pages/settings/settings.page.html

PR Checklist
Remove open welcome flow button in settings as this can now be reached from the launch flow selector.
_Closes #177

Remove open welcome flow button in settings

---

src/app/feature/chat/services/offline/offline-chat.service.ts
src/app/pages/settings/user.settings.model.ts

PR Checklist
Prevents settings change from causing flows to start multiple times (an extra time for each time settings are changed).

Prevent setting change doubling flows

---

src/app/feature/goals/components/anim-modal/anim-modal.component.scss

PR Checklist
neighbor jumping animation

neighbor jumping animation

---

src/app/feature/survey/surveys/intro-splash.survey.ts
src/assets/images/splash-screen/0.svg
src/assets/images/splash-screen/1.svg
src/assets/images/splash-screen/2.svg

PR Checklist
And splash screen blob images, and position and sizing of organisation logos.
_Closes #_

Add splash screen images

---

package.json
src/app/feature/goals/components/task-reminder-item/task-reminder-item.component.ts
src/app/feature/module_list/skins/module-focus/components/habit-add.ts
src/app/feature/module_list/skins/module-focus/components/habit-tracker.ts
src/app/shared/services/task/task-action.service.ts
src/app/shared/utils/utils.ts

PR Checklist
- add data bindings to track completed habits
- add ui for habit history
_Closes #_

implement habit history and tracker

---

src/app/feature/chat/services/offline/chat.flow.ts

PR Checklist
Use only one regex to match all @variable fields including
@contact.field_name
@fields.field_name
@results.result_name
This will support more app specific @variable types

Make @variable matching more generic

---

src/data/completion_list.ts
src/data/conversation.ts
src/data/goal_list.ts
src/data/habit_list.ts
src/data/module_page.ts
src/data/task_list.ts
src/data/tips.ts

PR Checklist
Update with latest Google sheets content.
_Closes #_

Content update

---

src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/services/offline/offline-chat.service.ts
src/data/conversation.ts

PR Checklist
Allow @habit.habit_id.weekly_count be used to display weekly count of that habit.

Habit weekly count

---

src/app/app-routing.module.ts
src/app/feature/care-packages/care-package/care-package.component.html
src/app/feature/care-packages/care-package/care-package.component.scss
src/app/feature/care-packages/care-package/care-package.component.spec.ts
src/app/feature/care-packages/care-package/care-package.component.ts
src/app/feature/care-packages/care-packages-routing.module.ts
src/app/feature/care-packages/care-packages.module.ts
src/app/feature/care-packages/care-packages.page.html
src/app/feature/care-packages/care-packages.page.scss
src/app/feature/care-packages/care-packages.page.spec.ts
src/app/feature/care-packages/care-packages.page.ts
src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/services/offline/offline-chat.service.ts
src/app/feature/module_list/skins/module-focus/components/habit-add.ts
src/app/shared/components/plh-main-tabs.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/data/data.service.ts
src/app/shared/services/db/db.service.ts
src/app/shared/services/habit/habit.model.ts
src/app/shared/services/habit/habit.service.spec.ts
src/app/shared/services/habit/habit.service.ts
src/app/shared/services/task/task.service.ts
src/assets/images/blob_holding_heart1.svg
src/assets/plh_assets/plh_images/care_packages/care_package_self.svg
src/assets/plh_assets/plh_images/care_packages/care_package_teen.svg
src/data/care_package_list.ts
src/data/habit_list.ts
src/data/task_list.ts

- Start of care packages
- Launch task from care package habit
- My aim button and count working
PR Checklist
Adds care packages screens, accessible from bottom tab button
_Closes #288

Care packages

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/utils/message.converter.ts
src/app/shared/model/flowTypes.ts
src/data/conversation.ts
src/data/task_list.ts
src/data/tips.ts

- Start of multiple <icon> and <image>
- Multiple icons working
- Content update
PR Checklist
Allows message text to have multiple icons in it.
e.g Hello this is icon 1 <icon> and this is icon 2 <icon>
Also allows media and icon column to be separated by new line
Also switches <story-image> to just <image>
_Closes #291

Multiple <icon> support

---

src/app/feature/chat/components/chat-responses/chat-responses.component.scss

PR Checklist
Fix quick response width when quick responses are long
e.g "Suggest other activities that we can do together instead of against each other"
_Closes #286

Fix quick response width

---

src/app/feature/chat/services/offline/offline-chat.service.ts

PR Checklist
Removes "End of this content" message

Remove "End of this content" message

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts

Support @habit condition variables

---

angular.json
package.json
src/app/feature/habit-ideas/habit-ideas.module.ts
src/app/feature/habit-ideas/habit-ideas.page.html
src/app/feature/habit-ideas/habit-ideas.page.scss
src/app/feature/habit-ideas/habit-ideas.page.ts
src/global.scss
src/index.html
yarn.lock

- Habit activity ideas screen
- Allow deleting habit activty ideas
- Drag suggested habit ideas to my list
PR Checklist
Allow dragging of suggested habit activity ideas to "My List" (the user ideas).
Deleting a suggested idea from my list causes it to appear in the suggested list again.
_Closes #303

Drag suggested habit activity ideas to my list

---

src/app/app-routing.module.ts
src/app/feature/habit-ideas/habit-ideas.page.html
src/app/feature/habit-ideas/habit-ideas.page.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/data/data.service.ts
src/assets/plh_assets/plh_images/modules/mod_instruct/illustrated_story/is_8.jpg
src/data/habit_ideas.ts
src/data/habit_list.ts

PR Checklist
Habit ideas refactor to use new worksheet format.

Habit ideas refactor

---

src/app/app-routing.module.ts
src/app/feature/home/home-routing.module.ts
src/app/feature/home/home.module.ts
src/app/feature/home/home.page.html
src/app/feature/home/home.page.scss
src/app/feature/home/home.page.spec.ts
src/app/feature/home/home.page.ts
src/app/shared/components/plh-main-header.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/data/data.service.ts
src/assets/plh_assets/plh_images/home_page/home_page_parent_center.svg
src/assets/plh_assets/plh_images/home_page/home_page_parent_points.svg
src/assets/plh_assets/plh_images/home_page/home_page_workshops.svg
src/data/home_page.ts
src/data/tour.ts

PR Checklist
New home screen. Configurable via this spreadsheet: https://docs.google.com/spreadsheets/d/1TzUiBdGn1ifQPm8zNEQhj9uGiARwSo-vAggAUkkTOKY/edit#gid=2103231405
_Closes #310
Options without gradient:

New home screen

---

src/app/app-routing.module.ts
src/app/feature/parent-points/parent-points-routing.module.ts
src/app/feature/parent-points/parent-points.module.ts
src/app/feature/parent-points/parent-points.page.html
src/app/feature/parent-points/parent-points.page.scss
src/app/feature/parent-points/parent-points.page.spec.ts
src/app/feature/parent-points/parent-points.page.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/db/db.service.ts
src/app/shared/services/habit/habit.model.ts
src/app/shared/services/habit/habit.service.ts
src/data/home_page.ts

Parent points screen

---

scripts/src/plh-data-convert/parsers/default/default.parser.ts
src/assets/plh_assets/plh_images/workshops/welcome1.svg
src/data/template.ts
src/data/tour.ts

PR Checklist
- fix parser for null types
- merge latest data updates
_Closes #_

Data Updates - 2021 02 16

---

src/app/shared/components/template/components/template_group.ts
src/app/shared/model/flowTypes.ts
src/data/component_defaults.ts
src/data/reminder_list.ts
src/data/template.ts

- Progress
- Override function works but infinite recursion bug
PR Checklist
Attempts to implement nested_properties.

Further templating infrastructure

---

src/app/shared/components/animations/index.ts
src/app/shared/components/animations/relax1/relax-anim1.scss
src/app/shared/components/animations/relax1/relax-anim1.ts

PR Checklist
Start of general system for CSS + SVG based animations.
Smiling relaxing blob with rings growing and shrinking around it.
View and search for animations at https://plh-teens-app1.web.app/animations

Animation browser

---

src/app/feature/template-testing/template-testing-routing.module.ts
src/app/feature/template-testing/template-testing.page.html
src/app/feature/template-testing/template-testing.page.ts

PR Checklist
- add a home `/template` page that lists all templates (for dev/debugging purposes)

add template list page

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/app/shared/components/template/components/debugger.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/app/shared/components/template/template-component.ts
src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- Create a queue system for processing actions in a synchronous way
- Fix dynamic field evaluation (wasn't returning a the calculated value :s )
- Re-bind hidden template evaluators
- Refactor debugger to own component and minor improvements
https://user-images.githubusercontent.com/10515065/110733256-79b9b780-81da-11eb-85c4-d9f1dac87df8.mp4
**Hidden Fields** - example using action that changes local variable state and toggles hidden property. Note, hidden fields still show in debug mode
https://user-images.githubusercontent.com/10515065/110733284-81795c00-81da-11eb-9fa0-d7dfa2fe9000.mp4
**Action Queuing** - simulating multiple actions that have 1.5s delay, still processed sequentially

Template action queuing and hidden display

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/app/shared/model/flowTypes.ts
src/assets/plh_assets/plh_audio/sample.mp3
src/assets/plh_assets/plh_images/other_icons/add-time.svg
src/assets/plh_assets/plh_images/other_icons/arrow.svg
src/assets/plh_assets/plh_images/other_icons/pause.svg
src/assets/plh_assets/plh_images/other_icons/play.svg
src/assets/plh_assets/plh_images/other_icons/repeat.svg
src/data/component_defaults.ts
src/data/template.ts

Data updates 2021 03 11

---

src/app/app.component.html
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
Temporary solution for events propogating up template component tree for emit completed.
Nav group then responds to completed / uncompleted events received by it's parent template and uses them to show the next / previous template.

Nav group going to next template

---

src/app/app.component.html
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

Shouldn't merge just before bed.

Revert "Nav group going to next template"

---

src/app/app.component.html

- Nav group going to next template
- Support @fields in templates
- Show progress bar on top of nav group
- Hide bottom main tabs
PR Checklist
Nav group going to next section on button click.

Nav group going to next section on next button click

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/app/shared/components/template/components/video.ts

PR Checklist
Fixes bug where video in assets/plh_assets was not being found
_Closes #354

Fix video not found in assets folder bug

---

scripts/src/plh-data-convert/parsers/default/default.parser.ts

PR Checklist
Adds row and sheet name in the logs if a group can't be processed due to an error such as no closing end_group row.

Print row and xlsx path on group parse error

---

src/app/shared/utils/utils.ts

PR Checklist
Fixes error where template would not render at all if parameter list for component was undefined.

Fix undefined parameter bug

---

src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
Add Help For Title Template Component. 
New parameters:
help - help text value (default null)
tooltipPosition - right | left | top | bottom (default right)

Feature: Title Template Component Help

---

src/app/shared/components/template/components/audio/audio.component.html
src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/audio/audio.component.ts
src/assets/plh_assets/plh_images/other_icons/arrow.svg
src/assets/plh_assets/plh_images/other_icons/pause.svg
src/assets/plh_assets/plh_images/other_icons/play.svg
src/data/template.ts

PR Checklist
Fix AudioPlayer Component Bugs

Fix: Audio Player Fix

---

src/app/shared/components/template/components/slider/slider.component.ts
src/app/shared/components/template/template-container.component.ts

- Fix action / parameter list when not dynamic
PR Checklist
Fixes issue where parameter_list or action_list items which didn't have a varaible in them (@global, @local) were not working.

Fix bug where non dynamic parameter_list or action_list was not working

---

src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/debugger.ts
src/app/shared/components/template/components/layout/animated_section.ts
src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss
src/app/shared/components/template/template-container.component.ts

PR Checklist
- merge/tidy container box and row name display code
- various minor debugger ui improvements
- link with query param `debugMode=true` or similar to allow persist across reload
_Closes #_

debugger updates

---

src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss

PR Checklist
Addition to previous debugger pr, to add template and template name to debugger top row
_Closes #_

add template name to debugger

---

src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss
src/app/shared/components/template/template-container.component.ts

PR Checklist
- add query param bindings for debug mode (with single toggle for all groups)
- add template breadcrumb data property (for future use)
_Closes #_

Handle debugger via query params

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
- [] - PR title descriptive (can be used in release notes)
This PR parses the local variables when you are processing variables within processVariable

Correcting the nesting of local variables - possibly temporary solution

---

src/app/shared/components/template/components/image.ts
src/app/shared/components/template/components/video.ts

Image assets path fixed

---

src/app/shared/components/template/components/timer/timer.component.ts
src/data/template.ts

Fix: Timer Seconds as value

---

src/app/shared/components/template/template-container.component.ts
src/data/template.ts

Hidden JS evaulation

---

src/app/shared/components/template/components/audio/audio.component.html
src/app/shared/components/template/components/audio/audio.component.scss
src/assets/icon/audio/arrow.svg
src/assets/icon/audio/pause.svg
src/assets/icon/audio/play.svg

PR Checklist
Fix: Add Audio Player Icons.
Fix: QA Feedback 16
Change minutes for input to seconds.
_Closes #_

Fix: Audio Player Icons and Header

---

documentation/template-component-parameter-list.md

PR Checklist
Template components documentation with parameters and value description
_Closes #_

Template components documentation

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.html
src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.scss
src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/text-box/text-box.component.html
src/app/shared/components/template/components/text-box/text-box.component.scss
src/app/shared/components/template/components/text-box/text-box.component.ts
src/app/shared/shared.module.ts
src/data/template.ts

PR Checklist
Add Template TextBox Component. 
Parameters:
- placeholder - placeholder text
- max-length - max value length
- value - text value
Add Template ComboBox Component
- value - selected value text
- style -  "pop-up",
- text - modal question text  (default null)
- placeholder - input placeholder text (default null)
- answer_placeholder - custom answer placeholder  (default null)
- max-length - max custom answer length (default 30)
- input_allowed - boolean - allow to provide user custom answer (default false),
- input_position - top | bottom - user custom answer position (default bottom)
- list_of_answers: Text1; Text2; Text3" - list of available answers splitted by ";"
_Closes #331 #330

Feature: Template TextBox Component | Template Combobox Component #363 - rebased

---

src/app/feature/template-testing/template-testing.page.html
src/app/feature/template-testing/template-testing.page.scss
src/app/feature/template-testing/template-testing.page.ts

PR Checklist
Add Search Box to Template List

Feature: Add Search Box to Template List

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/button.ts
src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts
src/app/shared/components/template/components/index.ts
src/data/template.ts

PR Checklist
Improve Buttom Template Component
Parameter list:
- value - text - button text
- color - color variable or hex. Default: primary
- disabled - boolean. Default: false
Test Template:  test_btn
_Closes #326

Feature: Template Button Component

---

src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
Add new Style to title
style: primary
_Closes #_

Fix: Title Style

---

src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B1.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B10.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B11.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B12.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B13.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B2.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B3.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B4.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B5.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B6.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B7.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B8.svg
src/assets/plh_assets/plh_images/workshops/money/Family budgeting-B9.svg
src/data/global.ts
src/data/template.ts

PR Checklist
PR Updates content from 25 March 2021 for demo

Content Update 21/03/25

---

src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/layout/layout.ts
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/model/flowTypes.ts

PR Checklist
- Create new template layout base component to simplify logic of other layout template components
- Add default completed/uncompleted trigger and emit actions for layout components
- Refactor nav_group template to extend layout base
_Closes #_

Common layout template and default actions

---

src/app/shared/components/template/components/dashed-box/dashed-box.component.html
src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/dashed-box/dashed-box.component.spec.ts
src/app/shared/components/template/components/dashed-box/dashed-box.component.ts
src/app/shared/components/template/components/index.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
Created Dashed Box Template Component
Parameter list:
style: class name component. banner_passive | banner_active. Default: banner_passive
value: text of component.
icon_src: path to image.
_Closes #_

Dashed Box Template Component

---

src/data/global.ts
src/data/template.ts

2021-03-27 data updates

---

src/app/shared/components/template/components/tile-component/tile-component.component.html
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/data/template.ts

PR Checklist
Fix Icon Click Effect and add Tile Click action trigger.
_Closes #_

Fix: Icon Click Effect and add Tile Click action trigger

---

scripts/src/gdrive-download/index.ts

PR Checklist
Fix sync-single to always download files
_
_Closes #_

Fix sync single to always download matching files

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.ts

PR Checklist
_Remove background color parameter for buttons_
_Closes #_

Remove background color parameter for buttons

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
_Fix: Title Help Position and White Style_
_Closes #_

Fix: Title Help Position and White Style

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts

fix boolean parsing

---

src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/components/template/components/radio-group/radio-group.component.scss
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/data/template.ts

PR Checklist
1. Add style active, passive to all radio_group types.
2. Fix parameters parsing for list.
3. Fix assets path handling. 
_Closes #463_
Active:
Passive:

Fix: radio_group styles, parameter parsing, and assets path parsing

---

src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
changed title font size if screen width of device is less than 375px
_Closes #474

changed title font-size

---

src/app/feature/template-testing/template-testing.page.scss

PR Checklist
Made the main container-component full screen height 
_Closes #470

full screen height for main template-container

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/layout/workshops_accordion.ts
src/app/shared/model/flowTypes.ts
src/theme/_typography.scss

added accordion layout components

---

src/app/shared/components/template/components/subtitle.ts

PR Checklist
Rename variable naming:
From text-align to text_align
#481 
_Closes #_

Feature: Subtitle text_align parameter rename

---

src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/layout/workshops_accordion.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/assets/plh_assets/plh_images/icons/tick_white.svg
src/data/template.ts

PR Checklist
Draft PR for accordion. 
1.  ability to toggle state of a section (open | close).
2. smooth animation for open and close.
3. ability to pass any template in a section.
4. progress bar.
5. hidden progress bar when section is open.
_Closes #_

accordion changes

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
This fixes a bug where popups created from a template that overrides / embeds and modifies another template that opens popups, would not open.
_Closes #

Fix popups not opening in overriden template

---

src/assets/plh_assets/plh_images/workshops/solve/read_2/slide_5.svg
src/data/global.ts
src/data/template.ts
src/data/tour.ts

PR Checklist
PR updates content on 8th april 21 for content review

Content update 21/04/08 for content review

---

src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
home screen needed to be done via template, not home_screen flow type
every section of the home screen is a display_group with a title and an image in it.
moving home screen into the templates.
_Closes #335 

home screen template

---

src/app/shared/components/template/template-container.component.ts
src/data/template.ts

PR Checklist
PR adds the ability to parse lists in _extractDynamicEvaluators so that when there is a list it still evaluate the variables.

Debug local variables in lists

---

src/assets/plh_assets/plh_images/workshops/praise/reflect_together/placeholder.svg
src/data/global.ts
src/data/template.ts

PR Checklist
PR Updates content into master on 12 April 2021 for content review

content update on 2021/04/12 for content review

---

src/app/shared/components/plh-main-header.ts

PR Checklist
Add new ion-button to header, on click navigate to /template
#513
_Closes #_

feat: add button to header

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
Small design fixes, add documentation for TmplTextComponent
Add examples TmplTextComponent.
Template: [TmplTextComponent](https://plh-teens-app1--pr536-feat-text-examples-a-4r7cad71.web.app/template/feature_text)
#501
_Closes #_

feat: update styles. add documentation for TmplTextComponent

---

src/app/shared/components/template/components/layout/popup.ts

PR Checklist
Improve popup styling by making popup taller when there is a lot of content in the popup, but not so tall that it covers the app header.
_Closes #_

Improve poup styling

---

src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/subtitle.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/theme/_typography.scss
src/theme/variables.scss

PR Checklist
PR updates progress on style refactoring

style changes

---

src/assets/plh_assets/plh_audio/topic_intro_instruct.mp3
src/assets/plh_assets/plh_audio/topic_intro_instruct.mp4
src/assets/plh_assets/plh_audio/topic_intro_praise.mp4
src/assets/plh_assets/plh_images/orli_upload_folder/celebration-04.svg
src/data/data_list.ts
src/data/global.ts
src/data/template.ts

PR Checklist
Updates content on 13th April to master for content review

content update 2021/04/13 for content review

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts
src/app/shared/components/template/components/layout/animated_section.ts
src/app/shared/components/template/components/subtitle.ts
src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts
src/theme/variables.scss

PR Checklist
refactoring title, subtitle, buttons
[title template](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1534534853)
[subtitle template](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1032308656)
[buttons template](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=98013889)
-buttons full width;
-buttons responsive height;
-the ability to use all styles from style guide through the table;
-add padding to animated section;
_Closes #545 

refactoring title/subtitle/buttons

---

documentation/template-component-parameter-list.md
src/app/shared/components/plh-main-header.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
Add classes: 
.row with value: flex-direction:row;
.column with value flex-direction: column;
Other:
Add default style align-items:center; to .display-grop
Fixed property text-align in plh-main-header component.
Template: [link](https://plh-teens-uat1--pr551-feat-display-group-s-4plkn5bw.web.app/template/feature_dg_styles_improve)
#543 #548
_Closes #_

Add styles to TmplDisplayGroupComponent

---

src/app/feature/template-testing/template-testing.page.scss
src/app/shared/components/template/components/layout/animated_section.ts

PR Checklist
fixed multiple margins bug in animated section.
have deleted padding from animated_section and added it to parent container.
_Closes #552

fixed animated section margin bug

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
fixed home screen styles
_Closes #563 

fixed home screen

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.scss

PR Checklist
_Closes #570 
https://user-images.githubusercontent.com/81557818/114817177-1e3ba480-9dec-11eb-887e-d955166394c0.mov

added scroll to combo box

---

src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tmpl-components-common.scss
src/assets/plh_assets/plh_images/icons/tick_light.svg
src/data/template.ts
src/theme/variables.scss

PR Checklist
-added tick icon
-changed gradient colours 
-added adaptive sizes for title and tile
-updated documentation
_Closes #565 

Accordion fixes

---

src/app/shared/components/template/template-component.ts

PR Checklist
fixed height for the buttons 
_Closes #574

fixed height of the buttons

---

src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tmpl-components-common.scss
src/assets/plh_assets/plh_images/icons/play_light.svg
src/data/template.ts
src/theme/variables.scss

accordion style changes

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/subtitle.ts
src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts
src/theme/variables.scss

PR Checklist
fixed styles classes for title and subtitle 
[subtitle template link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1032308656)
[title template link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1534534853)
_Closes #577 

title subtitle styles

---

src/app/shared/components/template/components/text-box/text-box.component.html

PR Checklist
Only trigger changed event on text box when enter is pressed or when the user clicks away (blur event).
_Closes #_

Text box changed trigger only on enter or blur

---

src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/tile-component/tile-component.component.html
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.ts

PR Checklist
fixed accordion tile icon
_Closes #582 

fixed accordion tile icon

---

src/data/global.ts
src/data/template.ts

PR Checklist
PR updates content and changes on 16 april to master for content review

content update for review 2021/04/16

---

src/app/shared/components/template/components/radio-group/radio-group.component.scss

PR Checklist
fixed radio group options per row:
-deleted padding and margin 
_Closes #557 

fixed radio group options

---

src/assets/plh_assets/plh_images/icons/play_outline_white.svg
src/assets/plh_assets/plh_images/orli_upload_folder/White tick.svg
src/data/global.ts
src/data/template.ts
src/data/tour.ts

2021-16-04 - Merge latest data

---

scripts/src/plh-data-convert/index.ts
scripts/src/plh-data-convert/parsers/template/template.parser.ts

- Audio player triggers
- Close popup action
- Add relax  animation json
- Fix template parser
- Remove unecessary formatting
PR Checklist
_Closes #_

Parser fix for audio events

---

src/app/shared/components/template/components/layout/nav_group.ts
src/theme/variables.scss

PR Checklist
-rounded edges
-made them a little higher
_Closes #597

rounded edges

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/dashed-box/dashed-box.component.html
src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/image.ts
src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/app/shared/components/template/components/text-box/text-box.component.html
src/app/shared/components/template/components/text-box/text-box.component.scss
src/app/shared/components/template/components/text-box/text-box.component.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/app/shared/components/template/components/video.ts
src/theme/_layout.scss

…argin and no_paddings styles
PR Checklist
_Closes #_

Margins for template components

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.html
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts

Fix round button click event for home screen

---

src/app/shared/components/template/components/number-selector/number-selector.component.html
src/app/shared/components/template/components/number-selector/number-selector.component.scss
src/app/shared/components/template/components/number-selector/number-selector.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts
src/app/shared/components/template/template-container.component.ts
src/data/template.ts

PR Checklist
Add trigger action to TmplCheckBoxComponent, TmplNumberSelectorComponent.
Refactoring styles
[NumberSelector](https://plh-teens-uat1--pr607-feat-trigger-action-0e4eb2tm.web.app/template/box_multi_1_temp)
[CheckBox](https://plh-teens-uat1--pr607-feat-trigger-action-0e4eb2tm.web.app/template/feature_checkbox)
_Closes #_

Feat/trigger action TmplCheckBoxComponent, TmplNumberSelectorComponent

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/global.ts
src/data/template.ts
src/theme/variables.scss

PR Checklist
-changed sizes for new styles
-made font size of the banner_short smaller (as a subtitle small -> 18px)
[template link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)
_Closes #601 

fixed size of the new banner styles

---

src/app/shared/components/template/components/slider/slider.component.scss

PR Checklist
removed slider margin left and right 
made slider-container wider as in the Design Feedback
_Closes #611 

removed margin from slider

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
added style 'banner_light' for white dashed box
_Closes #613 

added new dashed box style

---

src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
- made image smaller
- made text center
_Closes #_

new banner styles changes 

---

src/app/shared/components/template/components/button/button.component.scss

PR Checklist
made buttons make_me_smile and get_me_going taller by default with fit content width
_Closes #_

buttons style

---

src/data/template.ts
src/data/tour.ts

PR Checklist
Updates content into master for content review 20th April

Content unpdate for content review 2021/04/20

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/points-item/points-item.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.scss
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts

PR Checklist
Update scale-factro in TmplParentPointBoxComponent.
Update margin, padding in SimpleCheckBoxComponent, add parameter style.
[TemplatePointsItem](https://plh-teens-app1--pr622-fix-parent-point-dg-52rzhwzn.web.app/template/parent_points)
[TemplateCheckBox](https://plh-teens-app1--pr622-fix-parent-point-dg-52rzhwzn.web.app/template/feature_checkbox)
#621 
_Closes #_

update styles in simple-checkbox.component.html, points-item

---

src/app/shared/components/template/components/number-selector/number-selector.component.ts

PR Checklist
refactor nested ternary operators to if/else statement
#609
_Closes #_

fix: refactor nested ternary operators in TmplNumberSelectorComponent

---

src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/audio/audio.component.ts

PR Checklist
Fixed bug when audio keeps playing after leaving audio page.
_Closes #_

fix: audio keeps playing after leaving audio page

---

src/app/shared/services/tour/tour.service.ts

PR Checklist
Add new functionality parsing global variables from new spreadsheets like a "tour".
Фdd default assetsPrefix with value 'assets/plh_assets/plh_images' to property src in img tag
_Closes #_

Add new parsing global variables from spreadsheet tour

---

src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.ts

PR Checklist
-changed  size of tiles inside accordion section
Template:  [Link](https://plh-teens-uat1--pr620-accordion-refactorin-aynes8iw.web.app/template/weekly_workshops)
_Closes #619 

size of tiles

---

src/assets/plh_assets/plh_images/orli_upload_folder/Relax icon_blue.svg
src/assets/plh_assets/plh_images/orli_upload_folder/Relax icon_white.svg
src/data/global.ts
src/data/template.ts

PR Checklist
PR updates content and changes to master on 23 April for review

content update 2021/04/23 for content review

---

src/app/shared/components/template/components/audio/audio.component.html
src/app/shared/components/template/components/audio/audio.component.ts

PR Checklist
Add new functionality, when file is not played user can rewind the file
_Closes #_

feat: Forward and back buttons working when file is not playing

---

src/app/shared/components/template/components/timer/timer.component.html
src/app/shared/components/template/components/timer/timer.component.scss
src/assets/icon/timer/add-time.svg

PR Checklist
Change svg icon and add inside button value duration_extension from parameter list.
_Closes #_

feat: Display correctly value duration_extension in add-time TmplTimerComponent

---

src/app/shared/components/template/components/slider/slider.component.scss
src/app/shared/components/template/components/slider/slider.component.ts

PR Checklist
1. changed custom checkbox shape to circle.
2. ability to extract the value selected for a slider dynamically
3. If you select no answer before you select a number and then de-select it, the value goes to 'null' (not sure about this)
_Closes #638

slider fixes

---

src/app/shared/services/tour/tour.service.ts

PR Checklist
Change src from 'assets/plh_assets/plh_images/ to 'assets/plh_assets/'
_Closes #_

feat: refactoring tour image src

---

src/app/shared/components/template/components/text-box/text-box.component.html
src/app/shared/components/template/components/text-box/text-box.component.ts
src/data/template.ts

[PR](url) Checklist
added new parameter 'number_input: true/false'
[template](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1087467096)
_Closes #641 
https://user-images.githubusercontent.com/81557818/115740152-203fcd80-a3c1-11eb-943a-dcc36b487b43.mov

number text box

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/components/template/components/radio-group/radio-group.component.scss
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/app/shared/components/template/services/template.service.ts
src/data/template.ts
src/theme/variables.scss

PR Checklist
Add auto background, when parameter style dont includes defaulty styles: 'active' or 'passive'.
Add subscription on event set_theme, when combobox or radio dont have default styles.
[Template](https://plh-teens-app1--pr634-feat-radio-group-aut-u0ph0ouw.web.app/template/feature_radio_group)
_Closes #_

feat: add auto background for TmplRadioGroupComponent

---

src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss

PR Checklist
fixed misalignment of the navigation buttons
_Closes #647

fixed misalignment of the navigation btns

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
added possibility to control height of the image from [spreadsheet](https://docs.google.com/spreadsheets/d/1NrMPEVnn_misvqrKzxvRLY3PN0-dg1yc4rhiedSiss8/edit#gid=139871760)
_Closes #655 

Survey welcome image

---

src/app/shared/components/template/components/timer/timer.component.scss
src/app/shared/components/template/components/timer/timer.component.ts
src/global.scss

PR Checklist
added dots between  numbers
reduced space between numbers
_Closes #649 

fixed scrollable numbers

---

src/app/shared/components/template/components/radio-group/radio-group.component.scss

PR Checklist
made radio groups tiles sized  similar with or without text.
_Closes #653

height of the radio group

---

src/app/feature/survey/surveys/intro-splash.survey.ts
src/app/shared/components/template/components/points-item/points-item.component.ts
src/app/shared/components/template/components/slider/slider.component.ts

PR Checklist
PR fixes bugs for release: temporary fix to parent point tiles to dynamically evaluate number of points. fix to slider to set field at the same time as set local. changed value in splash screen.

bugs fixed for release

---

src/data/template.ts
src/data/tour.ts

PR Checklist
PR updates content and changes for release 26th April

content update for release 2021-04-26

---

android/app/build.gradle
package.json

new version number 0.9.1

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
Add auto background to display group component, when parameter style dont includes default styles with property background.
[](url)
_Closes #_

feat: add auto background to display_group.ts

---

src/global.scss

PR Checklist
made the color of the dots the same with numbers  
_Closes #_

changed color of timer slider dots

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.html
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
src/data/template.ts

PR Checklist
[template](https://docs.google.com/spreadsheets/d/1tmtdyeSYcqGH6joqZiA-wPtH0QH6td8hA3qGp62AcHs/edit#gid=646539876)
changed icons path from '/assets/icon/' to 'plh_images/icons/' 
_Closes #662 

changed path of the icons for round icon buttons

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.html
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts

fixed round icon bug

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
added possibility to use lottie animations on the home screen.
[spreadsheet link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1361559004)
[template link](http://localhost:4200/template/feature_home)
_Closes #668

lottie animations on the home screen

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.html
src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.ts

PR Checklist
made answer list for the combo box like the answer list for the radio buttons
[spreadsheet link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=763902434)
[template link](http://localhost:4200/template/feature_combo_box)
_Closes #665

answer list for the combo box

---

src/app/shared/components/template/components/debugger.ts
src/app/shared/components/template/pipes/markdown.pipe.ts
src/app/shared/components/template/template-container.component.ts
src/data/data_list.ts

PR Checklist
- Fix issue where setting a field doesn't prompt immediate re-render
- Add global to debug logging
- Fix minor markdown render bug
_Closes #_
https://user-images.githubusercontent.com/10515065/116373906-b92d7900-a805-11eb-9371-d054badaf4fe.mp4

trigger re-render on set_field

---

src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Home Practise icon_v2_blue.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Home Practise icon_v2_white.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Letter icon_v2_blue.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Letter icon_v2_white.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Play icon_v2_blue.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Play icon_v2_white.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Relaxing icon_v2_blue.svg
src/assets/plh_assets/plh_images/orli_upload_folder/New icons/Relaxing icon_v2_white.svg
src/data/data_list.ts
src/data/global.ts
src/data/template.ts

PR Checklist
Latest content in master for testing

conten update on master

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/data/template.ts

WiP - Compare script changes

---

src/app/app.component.html
src/app/pages/settings/settings.page.html
src/app/pages/settings/settings.page.ts

PR Checklist
PR updates sliding menu on the left to add link to in-week messages, and tidies up the settings page.

Tidy up settings page

---

src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/data/template.ts
src/theme/variables.scss

PR Checklist
fixed workshop statuses. 
workshops appear as unlocked if disabled is false.
changed background of the statuses
_Closes #680

workshops status

---

scripts/src/plh-data-convert/parsers/default/default.parser.ts
scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts

PR Checklist
Fix local variable overwrites for deep nested values
_Closes #_

fix dynamic deep nesting

---

src/app/shared/components/template/components/image.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
added style rounded_corners for images 
_Closes #685
_If useful, provid
e screenshot or capture to highlight main changes_

rounded_corners for images

---

src/app/shared/components/template/components/slider/slider.component.html
src/app/shared/components/template/components/slider/slider.component.scss
src/app/shared/components/template/components/slider/slider.component.ts

PR Checklist
- better handling of 'no_value' and undefined values and slider disabling
- method and class name tidying
_Closes #_

update slider component

---

src/app/feature/survey/surveys/analytics/analytics.survey.html
src/app/feature/survey/surveys/analytics/analytics.survey.scss

PR Checklist
Temporarily disable google log in
Adjusted content and style of terms and conditions page

Feat disable google login

---

android/app/build.gradle
package.json

PR Checklist
version update for release

version update for release

---

src/app/pages/settings/settings.page.html
src/app/pages/settings/settings.page.ts

PR Checklist
add setting to unlock workshops

Added setting to unlock workshops

---

src/data/global.ts
src/data/template.ts

PR Checklist
Update content into master for pre-release review

Content update for pre-release review 4th April

---

src/app/shared/components/template/mocks/template-merge.mock.ts
src/app/shared/components/template/utils/template-utils.ts

fix deep nest

---

src/data/global.ts
src/data/template.ts
src/data/tour.ts

PR Checklist
Update content for release on 4th May

Content update for release

---

android/app/build.gradle
package.json

PR Checklist
New version for release

new version for release

---

src/app/shared/components/template/components/image.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
added rounded_corner style for images 
_Closes #685

Round img corners

---

src/app/shared/components/template/components/layout/popup.ts

PR Checklist
added overflow to pop ups
_Closes #707 
https://user-images.githubusercontent.com/81557818/117416052-91e45380-af4b-11eb-8d00-a1140976c77f.mov

pop_ups bug

---

src/app/app.component.ts

PR Checklist
hard coded fields to calculate difference in days from current day and first app opening and unlock workshop 2 if more than 6 days

hard coding of fields to unlock workshop for week 2 after 6 days

---

src/app/feature/tour/tour.component.ts
src/global.scss

PR Checklist
tour doesn’t go off the screen anymore
_Closes #713

fixed position of the tour

---

src/app/shared/components/template/components/layout/popup.ts

PR Checklist
added possibility to close pop up on backdrop click
_Closes #725

close pop up on backdrop click

---

src/app/app.component.ts

PR Checklist
Add hardcoded fields on first initialise to avoid doubling up of quickstart buttons.

temporary fix to avoid doubling up of quickstart buttons

---

src/app/shared/components/template/components/icon.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/model/flowTypes.ts

PR Checklist
- created new component 'TmplIconComponent' in order to avoid color problems 
_Closes #714

new icon component

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
scripts/src/utils/index.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/utils/index.ts
src/app/shared/utils/utils.ts
src/app/shared/utils/variables.utils.ts
src/data/template.ts

PR Checklist
- Merge latest data updates (needed for checking changes to scripts)
- Refactor dynamic scripts methods to be available to app at runtime
- Add runtime evaluation of deep nested dynamic variables
_Closes #_
https://plh-teens-app1--pr728-feat-multiple-locals-288j4cvq.web.app/template/example_multiple_locals

Add support for runtime dynamic variables (e.g. @local.@local.someVar)

---

src/app/shared/components/template/components/radio-group/radio-group.component.scss
src/data/template.ts

PR Checklist
made size of the buttons look the same, regardless of parameter 'options_per_row'.
_Closes #739

Radio group size

---

src/app/shared/components/template/components/text-box/text-box.component.html
src/app/shared/components/template/components/text-box/text-box.component.ts

PR Checklist
- added boolean parameter prioritise_placeholder (Default: false);
_Closes #743

prioritise placeholder text box

---

src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.ts

PR Checklist
- added boolean parameter prioritise_placeholder (Default: false);
_Closes #747

prioritise placeholder combo box

---

src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts
src/app/shared/components/template/services/template.service.ts

PR Checklist
- fix checkbox field update bindings
- change @fields and @global missing value default return to undefined (instead of {{@fields.missingFieldname}})
- fix radio_group initial value setting
_Closes #_

fix component triggered field setting

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/data/template.ts

PR Checklist
- Fixed value of the combo box.
- The text associated with answers_list item displayed
[Spreadsheet link](https://docs.google.com/spreadsheets/d/13h4OJiMok3XG9DklnRzVmUue_9cXydVTclI4Ixb5nAo/edit#gid=1916689711)
----
- Fixed custom answer
- When a typed answer is submitted, it displayed in the combo box
[Spreadsheet link](https://docs.google.com/spreadsheets/d/13h4OJiMok3XG9DklnRzVmUue_9cXydVTclI4Ixb5nAo/edit#gid=1595229908)
_Closes #746

combo box value & custom answer

---

src/app/shared/components/template/components/number-selector/number-selector.component.ts

PR Checklist
- Add initial value override for saved values
_Closes #_

fix number-selector init bindings

---

src/app/feature/template-testing/template-testing.page.scss
src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.scss
src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/icon-banner/icon-banner.component.scss
src/app/shared/components/template/components/number-selector/number-selector.component.scss
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/theme/variables.scss

PR Checklist
- colours from middleware variables instead of hardcoded colours  
_Closes #_

styles refactoring

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/text-area/text-area.component.html
src/app/shared/components/template/components/text-area/text-area.component.scss
src/app/shared/components/template/components/text-area/text-area.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- added new 'text_area' component
[example spreadsheet](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1824352647) 
_Closes #752 

text_area component

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
Remove code that prevented dynamic dependencies being used within template rows (should still be handled correctly as stripped out by child template on init)
_Closes #_
https://user-images.githubusercontent.com/10515065/118647930-cb358280-b7d9-11eb-835f-29b8ef808e1f.mp4

fix nested dynamic action list

---

scripts/src/plh-data-convert/utils/plh-action.utils.ts
scripts/src/plh-data-convert/utils/plh-condition.utils.ts
scripts/src/utils/string-utils.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/data/data-evaluation.service.ts
src/app/shared/utils/utils.ts

Fix parsing for arg strings representing boolean values

---

src/app/app.component.ts

PR Checklist
Hardcoded fields for workshop campaigns (unlocking and quickstart) as a temporary fix

temporary fix: hardcoded fields for campaigns

---

src/data/data_list.ts
src/data/global.ts
src/data/template.ts
src/data/tips.ts

PR Checklist
Update latest content for release

content update for release v 0.9.6

---

src/app/shared/components/template/components/text-area/text-area.component.html
src/app/shared/components/template/components/text-area/text-area.component.scss
src/app/shared/components/template/components/text-area/text-area.component.ts
src/data/template.ts

PR Checklist
- added set value action to text_area
- fixed height of the text_area
_Closes #_

changes for text_area

---

src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/theme/variables.scss

PR Checklist
- smaller icon 
- default background white
_Closes #764 

dashed box styles

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.scss
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- added advanced_dashed_box component
_Closes #766

advanced_dashed_box component

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/toggle-bar.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- created toggle_bar component
[feature_toggle_bar](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=550703021) 
_Closes #_

toggle bar component

---

src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/layout/accordion_section.ts
src/data/template.ts

PR Checklist
- added a pop-up appearing by click for accordion section if it is disabled.
_Closes #771 

accordion pop up

---

src/app/feature/survey/surveys/analytics/analytics.survey.html

PR Checklist
Changed wording in the T&C page

updated terms and conditions page

---

src/app/shared/components/template/components/layout/accordion_section.ts
src/assets/plh_assets/plh_images/icons/in_progress.svg
src/assets/plh_assets/plh_images/icons/in_progress_white.svg
src/assets/plh_assets/plh_images/icons/temporarily_disabled.svg
src/assets/plh_assets/plh_images/icons/temporarily_disabled_white.svg

PR Checklist
Added 2 new icons in blue and white
Updated route to new icons in accordion section

updated icons in workshop accordion

---

android/app/build.gradle
package.json

PR Checklist
Updates version number to 0.9.7 for release

Version update for release 0.9.7

---

src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.ts
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/subtitle.ts
src/data/template.ts

PR Checklist
- fixed infinite loop
- text align param for subtitle.   
[debug_advanced_dashed_box](https://docs.google.com/spreadsheets/d/1vnij3ASAYSvOXe4wU9F9BKl52SjTeTKZ_QkKl81fUnc/edit#gid=697081060)
_Closes #_

fix advanced dashed box infinite loop / text align

---

android/app/build.gradle
package.json

version update

---

src/app/shared/components/template/components/timer/timer.component.ts
src/assets/audio/timer/ping_1.wav
src/assets/audio/timer/ping_2.wav
src/data/template.ts

PR Checklist
- added two ping sounds for timer
- added parameter to define ping sound [ping: whatever]
[feature_timer_ping](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=780498113)
_Closes #782 

 timer ping sound

---

src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.scss
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/components/number-selector/number-selector.component.scss
src/app/shared/components/template/components/points-item/points-item.component.scss
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.scss
src/app/shared/components/template/components/slider/slider.component.scss
src/app/shared/components/template/components/text-area/text-area.component.scss
src/app/shared/components/template/components/text-box/text-box.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/timer/timer.component.scss
src/app/shared/components/template/components/tmpl-components-common.scss
src/app/shared/components/template/template-container.component.scss
src/global.scss
src/theme/mixins.scss
src/theme/variables.scss

PR Checklist
- got rid of hard coded sizes, replaced them with middleware variables 
_Closes #_

Refactoring styles

---

src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.ts
src/app/shared/components/template/components/layout/display_group.ts
src/data/template.ts

PR Checklist
- changed logic in order to read type from styles
_Closes #786 

display group 'type' to 'style'

---

src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.ts
src/app/shared/components/template/components/layout/display_group.ts
src/data/template.ts

PR Checklist
- fixed the display group style definition method.
_Closes #807 

fix - display group style 

---

src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.scss
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts
src/data/template.ts

PR Checklist
- added param 'align' in order to control checkbox position
- [feature_checkbox](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1210506143)
_Closes #805 

 checkbox position

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/assets/plh_assets/plh_audio/timer/ping_1.wav
src/assets/plh_assets/plh_audio/timer/ping_2.wav
src/data/data_list.ts
src/data/global.ts
src/data/template.ts

PR Checklist
- Sync latest data
- Minor whitespace fix
_Closes #_

Data sync - 2021 06 05

---

src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
- fixed an issue with wrapping text
_Closes #811

fix text wrapping

---

src/app/shared/model/flowTypes.ts

PR Checklist
- add exclude_from_translation into tour and global flows
_Closes #803

exclude_from_translation into flows

---

src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/layout/form.ts
src/data/template.ts

PR Checklist
- added ability to pass an action into form
- [feature_form](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1654153446)
_Closes #801 

action params for form

---

src/app/shared/components/template/components/timer/timer.component.ts
src/assets/audio/timer/ping_1.wav
src/assets/audio/timer/ping_2.wav
src/data/template.ts

PR Checklist
- added pings into plh_assets
- changed logic in order to read ping from plh_assets folder 
_Closes #799

fixed path for timer ping

---

src/app/shared/components/template/components/text.ts
src/app/shared/components/template/pipes/index.ts
src/app/shared/components/template/pipes/numbering.pipe.ts
src/data/template.ts

PR Checklist
- added pipe in order to number a list
- require to provide a parameter into text component (type: marked | numbered)
[debug_ordered_list](https://docs.google.com/spreadsheets/d/179iFkCnMIIPelDRp9WRBEx8FgPT9SoUNM9eXIW4UQj4/edit#gid=1489640820)
_Closes #773 

nambering pipe for text

---

scripts/src/plh-data-convert/utils/plh-action.utils.ts
src/app/shared/components/template/components/index.ts
src/app/shared/model/flowTypes.ts

add new action list types

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.html
src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.scss
src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- created parent-point-counter component
- [box_parent_points](https://docs.google.com/spreadsheets/d/10C-Y0t59m5E4GR5dCLpgii16tBuE3mvWcmxGA_9H7RM/edit#gid=57214870)
_Closes #_

parent-point-counter

---

src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.html
src/data/template.ts

PR Checklist
- removed hardcoded number from tex
_Closes #_

parent point counter 

---

src/app/shared/components/template/components/layout/nav_group.ts

PR Checklist
- fixed workshops continue from the right step
- added new method which getting actual step from current progress of the workshop
_Closes #814

workshops continue 

---

src/app/feature/survey/surveys/analytics/analytics.survey.scss
src/app/feature/survey/surveys/intro-splash.survey.ts

PR Checklist
Update number of parents reached by PLH
Allow scrolling on terms and conditions page

Updates on splash screens

---

src/app/shared/components/template/components/points-item/points-item.component.scss
src/app/shared/components/template/components/points-item/points-item.component.ts

PR Checklist
Following #813 (should merge 813 first)
Minor changes to parent point animation to support better scaling
_Closes #_
https://user-images.githubusercontent.com/10515065/121252514-f05b6500-c85c-11eb-8ba8-34fa34ed5e64.mp4

parent point animation scaling

---

android/app/build.gradle
package.json

PR Checklist
Update version to 0.9.9

updated version number to 0.9.9

---

documentation/template-component-parameter-list.md

PR Checklist
- updated documentation according to this [template](https://docs.google.com/document/d/1oqinnpqGhNrRp9ZGyVn5JWk5E57UsfBNYp0waRYH3d4/edit?usp=sharing)
_Closes #_

updated documentation

---

src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.scss

PR Checklist
- changed styles for better scaling 
_Closes #833 

parent point counter scaling

---

scripts/src/plh-data-convert/parsers/default/default.parser.ts
src/app/feature/campaign/campaign.service.ts

PR Checklist
- Fixes issue where data_lists would not populate if referring to `@row.text::eng`
- Minor log changes
_Closes #_

Support colon character in @row replacements

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.ts
src/data/template.ts
src/theme/variables.scss

PR Checklist
- added new tile style
- updated documentation
[feature_tile](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=388166020)
_Closes #_

new tile style 'image_text'

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts

PR Checklist
- changed default alignment
- looks like it needs only for buttons. Tiles do not support it. Every text component left aligned by default
_Closes #_

change default alignment

---

scripts/package.json
scripts/src/plh-data-convert/index.ts
scripts/src/plh-data-convert/parsers/default/default.parser.ts
scripts/yarn.lock

PR Checklist
Add more context to errors thrown from all flow parsers. See red box in screenshot for additional info now populated
_Closes #_

Scripts parser error logging

---

src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/layout/accordion_section.ts
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tmpl-components-common.scss
src/theme/variables.scss

PR Checklist
-changed styles according to figma
_Closes #_

workshops style changes

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/tile-component/tile-component.component.html
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.ts
src/theme/variables.scss

PR Checklist
- added new tile style 
- updated documentation
- [feature_tile_button](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1882691872)
_Closes #_

new tile style 'button'

---

src/app/shared/components/template/components/layout/accordion.scss
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/theme/variables.scss

PR Checklist
-changed name of the style. Previous coincided with css style
- fixed height 
_Closes #_

simple changes for tile button

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/help-icon.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/template-component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- added new component help_icon
- update documentation
- [feature_help_icon](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1962267037)
_Closes #_

new component help_icon

---

src/app/shared/components/template/components/text.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts

PR Checklist
- added new method to define break lines in a text. 
- [debug_text_paragraphs](https://docs.google.com/spreadsheets/d/1A159jPS8rSDnA2GDUTda6xeC_Kyu3oYk_-KbuhzMqmQ/edit#gid=1342264693)
_Closes #_

text break lines

---

src/app/shared/components/template/services/template.service.ts

convert "undefined" fields to undefined

---

src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.scss

PR Checklist
- changed stars position 
_Closes #_

stars position in parent point counter

---

src/app/shared/components/template/components/text.ts
src/app/shared/components/template/components/tmpl-components-common.scss

PR Checklist
- changed styles for paragraphs and lists 
[debug_var_in_bulleted_list](https://docs.google.com/spreadsheets/d/1UusKwmH8a4VGqolUe4X6i7d7wlHpFPui-_xYGGJLiig/edit#gid=1595229908)
[debug_text_paragraphs](https://docs.google.com/spreadsheets/d/1A159jPS8rSDnA2GDUTda6xeC_Kyu3oYk_-KbuhzMqmQ/edit#gid=1342264693)
_Closes #_

fixed break lines / bulleted list

---

src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.scss

PR Checklist
- fixed width of the dashed boxes (same as other components)
- checked box components width. 
_Closes #_

dashed boxes same width

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/subtitle.ts
src/app/shared/components/template/components/text.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/theme/variables.scss

PR Checklist
- changed default font size for text to 20px
_Closes #_

changed default font size

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/square-icon-button/square-icon-button.component.html
src/app/shared/components/template/components/square-icon-button/square-icon-button.component.scss
src/app/shared/components/template/components/square-icon-button/square-icon-button.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts
src/theme/variables.scss

PR Checklist
- created new component 'square_button'
- updated documentation
- [feature_square_button](https://docs.google.com/spreadsheets/d/1fzBOs4MuFDK80JhxIMmoPU6aTSD-zG6bSTfaghRv3xg/edit#gid=1401291899)
_Closes #_

square button

---

src/app/shared/components/template/components/text.ts

fixed dynamic changes

---

src/app/shared/components/template/components/layout/popup.ts
src/data/template.ts

PR Checklist
- changed styles for pop ups according to figma.
- [feature_pop_ups](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=684201828)
_Closes #_

pop ups styles

---

src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.html

PR Checklist
- added background color for selected input
_Closes #_

input background 

---

src/data/data_list.ts
src/data/global.ts

PR Checklist
update content for release v0.9.10 on 23 june

Update content for release v0.9.10

---

android/app/build.gradle
package.json

PR Checklist
Updates version number to v0.9.10

version update to v0.9.10 for release

---

src/app/shared/components/template/services/template-row.service.ts

PR Checklist
Update UAT with master after fixing hiding issue

Update UAT post error fixing in v0.10.0

---

src/global.scss

PR Checklist
-changed tour next button color
_Closes #_

tour next button color

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/toggle-bar/toggle-bar.scss
src/app/shared/components/template/components/toggle-bar/toggle-bar.ts
src/data/template.ts

PR Checklist
- added icons for toggle bar
- added new parameter to show and hide the icons
- updated documentation
_Closes #_

icons for toggle bar

---

documentation/template-component-parameter-list.md
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/title.ts

PR Checklist
- added two_columns_images style for display group
- updated documentation 
- [feature_two_columns_images](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1541544222)
- [feature_two_columns_images_2](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=885480382)
_Closes #_

new two_columns_images style

---

package.json
src/app/shared/components/template/services/template-calc.service.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/utils/utils.ts
src/main.ts

PR Checklist
- Change how global functions are included in dynamic variable calculations as these are broken during optimisation step of production build
- Revert build script change to make ```production``` build by default
- Minor log change to exclude console logs from native builds (for improved performance)
_Closes #_
```v0.10.0``` - now appears to be working as intended

Fix production build

---

src/app/shared/components/template/components/tile-component/tile-component.component.ts

PR Checklist
temporary fix to issue created in PR #877. New issue #878 to fix this better soon

temporary fix to issue arising from PR #877

---

src/app/shared/components/template/services/template-row.service.ts
src/app/shared/utils/utils.ts

PR Checklist
Update previous change to hidden field overrides so that FALSE values are not assumed when field empty
_Closes #_
https://user-images.githubusercontent.com/10515065/124171652-b1848d80-da5d-11eb-8d1b-ae79a739cc1b.mp4

fix hidden overrides

---

src/assets/plh_assets/plh_audio/workshops_reflection.mp3
src/data/data_list.ts
src/data/global.ts

PR Checklist
PR updates content for release v0.10.2

Content update for release v0.10.2

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.10.2

update version number to v0.10.2

---

src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/template-component.ts

PR Checklist
- fixed nav buttons bag on android
- fixed progress bar gaps between on native mobile
_Closes #870 

nav buttons bag on android

---

packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Cross icon_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Green tip icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Home Practice icon in circle_icon.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Ligh bulb icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Lock in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Parent Library icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Red cross icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Star icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Survay images_shadow 1.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Survay images_shadow 2.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Survay images_shadow 3.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Survay images_shadow 4.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Survay images_shadow 5.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/Tick icon_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/unlock icon in circle_new.svg
packages/plh-data/assets/plh_assets/plh_images/orli_upload_folder/www icon in circle_new.svg
packages/plh-data/data/data_list/data_list.ts
packages/plh-data/data/global/global.ts

PR Checklist
PR updates content for release v0.10.3 and some changes to data files that came as a consequence of PR #895

Content update for release v0.10.3

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.10.3
Note: Had to do it manually as the version script was not working

update version number to v0.10.3

---

src/app/feature/survey/surveys/analytics/analytics.survey.html

PR Checklist
Fixed a typo in the terms and conditions splash screen

Fixed a typo in the Terms and conditions splash screen

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other-issues.md

Modified bug report template and added feature request and other issues templates

Update issue templates

---

package.json
packages/scripts/src/decrypt-config.ts
packages/scripts/src/encrypt-config.ts
packages/scripts/src/gdrive-download/auth.ts
packages/scripts/src/paths.ts
packages/scripts/src/plh-copy-app-data.ts
packages/scripts/src/plh-data-convert/parsers/default/default.parser.ts
packages/scripts/src/resize-android-assets.ts
packages/scripts/src/version.ts

PR Checklist
- Create common scripts `Paths` file to keep a single list of main folder locations
- Update path handling to fix scripts execution
- Minor formatting updates
Closes #

fix scripts paths

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.10.4

update version number to v0.10.4

---

src/app/shared/services/server/server.service.ts
src/environments/environment.ts
tsconfig.json
yarn.lock

PR Checklist
- Update tsconfig to reduce files watched for changes
- Remove server tracking for local development
Closes #

minor config updates

---

packages/plh-data/model/flowTypes.ts
src/app/shared/components/template/components/index.ts

PR Checklist
- Core type updates and component bind to allow `debug_toggle` component use from templates
Work towards #920

add debug-toggle template component

---

packages/plh-data/model/flowTypes.ts
src/app/shared/utils/variables.utils.ts

PR Checklist
- Cross check all dynamic variables against named list to avoid assuming something like `user@domain.com` is a dynamic variable
Closes #

add stricter checks for dynamic variables

---

src/app/app.component.html
src/app/app.component.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
- add local developer mode to improve debugging
- add option to ignore query param changes for templates
- ignore query param changes from sidemenu templates
Closes #

Fix app side menu duplicate actions

---

README.md
packages/plh-data/data/data_list/data_list.campaign_rows.ts
packages/plh-data/data/template/template.debug.ts

PR Checklist
PR Update Content for Release v0.10.5

Content update for release v0.10.5

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.10.5

update version number to v0.10.5

---

packages/plh-data/assets/plh_assets/plh_audio/timer/bell_1.mp3
packages/plh-data/data/data_list/data_list.campaign_rows.ts
packages/plh-data/data/data_list/data_list.debug.ts
packages/plh-data/data/data_list/data_list.ts
packages/plh-data/data/global/global.debug.ts
packages/plh-data/data/global/global.ts
packages/plh-data/data/template/template.debug.ts
packages/plh-data/data/tour/index.ts
packages/plh-data/data/tour/tour.debug.ts
packages/plh-data/data/tour/tour.ts
packages/plh-data/data/translation_strings/index.ts
packages/plh-data/data/translation_strings/spa.ts
packages/plh-data/data/translation_strings/translation_strings.ts

PR Checklist
PR updates content for release v0.10.6

Content update for release v0.10.6

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.10.6

Update version number to v0.10.6

---

packages/plh-data/model/flowTypes.ts

PR Checklist
Update types to support future pr for template loop-items and process-on-start.
Closes #

add support for items flowtype

---

packages/plh-data/model/flowTypes.ts
src/app/app.component.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/group.ts
src/app/shared/components/template/services/template-calc.service.ts
src/app/shared/components/template/services/template-row.service.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/components/template/utils/template-utils.ts
src/app/shared/services/server/server.service.ts
src/app/shared/utils/utils.ts

PR Checklist
This builds from PR #942, which should be merged first to view proper diff.
- Add support for 3rd party date-utilities library date-fns within calc statements
- Add support for custom hardcoded variables within calc statements
- Add core app and device calc variables
- Improve example calc sheets
Closes #
[Example Calc GSheet](https://docs.google.com/spreadsheets/d/15TccctjzepSPPv9xrLp46fhYldNN0wrho1zA5voTYcg/edit#gid=1595229908)

Template calc system improvements

---

packages/plh-data/model/flowTypes.ts

PR Checklist
Add type support for upcoming template startup PR to add `process_on_start` content column and `process_template` action types
Closes #

type updates for template startup

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
angular.json
package.json

PR Checklist
Reverting changes from PR #950 as it caused problems in the display (of nav buttons).

Revert commits from PR #950

---

packages/plh-data/assets/plh_assets/plh_audio/relax/relax_10_audio.mp3
packages/plh-data/data/care_package_list/index.ts
packages/plh-data/data/completion_list/index.ts
packages/plh-data/data/component_defaults/index.ts
packages/plh-data/data/conversation/index.ts
packages/plh-data/data/data_list/index.ts
packages/plh-data/data/global/index.ts
packages/plh-data/data/goal_list/index.ts
packages/plh-data/data/habit_ideas/index.ts
packages/plh-data/data/habit_list/index.ts
packages/plh-data/data/home_page/index.ts
packages/plh-data/data/module_list/index.ts
packages/plh-data/data/module_page/index.ts
packages/plh-data/data/task_list/index.ts
packages/plh-data/data/template/index.ts
packages/plh-data/data/tips/index.ts
packages/plh-data/data/tour/index.ts
packages/plh-data/data/translation_strings/index.ts
packages/plh-data/data/translation_strings/spa.ts

PR Checklist
Content update for release v0.11.1

Content update for release v0.11.1

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.11.1

Update version number to v0.11.1

---

packages/plh-data/assets/plh_assets/i18n/flags/gb.svg
packages/plh-data/assets/plh_assets/i18n/flags/za.svg
packages/plh-data/assets/plh_assets/plh_audio/timer/bell_1.mp3
packages/plh-data/assets/plh_assets/plh_audio/timer/ping_1.wav
packages/plh-data/assets/plh_assets/plh_audio/timer/ping_2.wav
packages/plh-data/data/data_list/data_list.campaign_rows.ts
packages/plh-data/data/data_list/data_list.debug.ts
packages/plh-data/data/data_list/data_list.ts
packages/plh-data/data/global/global.debug.ts
packages/plh-data/data/global/global.ts
packages/plh-data/data/habit_ideas/habit_ideas.ts
packages/plh-data/data/module_page/module_page.ts
packages/plh-data/data/template/template.debug.ts
packages/plh-data/data/tour/tour.debug.ts
packages/plh-data/data/tour/tour.ts
packages/plh-data/data/translation_strings/index.ts
packages/plh-data/data/translation_strings/spa.ts
packages/plh-data/data/translation_strings/tsa.ts
packages/plh-data/data/translation_strings/xho.ts
packages/plh-data/data/translation_strings/zul.ts

PR Checklist
PR updates content for release v0.11.2

Content update for release v0.11.2

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.11.2

Update version number to v0.11.2

---

packages/plh-data/translations/from_translators/translated.za.xho.json
packages/plh-data/translations/from_translators/translated.za.zul.json

PR Checklist
Correct minor mistakes in translated content.

Translation updates

---

packages/test-e2e/projects/plh/integration/bugs/example_pop_ups.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_emit.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_go_to.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_go_to_1.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_go_to_2.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_go_to_3.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_text.spec.ts
packages/test-e2e/projects/plh/integration/example_actions/example_update_actions.spec.ts

PR Checklist
- Added cypress tests for example_actions which include 7 templates (example_go_to_1, example_go_to_2, example_go_to_3,example_emit,example_text,example_update_actions, example_pop_ups).
Closes #

Cyress tests for example_actions

---

packages/data-models/flowTypes.ts

PR Checklist
Type updates required for #1019. Merged to allow example_analytics template to be published
Closes #

add support for track_event action type

---

packages/plh-data/translations/from_translators/translated.es.spa.json

PR Checklist
Add "Audio message" to Spanish translation.

Update Spanish translation

---

packages/plh-data/assets/plh_assets/plh_audio/quality_assurance/sample.mp3
packages/plh-data/assets/plh_assets/plh_audio/quality_assurance/test.eng.mp3
packages/plh-data/assets/plh_assets/plh_audio/quality_assurance/test.esp.mp3
packages/plh-data/assets/plh_assets/plh_audio/sample.mp3
packages/plh-data/data/data_list/data_list.campaign_rows.ts
packages/plh-data/data/data_list/data_list.campaign_rows_debug.ts
packages/plh-data/data/data_list/data_list.notification_schedule.ts
packages/plh-data/data/data_list/data_list.ts
packages/plh-data/data/data_list/index.ts
packages/plh-data/data/global/global.debug.ts
packages/plh-data/data/global/global.ts
packages/plh-data/data/template/template.debug.ts
packages/plh-data/data/tour/tour.debug.ts
packages/plh-data/data/translation_strings/spa.ts
packages/plh-data/data/translation_strings/tsa.ts
packages/plh-data/data/translation_strings/xho.ts
packages/plh-data/data/translation_strings/zul.ts

PR Checklist
PR updates content for release v0.11.3

Content update for release v0.11.3

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.11.3

Update version number to v0.11.3

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
src/app/shared/components/template/components/subtitle.ts
src/app/shared/components/template/components/tile-component/tile-component.component.html
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/title.ts
src/app/shared/components/template/components/toggle-bar/toggle-bar.ts
src/app/shared/components/template/template-container.component.scss

PR Checklist
(tbc)
- Markdown rendering Issues are now resolved on the ```debug_markdown``` template.
closes #960

markdown syntax issue 

---

src/app/app.component.ts

PR Checklist
Add organisation registration screen to first launch.

Add organisation registration to first launch

---

packages/plh-data/translations/from_translators/translated.tz.swa.json

PR Checklist
Upload Tanzania Swahili translation

Upload Tanzania Swahili translation

---

src/app/feature/survey/surveys/analytics/analytics.survey.html

PR Checklist
- grammar correction commitment 1
- remove "anonymous" claim from commitment 3

Rephrase app commitments

---

src/app/shared/components/template/services/template.service.ts

PR Checklist
Quick workaround to force field and global defaults to re-initialise each app load (to account for newly added data)
Closes #

reinitialise default field and globals on init

---

packages/plh-data/assets/plh_assets/i18n/flags/tz.svg
packages/plh-data/assets/plh_assets/plh_lottie/habits/habit_breathe.mp4
packages/plh-data/data/conversation/conversation.ts
packages/plh-data/data/data_list/data_list.campaign_rows.ts
packages/plh-data/data/data_list/data_list.debug.ts
packages/plh-data/data/data_list/data_list.ts
packages/plh-data/data/global/global.debug.ts
packages/plh-data/data/global/global.ts
packages/plh-data/data/template/template.debug.ts
packages/plh-data/data/tour/tour.debug.ts
packages/plh-data/data/tour/tour.ts
packages/plh-data/data/translation_strings/index.ts
packages/plh-data/data/translation_strings/swa.ts
packages/plh-data/data/translation_strings/zul.ts
packages/plh-data/translations/from_translators/translated.za.zul.json

PR Checklist
PR updates content for release v0.12.2

Content update for release v0.12.2

---

android/app/build.gradle
package.json

PR Checklist
Update version number to v0.12.2

Update version number to v0.12.2

---

.github/workflows/android-release.yml
.github/workflows/firebase-hosting-merge-uat.yml
.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/trigger-build.yml

PR Checklist
Recent updates to yarn mean cache now invalidated. Update all github actions to update caching strategy
Closes #

update gh action caches

---

packages/app-data/translations/from_translators/translated.tz_sw.json
packages/app-data/translations/from_translators/translated.za_af.json
packages/app-data/translations/from_translators/translated.za_tn.json
packages/app-data/translations/from_translators/translated.za_xh.json
packages/app-data/translations/from_translators/translated.za_zu.json

PR Checklist
PR updates translations for release v0.12.3

Translations update for release v0.12.3

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.12.3

Update version number to v0.12.3

---

src/app/shared/components/template/components/toggle-bar/toggle-bar.scss

PR Checklist
Add back icons for toggle-bar and further tidying of style rules
Closes #

add icons back into toggle bar

---

documentation/docs/developers/adding-components.md
documentation/mkdocs.yml

PR Checklist
Add documentation for developers adding new components
Closes #

add developer component docs

---

documentation/docs/authors/template-component-parameter-list.md

PR Checklist
Minor docs updates as copied from #1086
Closes #

update radio params docs

---

.gitpod.yml

PR Checklist
Add configuration for development via https://www.gitpod.io/
Closes #

feat: add gitpod config

---

.gitpod.yml

PR Checklist
Minor fixes to gitpod config
Closes #

chore: add gitpod lfs support and ng serve

---

src/app/shared/services/settings.service.ts

PR Checklist
Previously reset app would reload on the current page which could lead to some unexpected behaviours. Now reset redirects to home screen
Closes #
https://user-images.githubusercontent.com/10515065/152435566-11be77e6-ccda-47fb-8223-d84cdcb89875.mp4

fix: redirect to home page after reset

---

packages/scripts/src/commands/app-data/convert/parsers/default/default.parser.ts

PR Checklist
Tidy logging of deprecated fields to also indicate name of template
Closes #

chore: tidy deprecated field messages

---

packages/app-data/translations/from_translators/translated.es_sp.json

PR Checklist
Update Spanish (debug) translation

Update Spanish (debug) translation

---

packages/app-data/translations/from_translators/translated.es_sp.json

PR Checklist
Merge master into content update

Merge master into content update

---

src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.scss
src/app/shared/components/template/components/layout/popup.ts

PR Checklist
Fix height style issue preventing scroll in full-screen popups
Closes #1217
https://user-images.githubusercontent.com/10515065/152430672-90311a65-c661-403e-b313-f2eb27054ce7.mp4

fix: fullscreen popup scroll

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to v0.14.2

Update version number to v0.14.2

---

.github/workflows/android-build.yml
.github/workflows/android-release.yml
.github/workflows/build-and-upload.yml
.github/workflows/firebase-hosting-merge-uat.yml
.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/test-appetize.yml
packages/app-data/data/template/index.ts
packages/app-data/data/template/template.example_hardcoded.ts
packages/data-models/constants.ts
src/app/app.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

PR Checklist
- Add bindings to automatically populate a `_deployment_name` field with the current deployment name
- Add example template to highlight known hardcoded fields
Debug sheet should show as working correctly, can also try changing app deployment name (to something more desirable) and confirm working. Although if changing a corresponding change will need to be made to github secrets so let me know if that's the case (see dev note below)
I can't remember if any of these hardcoded variables are documented elsewhere, if not might be good to make a note somewhere. 
Currently the scripts that build and deploy the app from the cloud work on the assumption that whatever is in the repo is what we want built. However, in order to access the deployment name we need to access the specific …

feat: add deployment name field mapping

---

packages/api/package.json

PR Checklist
Update API docker build scripts to populate version tag from package version
Closes #

chore: update api build version

---

documentation/docs/components/button.md
documentation/docs/components/images/button.png
documentation/mkdocs.yml

PR Checklist
Added button component documentation to the website

Added button component documentation

---

packages/api/package.json
packages/server/docker/docker-compose.yml
packages/server/package.json

PR Checklist
Minor versioning updates from work on server
Closes #

chore: minor version bumps and script change

---

packages/scripts/src/commands/deployment/set.ts

chore: update logging

---

packages/data-models/db.model.ts
src/app/shared/services/db/db-sync.service.ts

chore: add app version to server sync

---

packages/server/docker/docker-compose.yml

PR Checklist
Reduce size of logs files retained on server
Closes #

chore: reduce docker logging

---

package.json
packages/api/Dockerfile
packages/api/package.json
packages/api/spec-export.json
packages/api/src/endpoints/app_notification_interaction/app_notification_interaction.service.ts
packages/api/src/main.ts
packages/server/docker/docker-compose.yml
src/app/shared/services/notification/local-notification-interaction.service.ts
yarn.lock

PR Checklist
- Fix server build issue that could prevent latest update from being deployed
- Upgrade server build tooling, improve build speed and reduce build size
- Add support for updating synced interaction data on update (e.g. previously ignored but then tapped)
Closes #

fix: notification interaction

---

.github/workflows/deployment-preview.yml
.github/workflows/firebase-hosting-pull-request.yml

PR Checklist
- Add automation scripts to help process of generating preview builds for deployment branches
Closes #

feat: add deployment preview action

---

packages/app-data/translations/from_translators/translated.tz_sw.json
packages/app-data/translations/from_translators/translated.za_st.json

PR Checklist
Updates translations with Crowdin as of 25.03.2022.

Translations update 25.03.2022

---

src/app/app.component.ts
src/app/feature/theme/theme-editor/theme-editor.component.ts
src/app/feature/theme/theme-service/theme.service.ts
src/theme/variables.scss

PR Checklist
Comments out code for dark mode theming
Temp fix for #1300

fix: disable theme service

---

android/app/build.gradle
package.json

chore: bump version

---

documentation/docs/components/images/round_button.png
documentation/docs/components/round_button.md
documentation/mkdocs.yml

PR Checklist
Added round button component documentation to the website.

Added round button component documentation 

---

.gitattributes
.idems_app/deployments/plh/global.config.ts
.prettierignore
.prettierrc
packages/data-models/deployment.model.ts
packages/data-models/workflows.ts
packages/scripts/src/commands/workflow/run.ts
packages/scripts/src/tasks/providers/file.ts

PR Checklist
- Add gitattributes to try and force git to use consistent crlf line-endings
- Add workflow to make it easier to clear cached task data (side-effect of alternative approach)
It would be good to test if this makes a difference, if possible please:
- checkout this branch
- update current deployment (`yarn scripts deployment set`)
- sync content `yarn workflow sync`
Hopefully this should result in a cleaner output (instead of 1k file changes only those with meaningful change)
If this does not work you could also try clearing some of the git cache via:
```
rm .git/index
git reset
git status
```
And possibly try another `yarn workflow sync` after
Closes #

chore: attempt fix for crlf line-endings and add clean_cache workflow

---

documentation/docs/components/audio.md
documentation/docs/components/button.md
documentation/docs/components/html.md
documentation/docs/components/images/latex.png
documentation/docs/components/latex.md
documentation/docs/components/round_button.md
documentation/docs/components/square_button.md
documentation/mkdocs.yml

PR Checklist
Adds a page to the documentation explaining the usage of the latex component

docs: Added documentation for latex component

---

src/app/feature/theme/built-in-themes.ts
src/app/feature/theme/theme-editor/theme-editor.component.scss
src/app/feature/theme/theme-editor/theme-editor.component.spec.ts
src/app/feature/theme/theme-service/theme.service.spec.ts
src/app/feature/theme/theme.model.ts
src/app/shared/components/common/directives/connectedoverlayscrollhandler.ts
src/app/shared/components/template/components/dashed-box/dashed-box.component.ts
src/app/shared/components/template/components/icon-banner/icon-banner.component.ts
src/app/shared/components/template/components/number-selector/number-selector.component.spec.ts
src/app/shared/components/template/components/number-selector/number-selector.component.ts
src/app/shared/components/template/components/parent-point-counter/parent-point-counter.component.ts
src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts
src/app/shared/components/template/components/slider/slider.component.spec.ts
src/app/shared/components/template/template-container.component.spec.ts
src/app/shared/services/audio/audio.player.ts
src/app/shared/services/audio/audio.recording.service.ts
src/app/shared/services/audio/audio.service.spec.ts
src/app/shared/services/audio/ionic.audio.player.ts
src/app/shared/services/auth/auth.service.spec.ts
src/app/shared/services/db/db.service.spec.ts
src/app/shared/services/event/event.service.spec.ts
src/app/shared/services/ipc/ipc.service.spec.ts
src/app/shared/services/ipc/ipc.service.ts
src/app/shared/services/local-storage/local-storage.service.spec.ts
src/app/shared/services/notification/local-notification.service.spec.ts
src/app/shared/services/tour/tour.service.spec.ts

PR Checklist
Minor fix to run code auto-formatter across files which previously have not been formatted
Closes #

chore: lint fix files

---

.firebaserc
firebase.json

PR Checklist
add firebase config to support efm deployment
Closes #

chore: add efm deployment

---

packages/app-data/sheets/global/home_screen_variables.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/component_demo/comp_animated_slides.json
packages/app-data/sheets/template/component_demo/comp_html.json
packages/app-data/sheets/template/m_relax.json
packages/app-data/sheets/template/relax.json

PR Checklist
PR updates content.

Content sync 28/04/2022

---

src/app/app.component.ts

PR Checklist
Remove hack first-open logic no longer required
Closes #

chore: remove first open fields

---

packages/app-data/sheets/data_list/debug/efm_act_list.json
packages/app-data/sheets/data_list/debug/efm_chapter_list.json
packages/app-data/sheets/global/app_menu_globals.json
packages/app-data/sheets/global/localised_names.json
packages/app-data/sheets/global/localised_names_tz.json
packages/app-data/sheets/global/localised_names_za.json
packages/app-data/sheets/global/names_of_characters.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/app_menu_enter_dev_mode.json
packages/app-data/sheets/template/app_menu_exit_dev_mode.json
packages/app-data/sheets/template/box_video.json
packages/app-data/sheets/template/component_demo/comp_animated_slides.json
packages/app-data/sheets/template/component_demo/comp_animated_slides_fullscreen.json
packages/app-data/sheets/template/debug/debug_emit_force.json
packages/app-data/sheets/template/debug/debug_nesting_conditional.json
packages/app-data/sheets/template/debug/efm_activity_template.json
packages/app-data/sheets/template/debug/efm_chapter_acts_1.json
packages/app-data/sheets/template/debug/efm_chapter_acts_2.json
packages/app-data/sheets/template/debug/efm_chapters.json
packages/app-data/sheets/template/debug/example_pop_ups.json
packages/app-data/sheets/template/ending.json
packages/app-data/sheets/template/lets_slow_down_lyrics.json
packages/app-data/sheets/template/splash_screens.json
packages/app-data/sheets/template/w_self_care_relax.json

PR Checklist
PR updates content to include 
- video transcript and button
- new codes for enabling developer mode (`ParentApp_test` to be shared externally, `app_dev` for development)

Content update 04/05/2022

---

angular.json

PR Checklist
Adjust max core app build from 3MB -> 4MB
Closes #

chore: adjust build budgets

---

packages/app-data/sheets/index.ts
packages/app-data/sheets/template/common_with_parent_text/lets_slow_down_lyrics.json
packages/app-data/sheets/template/sign_in.json

Content sync 17/05/2022

---

packages/app-data/assets/global/plh_images/logos/partners/plh.png
packages/app-data/assets/index.ts
packages/app-data/sheets/template/component_demo/comp_video.json

PR Checklist
PR updates content to include new PLH logo

Content update 20/05/2022

---

packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_1on1.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_consequence.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_crisis.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_instruct.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_money.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_praise.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_rules.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_safe.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_self_care.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_solve.mp3
packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_stress.mp3
packages/app-data/assets/global/plh_audio/testimonies/teen/w_1on1.mp3
packages/app-data/assets/global/plh_audio/testimonies/teen/w_rules.mp3
packages/app-data/assets/index.ts
packages/app-data/sheets/data_list/workshop_data_list.json
packages/app-data/sheets/template/home_practice.json

PR Checklist
PR updates content to include caregiver testimonials.

Include caregiver testimonials

---

documentation/docs/questions/dynamic_content.md
documentation/docs/questions/hidden_condition.md
documentation/docs/questions/parameters_styles.md
documentation/docs/questions/positioning_components.md
documentation/mkdocs.yml

PR Checklist
PR adds documentation suggested in https://github.com/IDEMSInternational/parenting-app-ui/pull/1395#issuecomment-1136901392

Add hidden and dynamic content questions

---

packages/app-data/sheets/data_list/Akadelis_Lucky_Day_pages.json
packages/app-data/sheets/data_list/Can_We_Count_Our_Cats_pages.json
packages/app-data/sheets/data_list/Cat_And_Dog_And_The_Ball_pages.json
packages/app-data/sheets/data_list/Cat_And_Dog_And_The_But_pages.json
packages/app-data/sheets/data_list/Cat_And_Dog_And_The_Egg_pages.json
packages/app-data/sheets/data_list/Clever_Cat_pages.json
packages/app-data/sheets/data_list/Colors_Of_A_Rainbow_pages.json
packages/app-data/sheets/data_list/efm_sb_list.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/app_menu.json
packages/app-data/sheets/template/app_menu_privacy_policy.json
packages/app-data/sheets/template/efm_activity_advice_template.json
packages/app-data/sheets/template/efm_activity_template.json
packages/app-data/sheets/template/efm_chapter_acts_by_topic.json
packages/app-data/sheets/template/efm_chapter_acts_individually.json
packages/app-data/sheets/template/efm_chapters.json
packages/app-data/sheets/template/efm_storybooks.json
packages/app-data/sheets/template/home_screen.json

PR Checklist
PR Updates EFM content to include Privacy Policy

Deployment dev/early family math

---

android/app/build.gradle
package.json

PR Checklist
PR updates version to 0.16.2 prior to new release

Update version to 0.16.2

---

.github/workflows/test-visual-compare.yml
packages/test-visual/src/commands/compare.ts

fix: screenshot compare typo

---

packages/app-data/sheets/template/box_slider.json
packages/app-data/sheets/template/box_yes_no_slider.json

PR Checklist
PR updates content, in particular, it includes the app version number in the survey fields.

Content update 23/06/2022

---

src/app/shared/services/auth/auth.service.ts

PR Checklist
Remove auth data previously copied from firebase to idems db. Now only unique firebase `uid` retained which can be used for lookup on firebase server
This will not remove existing data from the database or any additional databases derived from it, and so will require somebody with access and knowledge of such things to clean existing data 
Closes #

chore: remove auth data

---

packages/app-data/assets/global/plh_images/logos/unicef.png
packages/app-data/assets/index.ts
packages/app-data/sheets/data_list/funders_data_list.json
packages/app-data/sheets/data_list/organisations_tz_data_list.json
packages/app-data/sheets/data_list/organisations_za_data_list.json
packages/app-data/sheets/data_list/partners_data_list.json
packages/app-data/sheets/data_list/partners_tz_data_list.json
packages/app-data/sheets/data_list/partners_za_data_list.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/accept_terms.json
packages/app-data/sheets/template/accept_terms_warning.json
packages/app-data/sheets/template/component_demo/comp_combo_box.json
packages/app-data/sheets/template/organisation_registration.json
packages/app-data/sheets/template/organisation_registration_tz.json
packages/app-data/sheets/tour/home_screen_tour_intro.json
packages/app-data/sheets/tour/home_screen_tour_menu.json

PR Checklist
PR updates content as of 23 July 2022.

Update content 23/07/2022

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version to 0.16.3

Update version number to 0.16.3

---

package.json
src/app/shared/components/template/components/select-text/select-text.component.ts
yarn.lock

PR Checklist
Fixes bug where the text did not get copied to the native clipboard correctly in the Android build.
Closes #1450 
Copy and paste functionality working as expected in emulator:
https://user-images.githubusercontent.com/64838927/180756195-7c8b70ef-a9c9-407c-8317-578f1f44d266.mov

bug: fixed issue where text was not copied to clipboard on Android

---

packages/app-data/test/index.ts

PR Checklist
Include `component_demo` flow subtypes in visual tests
Note - I would probably suggest we merge this and then re-run the visual tests on #1439 before it is merged
Closes #

chore: update visual test sheets

---

packages/app-data/sheets/data_list/example_sheet_defaults/example_sheet_defaults_list.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/example_sheet_defaults/example_sheet_defaults.json
packages/app-data/sheets/template/w_instruct_question_1.json
packages/app-data/sheets/template/w_instruct_question_2.json
packages/app-data/sheets/template/w_rules_question.json
packages/app-data/sheets/template/w_safe_question_1.json
packages/app-data/sheets/template/w_safe_question_2.json
packages/app-data/sheets/template/w_stress_question.json

PR Checklist
PR updates global PLH content as of 03 August 2022

Content update 03/08/2022

---

packages/app-data/sheets/data_list/example_sheet_defaults/example_sheet_defaults_list.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/example_sheet_defaults/example_sheet_defaults.json
packages/scripts/src/commands/app-data/convert/index.ts
packages/scripts/src/commands/app-data/convert/parsers/default/default.parser.ts
packages/scripts/src/commands/app-data/convert/parsers/template/template.parser.ts

PR Checklist
**Main Changes**
- Add support for using `@default` top-row in any sheet to populate as default values throughout
- Add support for `@include_default` and `@omit_default` to append or omit default values for a given row
- Create example datalist [example_sheet_defaults_list](https://docs.google.com/spreadsheets/d/1witVIPxVBJsok1c2CtmEOSIfBgm73RNlxdp2RyoDE9w/edit#gid=1694318910)
- Create example template [example_sheet_defaults](https://docs.google.com/spreadsheets/d/1witVIPxVBJsok1c2CtmEOSIfBgm73RNlxdp2RyoDE9w/edit#gid=409059068)
**Additional Changes**
As part of testing I included setting an entire action_list from a datalist as part of an item loop (e.g. `@item.data_list`) and discovered that this was not actually supported (only able to set string values, such as …

feat: add support for sheet defaults in parser

---

packages/shared/src/utils/templating.spec.ts

PR Checklist
Minor logging commit missing from merge #1463
Closes #

chore: add console logs

---

packages/shared/src/utils/templating.spec.ts
packages/shared/src/utils/templating.ts

PR Checklist
Builds on #1473 to improve handling of dynamic contexts and general tidying. Will merge into open PR for easier review processes
Closes #

Feat: template literals dynamic context and tidying

---

packages/scripts/src/commands/app-data/convert/index.ts
packages/scripts/src/commands/app-data/convert/parsers/default/default.parser.ts
packages/scripts/src/commands/app-data/convert/parsers/template/template.parser.ts
packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
packages/shared/src/utils/templating.spec.ts

chore: code tidying

---

packages/app-data/sheets/index.ts
packages/app-data/sheets/template/box_story_pages.json
packages/app-data/sheets/template/box_story_scroll.json
packages/app-data/sheets/template/debug/example_items_nav.json
packages/app-data/sheets/template/debug/example_items_radio.json

PR Checklist
PR updates content, in particular, it includes the template box_story_pages which is a step towards having the current read workshop activities authored through data lists

Update content 19/08/2022 (2)

---

LICENCE.md
LICENSE
package.json

PR Checklist
The repo was never correctly-licensed when setup. Assign a GNU GPL v3 license. 
Closes #

Apply GNU GPL v3 license

---

.idems_app/deployments/plh/tz.config.ts

PR Checklist
PR updates TZ deployment config so that tz_sw is the default language.

Update TZ config to set tz_sw as default language

---

src/app/shared/components/template/services/template-variables.service.ts

PR Checklist
Add fallback for case where campaign returns no rows
Closes #
**Console now just shows error on empty campaigns**
**Previous error message**

fix: empty campaigns

---

packages/app-data/assets/global/plh_images/habits/relax_chair.gif
packages/app-data/assets/index.ts
packages/app-data/sheets/data_list/parent_centre_data_list.json
packages/app-data/sheets/data_list/safeguarding_categories_tz.json
packages/app-data/sheets/data_list/safeguarding_contacts_tz.json
packages/app-data/sheets/data_list/survey_data_list.json
packages/app-data/sheets/data_list/workshop_data.json
packages/app-data/sheets/global/debug/example_glob_override_modular.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/component_demo/comp_select_text.json
packages/app-data/sheets/template/debug/example_parent_point_box.json
packages/app-data/sheets/template/debug/example_parent_point_box_info.json
packages/app-data/sheets/template/debug/example_skin_override_default.json
packages/app-data/sheets/template/debug/example_skin_override_modular.json
packages/app-data/sheets/template/debug/example_skin_select.json
packages/app-data/sheets/template/debug/feature_parent_point_box.json
packages/app-data/sheets/template/parent_centre_support_category.json
packages/app-data/sheets/template/parent_centre_support_con.json
packages/app-data/sheets/template/parent_centre_support_con_tz.json
packages/app-data/sheets/template/relax.json

PR Checklist
PR updates PLH content. In particular
- TZ safeguarding data lists and templates
- updated survey data list

Content updates 04/10/2022

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number.

Update version number to 0.16.5

---

packages/app-data/sheets/index.ts
packages/app-data/sheets/template/debug/example_items_pipe_2.json

PR Checklist
PR updates PLH and debug content as of 11/10/2022

Content update 11/10/2022

---

android/app/build.gradle
package.json
packages/app-data/sheets/template/user_code.json

PR Checklist
PR updates version number and user code template ahead of PLH TZ release v0.16.6 (specifically for including the user ID QR code)

Release prep/2022 10 13

---

packages/app-data/sheets/data_list/generated/workshop_tasks.json
packages/app-data/sheets/data_pipe/workshop_data_pipe.json
packages/app-data/sheets/index.ts

PR Checklist
PR updates PLH content.

Content sync: Append workshop skipped, completed field columns

---

packages/app-data/sheets/data_list/debug/debug_data_list.json
packages/app-data/sheets/data_list/generated/workshop_tasks.json
packages/app-data/sheets/data_pipe/workshop_data_pipe.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/debug/feature_highlighted_task.json
packages/app-data/sheets/template/footer.json
packages/app-data/sheets/template/home_screen.json
packages/app-data/sheets/template/home_screen_modular.json
packages/app-data/sheets/template/module_card.json

PR Checklist
PR updates PLH content, including some progress on populating the Modular Skin homescreen

Content/2022 10 26(2)

---

src/app/shared/components/template/components/task-card/task-card.component.ts
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
Follow-up on #1594, which was merged too early
Closes #

fix: Task card – removed '_list' suffix from data list param name

---

packages/app-data/sheets/template/debug/example_go_to_1.json

PR Checklist
PR makes a trivial content change into master, so that it's different from `deployment/plh_content_review`, and can be merged into that branch through a PR, to trigger the deployment hosting.

Trivial content change to trigger deployment hosting (1)

---

packages/app-data/sheets/template/debug/example_go_to_1.json

PR Checklist
PR ensures a web preview is created to be shared with content/translation reviewers.

Create PLH Content Review web preview

---

android/app/build.gradle
package.json

Update version number to v0.16.7

---

packages/app-data/sheets/data_list/generated/w_solve_task_gs.json
packages/app-data/sheets/data_list/generated/w_solve_task_gs_temp_1.json
packages/app-data/sheets/data_list/generated/w_solve_tog_task_gs.json
packages/app-data/sheets/data_list/w_solve_specific_task_gs.json
packages/app-data/sheets/global/home_screen_variables.json
packages/app-data/sheets/global/home_screen_variables_mod.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/component_demo/feature_task_card_params.json
packages/app-data/translations/es_sp/strings.json
packages/app-data/translations_source/from_translators/translated.es_sp.json

PR Checklist
PR updates PLH and debugging content

Content sync 02/11/2022

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version number to v0.16.8

Update version to v0.16.8

---

packages/app-data/sheets/template/debug/feature_feedback_text_select.json
packages/app-data/sheets/template/home_screen_modular.json
packages/app-data/sheets/template/module_card.json
packages/app-data/sheets/template/module_details.json
packages/app-data/sheets/template/things_to_do.json
packages/app-data/sheets/template/workshop_options_page.json

PR Checklist
PR updates PLH content.

PLH content sync 11/10/2022

---

.idems_app/deployments/early_family_math/config.ts

PR Checklist
Add professional skin to EFM

feat: add professional theme to available themes for EFM

---

.github/ISSUE_TEMPLATE/crashlytics.md

PR Checklist
Add github reporting template for crashlytics reports
Closes #

chore: add crashlytics github template

---

src/app/shared/services/task/task.service.ts

PR Checklist
Fixes a bug exposed by a crashlytics report, whereby completing every task group would cause an error.
Closes #1672

Fix: handle case where all task groups are completed when setting highlighted task group

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version number to 0.16.9

Update version number to 0.16.9

---

README.md
documentation/docs/authors/quickstart.md

PR Checklist
Minor docs update
Closes #

docs: update quickstart docs

---

src/app/shared/services/asyncService.base.ts

PR Checklist
While testing on a particularly slow emulator device I noticed some of the services where timing out on init which then broke things entirely. I'm now second-guessing whether we actually want services to be allowed to fail silently, but for now I've just upped the timeout delay from 10s to 60s 
Closes #

fix: service timeout

---

.firebaserc
.idems_app/.gitignore
.idems_app/deployments/perinatal/config.ts
firebase.json

Testing the github action that deploys web preview site to Firebase hosting.

Deployment dev/perinatal: testing firebase hosting deployment

---

packages/app-data/sheets/data_list/component_demo/comp_data_items_list.json
packages/app-data/sheets/data_list/safeguarding_contacts_tz.json
packages/app-data/sheets/index.ts
packages/app-data/sheets/template/change_thoughts.json
packages/app-data/sheets/template/component_demo/comp_calendar.json
packages/app-data/sheets/template/component_demo/comp_carousel.json
packages/app-data/sheets/template/component_demo/comp_data_items.json
packages/app-data/sheets/template/component_demo/comp_task_card.json
packages/app-data/sheets/template/debug/debug_go_to_url.json
packages/app-data/sheets/template/debug/debug_teen_ages.json
packages/app-data/sheets/template/debug/example_text_image.json
packages/app-data/sheets/template/debug/feature_display_group.json
packages/app-data/sheets/template/w_instruct_question_1.json
packages/app-data/sheets/template/w_stress_question.json

PR Checklist
PR updates ParentApp content as of 18 Jan 2023.

ParentApp content sync 18 Jan 2023

---

packages/app-data/sheets/data_list/generated/module_tasks.json
packages/app-data/sheets/data_list/module.json

PR Checklist
PR reverts the order of the highlighted modules.

Update WASH App web preview

---

packages/app-data/sheets/data_list/number_data.json
packages/app-data/sheets/template/component_demo/comp_data_items.json
packages/app-data/sheets/template/demographics_teen_age.json

PR Checklist
PR updates ParentApp content as of 19 Jan 2023

Content sync 2023/01/19

---

packages/app-data/sheets/template/accept_terms.json

PR Checklist
PR updates ParentApp content as of 20 Jan 2023

Update checkbox on accept_terms to be a square

---

packages/scripts/src/utils/file-utils.ts
src/app/shared/components/template/services/instance/template-action.service.ts

PR Checklist
Fix regression issue brought in #1603 where `set_field: this.value` actions would fail as the `this.value` override was not refactored along with the `set_field` action. 
As no releases have been made since the PR was merged just going to go ahead and fix directly.
Closes #

hotfix: set field args

---

packages/app-data/sheets/template/demographics_teen_age.json
packages/app-data/sheets/template/survey_final_stepper.json
packages/app-data/sheets/template/survey_welcome_repeat_stepper.json

PR Checklist
PR updates ParentApp content as of 27 Jan 2023, including changes to the final survey.

Content sync 27 Jan 2023

---

.idems_app/deployments/wash/config.ts
documentation/docs/developers/deployments.md
packages/data-models/deployment.model.ts
packages/scripts/src/commands/deployment/compile.ts

PR Checklist
Regression issue flagged in #1775, WASH deployment config requires update to match format described in #1763
I've also update documentation to remove legacy references, and added a new validation check to ensure the config has been defined using the `generateDeploymentConfig` syntax
**Error message shown when wash config manually reverted to older syntax**

fix: update wash deployment config

---

.idems_app/deployments/wash/config.ts

hotfix: wash deployment name

---

packages/app-data/sheets/data_list/bathing.json
packages/app-data/sheets/data_list/clean_toilets.json
packages/app-data/sheets/data_list/generated/bathing_tasks.json
packages/app-data/sheets/data_list/generated/clean_toilets_tasks.json
packages/app-data/sheets/data_list/generated/handwashing_with_soap_tasks.json
packages/app-data/sheets/data_list/generated/healthy_families_tasks.json
packages/app-data/sheets/data_list/generated/healthy_homes_tasks.json
packages/app-data/sheets/data_list/generated/how_to_wash_your_hands_tasks.json
packages/app-data/sheets/data_list/generated/module_tasks.json
packages/app-data/sheets/data_list/generated/safe_drinking_water_tasks.json
packages/app-data/sheets/data_list/generated/safe_food_tasks.json
packages/app-data/sheets/data_list/generated/waste_tasks.json
packages/app-data/sheets/data_list/generated/when_to_wash_your_hands_tasks.json
packages/app-data/sheets/data_list/handwashing_with_soap.json
packages/app-data/sheets/data_list/healthy_families.json
packages/app-data/sheets/data_list/healthy_homes.json
packages/app-data/sheets/data_list/how_to_wash_your_hands.json
packages/app-data/sheets/data_list/module.json
packages/app-data/sheets/data_list/safe_drinking_water.json
packages/app-data/sheets/data_list/safe_food.json
packages/app-data/sheets/data_list/waste.json
packages/app-data/sheets/data_list/when_to_wash_your_hands.json

- Content sync to reflect latest changes to WASH App content

WASH App content sync 20/02/2023

---

packages/app-data/assets/contents.json
packages/app-data/assets/global/plh_images/icons/tick.svg
packages/app-data/sheets/data_list/generated/w_celebrate_ind_task_gs.json
packages/app-data/sheets/data_list/generated/w_celebrate_task_gs.json
packages/app-data/sheets/data_list/generated/w_celebrate_task_gs_temp_1.json
packages/app-data/sheets/data_list/generated/w_celebrate_tasks.json
packages/app-data/sheets/data_list/generated/w_celebrate_tasks_temp_1.json
packages/app-data/sheets/data_list/generated/w_self_care_ind_task_gs.json
packages/app-data/sheets/data_list/generated/w_self_care_task_gs.json
packages/app-data/sheets/data_list/generated/w_self_care_task_gs_temp_1.json
packages/app-data/sheets/data_list/generated/w_self_care_tasks.json
packages/app-data/sheets/data_list/generated/w_self_care_tasks_temp_1.json
packages/app-data/sheets/data_list/w_celebrate_specific_task_gs.json
packages/app-data/sheets/data_list/w_celebrate_specific_tasks.json
packages/app-data/sheets/data_list/w_self_care_specific_task_gs.json
packages/app-data/sheets/data_list/w_self_care_specific_tasks.json
packages/app-data/sheets/template/app_menu.json
packages/app-data/sheets/template/app_menu_settings.json

PR Checklist
PR updates ParentApp content as of 22 Feb 2023

ParentApp content sync 22 Feb 2023

---

.idems_app/deployments/default.json
packages/app-data/sheets/data_list/campaign_rows/nf_inactive_progress.json
packages/app-data/sheets/data_list/campaign_rows/nf_inactive_week_month.json
packages/app-data/sheets/data_list/campaign_schedule/nf_schedule_in_week_messages.json
packages/app-data/sheets/data_list/check_in_data.json
packages/app-data/sheets/global/localised_names.json
packages/app-data/sheets/global/localised_names_tz.json
packages/app-data/sheets/global/workshop_options.json
packages/app-data/sheets/template/app_menu.json
packages/app-data/sheets/template/debug/example_field_hist.json
packages/app-data/sheets/template/feature_feedback_debug.json

PR Checklist
PR updates ParentApp content as of 24 Feb 2023

ParentApp content 24 Feb 2023

---

packages/scripts/src/utils/file-utils.spec.ts
packages/scripts/src/utils/file-utils.ts
src/app/shared/utils/utils.ts

PR Checklist
- Add basic spec tests for scripts file util `setNestedProperty` method
- Fix issue where method would not deep merge
- Duplicate changes for frontend code
Updated to support work in #1795
Closes #

chore: add tests for file utils and minor fix

---

packages/data-models/workflows/sync.workflows.ts

PR Checklist
Fix issue where the `--content-watch` flag not working (likely following some of the recent app scripts refactoring)
```
yarn workflow sync --content-watch
```
Make updates to a sheet and see if synced changes appear locally
Closes #

fix: content-watch workflow

---

android/app/build.gradle
package.json

PR Checklist
Update version number to v0.16.12

Update version to v0.16.12

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version number to 0.16.13

Update app version to 0.16.13

---

.idems_app/deployments/wash/config.ts

PR Checklist
PR updates WASH config to allow for Swahili translations

Update wash config

---

.idems_app/.gitignore
.idems_app/deployments/module_scaffolding/.gitignore
.idems_app/deployments/module_scaffolding/config.ts

PR Checklist
PR adds module_scaffolding deployment.

Add module_scaffolding deployment

---

.github/workflows/deployment-hosting.yml
.github/workflows/sourcemaps-upload.yml
.github/workflows/test-preview.yml
.idems_app/deployments/plh/config.ts
.idems_app/deployments/plh_debug/config.ts
.idems_app/deployments/plh_global/config.ts
.idems_app/deployments/plh_tz/config.ts
.idems_app/deployments/plh_za/config.ts
src/app/app.component.ts
src/app/shared/services/error-handler/error-handler.service.ts
src/environments/sha.ts

PR Checklist
Error logging uses uploaded sourcemaps to create human-interpretable stack traces of errors, identifying where in the source code production errors originate from. These sourcemaps are automatically generated on release, and so the ability to create these error logs requires that the codebase used to upload the sourcemaps is identical to the codebase in the release.
This can result in broken sourcemaps in cases where new web releases are created independently of android app release, as we now have to versions of sourcemaps for the same app version, one which works with the android release and one with latest web release. 
This PR fixes by attaching the current git commit SHA to sourcemaps, so that all releases create a unique set of sourcemaps independent of the actual …

feat: add support for ci sha tracking in glitchtip

---

packages/app-data/sheets/contents.json
packages/app-data/sheets/data_list/survey_question.json
packages/app-data/sheets/global/app_id.json
packages/app-data/sheets/global/app_id_tz.json
packages/app-data/sheets/template/legal_terms/app_menu_privacy_policy.json
packages/app-data/sheets/template/legal_terms/app_menu_terms.json
packages/app-data/sheets/template/w_self_care_reward_pop.json

PR Checklist
PR updates ParentApp content as of 15 Mar 2023

ParentApp content sync 15 Mar 2023

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version number to 0.16.14

Update version number to 0.16.14

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version to v0.16.17

Update version to v0.16.17

---

.firebaserc
firebase.json

PR Checklist
PR updates firebase files to include PfR.

Update firebase files to include PfR

---

android/app/build.gradle
package.json

PR Checklist
Update version number to try and trigger web preview

Update PfR version number to 0.16.18

---

packages/app-data/sheets/contents.json
packages/app-data/sheets/data_list/topic.json
packages/app-data/sheets/data_list/topic_group.json
packages/app-data/sheets/template/app_menu.json
packages/app-data/sheets/template/feature_feedback_default.json
packages/app-data/sheets/template/feature_feedback_text_select.json

PR Checklist
Add feedback templates to PfR web preview

Add feedback templates to PfR web preview

---

.firebaserc
firebase.json

PR Checklist
Adds a web preview for the `plh_facilitator` deployment, available here: https://plh-facilitator.web.app
See #1944 for a brief discussion of new web previews in the period of moving deployment contents to their own repos.
After merging, the `plh_facilitator` web preview can be updated from the CLI according to the following instructions:
1. Set the active deployment to `plh_facilitator` (if not previously imported, run `yarn workflow deployment import https://github.com/IDEMSInternational/plh-facilitator-app-content`
2. Run `yarn workflow sync` to sync the latest content
3. Run `yarn build` to build the app the `www` folder
4. Run `firebase deploy --only hosting:plh_facilitator` to deploy the local build to Firebase
- You'll need to install Firebase tools and log in if you …

chore: configure web preview for plh_facilitator deployment

---

firebase.json

PR Checklist
Fixes a typo in the target for the plh_facilitator web preview (see comment on #1952), allowing the web preview to be updated using `firebase deploy --only hosting:plh_facilitator`

fix(plh_facilitator web preview): replace hypen with underscore

---

packages/app-data/sheets/data_list/hp_check_in_data.json
packages/app-data/sheets/data_list/story_data.json
packages/app-data/sheets/template/activity_memory_game.json
packages/app-data/sheets/template/relax_9_text.json
packages/app-data/sheets/template/w_consequence_tools.json

PR Checklist
PR integrates edits coming out of Natasha's second round of proofreading the ParentApp Teens content.

PLH content: second round proofreading

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version number to v0.16.18

Update app version number to v0.16.18

---

android/app/build.gradle
package.json

PR Checklist
PR updates app version to 0.16.19 ahead of PLH TZ release

Update app version to 0.16.19

---

.github/workflows/android-build-dispatch.yml
.github/workflows/android-build.yml

PR Checklist
Fix typo where branch was not being passed to build action correctly
Closes #

fix: android release action

---

android/app/build.gradle
package.json

PR Checklist
PR updates app code version to v0.16.20 ahead of PLH TZ release

Update app version to v0.16.20

---

.github/workflows/web-build.yml

PR Checklist
Fix issue where deployment from master would not pick the correct default deployment name
Closes #2052

fix: master deployment hosting

---

android/app/build.gradle
package.json

PR Checklist
PR updates version number to 0.16.21

Update version number to 0.16.21

---

.github/workflows/android-build.yml

PR Checklist
Update android build action to checkout git-lfs files in android folder
Should fix issue where compiling icon/splah assets fail
Closes #

chore: add lfs files to android build action

---

packages/api/Dockerfile
packages/api/package.json
packages/api/src/db/index.ts
packages/api/src/environment/index.ts
packages/api/src/main.ts
packages/api/tsconfig.json
packages/server/README.md
packages/server/docker/docker-compose.yml

PR Checklist
Various fixes required when deploying app to server
- Bump node 16 -> 18
- Fix issue not picking package version
- Fix issue not pinning yarn to expected version
- Update methods to install workspace npm production modules
- Code tidying
Additionally on server bumped disk from 30GB -> 50GB as was running low on space, and took snapshots of disk both before `idems-apps-20231102a` and after `idems-apps-20231102b` update 
Changes already deployed to server so should do functional testing on server and can merge here if working as expected
Closes #
**Latest version of api (1.4.3) running on server**

Server/updates 1.4.x

---

android/app/build.gradle
package.json

PR Checklist
Increases version number to 0.16.22 to prepare for upcoming release

ci: increment version number to 0.16.22

---

.github/workflows/contentflows/reusable-android-build.yml
.github/workflows/contentflows/reusable-android-release.yml
.github/workflows/contentflows/reusable-app-build.yml
.github/workflows/contentflows/reusable-content-sync.yml
.github/workflows/contentflows/reusable-deploy-pr-preview.yml
.github/workflows/contentflows/reusable-deploy-web-preview.yml

Added actions to be called from content repositories. All actions must inherit secrets from repos that run the actions.

Added actions to be called by content repositories

---

packages/workflows/src/sync.workflows.ts

PR Checklist
Fix issue where gdrive_authorize script exits before completing. Likely regression issue brought in by #2091 
Closes #

fix: gdrive authorize script

---

package.json

PR Checklist
Bumps version number
Closes #

ci: increment version to 01625

---

package.json

PR Checklist
Bump version number in anticipation of next release
Closes #

ci: increment version to 01627

---

android/app/build.gradle
packages/data-models/flowTypes.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/services/auth/auth.service.ts

PR Checklist
Updates the Android Firebase library versions, in an attempt to address the warning in #2133. 
Also refactors the auth actions to use a new `auth` namespace:
- `google_auth` action is replaced by `auth: sign_in_google`
- `google_auth` syntax is still supported for compatibility, but should be considered deprecated
- Adds a new action: `auth: sign_out`, which signs the user out through Firebase. Currently the only use case for this is debugging
See [example_google_auth](https://docs.google.com/spreadsheets/d/12xo0ewDN0bbeVrs3klWd9J8DkFQLTCYX1zhGWnovqIo/edit#gid=579616705) template below for the actions in use.
Closes #2133
The initial behaviour on clicking the "Sign in with Google" button was confusing to me (see demo below), especially as it didn't match what I observed when …

chore: update Firebase BoM; refactor: auth actions

---

package.json

PR Checklist
Bump version number in anticipation of next release
Closes #

ci: increment version to 01628

---

src/theme/themes/plh_facilitator_mx.scss

PR Checklist
Change `plh_facilitator_mx` accent colour used in round buttons from yellow to pink, in line with the [partner's colour scheme](https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/issues/53). 
This also improves the contrast on this button, now passes AA standard - contrast ratio 4.5+
Closes #
After / Before

feat: Update plh_facilitator_mx theme

---

package.json

PR Checklist
Increases version number
Closes #

ci: increment version number to 01629

---

package.json

PR Checklist
Bumps package version number to 0.16.30
Closes #

CI: increment version number to 0.16.30

---

package.json

PR Checklist
Updates code version to 0.16.31
Closes #

ci: bump code version to 01631

---

package.json

PR Checklist
Increases code version number to 0.16.32
Closes #

ci: bump version to 0.16.32

---

package.json

PR Checklist
Increases code version number to 0.16.33

ci: bump version to 0.16.33

---

src/app/shared/services/local-storage/local-storage.service.ts

PR Checklist
Minor follow-up to #2320 to catch undefined cases
Closes #

chore: add localstorage undefined handling

---

package.json

PR Checklist
Update version number after publishing release [v0.16.33](https://github.com/IDEMSInternational/open-app-builder/releases/tag/v0.16.33).
Closes #

ci: bump version to 0.16.34

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds a basic legend to the map component to display a key for each plotted layer
Closes #
Updated [comp_map_layer_data](https://docs.google.com/spreadsheets/d/1KgLTrFhqZdGhcSk6Zt0KQoy2mYf7NCqhCJz_zS0KEYw/edit?gid=1695224840#gid=1695224840)
https://github.com/user-attachments/assets/63725a5e-67f7-47cf-92ea-0de2b72c84b3

feat: add basic legend to map component

---

src/app/shared/components/template/components/audio/audio.component.html
src/app/shared/components/template/components/audio/audio.component.ts

PR Checklist
Update the method of change detection used by the audio player to more reliably set the value of the seek progress bar
Ideally should fix the issue seen in #2387 (was working locally for me). Although feel free to let me know if there are similar issues related to other components which I can look at in follow-up (I couldn't see an example video, but also think the code is handled differently so not sure if it would have the same issue). 
As for the underlying issue (why it works in some place and not in others), hard to be sure and I don't think fully worth a deep dive at this point (angular change detection can be fickle), but happy to look more closely at any other specific issues you notice
I was a bit surprised to see the package used to manage audio not have support for …

fix: audio player seek

---

package.json

PR Checklist
Bumps version number in anticipation of next release

ci: bump version to 0.16.35

---

src/app/shared/components/template/components/toggle-bar/toggle-bar.ts

PR Checklist
Very minor follow-up to #2352 to correct a comment to accurately state the default styling applied on web platforms.

chore: update comment in toggle-bar component code to reflect default styling on web

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Map component: Point type features will now render in vector layers

feat: map - handle Point geometry types in vector layers

---

.github/workflows/reusable-deploy-pr-preview.yml

Added explicit secret passed to fix the issue with passing secrets between organisations

Update reusable-deploy-pr-preview.yml action

---

package.json

PR Checklist
Bump version number following release of [v0.16.35](https://github.com/IDEMSInternational/open-app-builder/releases/tag/v0.16.35).

ci: version bump to v0.16.36

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Handles the case where the property to plot on heatmap layer data is not already normalised between 0 and 1.

fix(map): handle non-normalised values in heatmap layer property scale

---

src/theme/themes/_index.scss
src/theme/themes/plh_kids_kw.scss
src/theme/variables.scss

PR Checklist
Adds a new theme, `plh_kids_kw`, to be used for making style changes for the `plh_kids_kw` deployment. Currently, this theme is just a deuplicate of the existing `professional` theme.

feat: add plh_kids_kw theme

---

package.json

PR Checklist
Bumps version number after release https://github.com/IDEMSInternational/open-app-builder/releases/tag/v0.16.36

ci: bump version to 0.16.37

---

cspell.config.yml
src/app/shared/components/template/components/youtube/youtube.component.html
src/app/shared/components/template/components/youtube/youtube.component.ts

PR Checklist
Proposed changes for #2490. Main changes:
- Use signals instead of lifecycle methods
- Separate out value and parameter list parsing, include value validation function
- Handle videoId extract as part of general value parse to allow additional search params to be retained (e.g. video timestamp start)
Closes #

review: 2490

---

packages/data-models/appConfig.ts
packages/data-models/flowTypes.ts
packages/data-models/functions.ts
src/app/shared/components/template/components/data-items/data-items.component.ts
src/app/shared/components/template/processors/item.ts
src/app/shared/components/template/processors/itemPipe.spec.ts
src/app/shared/components/template/processors/itemPipe.ts
src/app/shared/components/template/services/instance/template-row.service.ts

PR Checklist
Small amount of tidying for `items` and `data_items` (to support ongoing refactor work)
- Improve some variable naming
- Improve some types
- Move `DYNAMIC_PREFIX` definitions
- Update template item handling to pass arrays instead of hashmap
- Move item data pipe to own file
I've checked `comp_data_items` and it looks to be working same as in `master` - example 3 not working in either but others appear to be (but good to double-check)
I've also checked `example_items` and `feature_items` and both appear to be working as intended. There's quite a lot of other debug sheets with the word items in, I haven't checked any of these as I'm not aware if any are still relevant or not.
There's a bit of a mix of changes here, if you'd like me to separate type-only from more functional …

Chore: items code tidying

---

package.json

PR Checklist
Bumps version number after publishing release [v0.16.37](https://github.com/IDEMSInternational/open-app-builder/releases/tag/v0.16.37)
Closes #

ci: bump version to 0.16.38

---

src/app/shared/components/template/services/template-metadata.service.ts
src/app/shared/components/template/services/template.service.ts

PR Checklist
Alt pr to #2511, to support screen orientation when triggered from fullscreen popup
Testing on `feature_screen_orientation` should allow for any template defined with parameter_list `orientation: landscape` to be forced into landscape mode both when navigated to ordinarily or when called as a fullscreen popup (video demo below).
Closes #2511
[untitled.webm](https://github.com/user-attachments/assets/9c56d5c0-c33f-4399-8f3c-9dc5af116fbc)

feat: full screen template screen orientation tracking

---

.idems_app/deployments/local/sheets/demo.xlsx

PR Checklist
Update demo sheet that is used when running locally to include a side_menu that has links to templates and a few other pages (like in debug repo)
I'm not sure if anyone actually uses the local deployment (I do whenever testing/debugging), but can be run via
```sh
yarn workflow deployment set local
yarn start:local
```
Closes #
**App menu shown when running local deployment demo**

chore: update local demo sheet

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Fixes issue where map component would not render correctly when navigating between templates

fix: fix map rendering on navigation

---

package.json

PR Checklist
Bumps version number in anticipation of next release, following publication of [v0.16.38](https://github.com/IDEMSInternational/open-app-builder/releases/tag/v0.16.38)
Closes #

ci: bump version number to 0.17.0

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Reinstates the custom theme-level styling on the `plh_module_list_item` component. This was broken by merging #2521.
Closes #2565

fix: plh-module-list-item styling

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds support for "LineString" geometry feature type in map vector layer geojson data.
Closes #

feat(map): support 'LineString' geometry type

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
A new property for map layer rows: `excluded_features_colour`. This takes a colour value and, if set, this colour will be applied to any geometry features that fall outside of the range set by the scale sliders. This overrides the default behaviour of hiding features that fall outside of the range.
Closes #

feat(map): new layer property, 'excluded_features_colour'

---

src/theme/themes/plh_kids_kw/_overrides.scss

Bug fix: Remove right aligned styling on text bubble

---

src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
src/app/shared/components/template/components/layout/display-group/display-group.component.html
src/app/shared/components/template/components/layout/display-group/display-group.component.scss
src/app/shared/components/template/components/layout/display-group/display-group.component.ts
src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
src/app/shared/utils/utils.ts

PR Checklist
Targets branch of #2589 
- Removes sticky display group specific styling (should be inherited within main display-group wrapper)
- Restricts background image styles to only include when image provided
Closes #

review: 2589 tidying

---

src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

PR Checklist
Fixes an issue where data lists containing app meta fields would not work with the dynamic data system.
@esmeetewinkel observed that for the `plh_kids_kw` deployment, any template containing a `data-items` component would not load, and observed the following error in the console:
I believe this is a regression issue introduced by #2597, which missed when testing because the data lists in the `debug` deployment don't tend to have metadata fields (columns starting with a "_" character, such as `_translations`).
I've updated the [comp_data_items_list](https://docs.google.com/spreadsheets/d/1khGTrDekzqDQyW1r2x0ADqknanrlkmhOz1RRzhP6-7c/edit?gid=2110733076#gid=2110733076) template so that this issue can be recreated on `master` by navigating to the …

fix: dynamic data for data list including app metadata fields

---

src/theme/themes/_index.scss
src/theme/themes/conflict_forecast.scss
src/theme/variables.scss

PR Checklist
Adds a new dedicate `conflict_forecast` theme.
Closes #

chore: add conflict_forecast theme

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
- In RTL the `nav-image-asset` should flip horizontally on the `module-list-item`. Styling fix made for the asset
- Margin added to space the list items
Closes #2623

Bug Fix: Flip Module List Item nav-asset in RTL

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
- Reduced `min-width` of accordion component.  Now responsive for small screens
Closes #2567 
https://github.com/user-attachments/assets/0161ff98-685c-4c38-b122-b9f9d11494d0

Bug Fix: Accordion component responsiveness

---

src/app/shared/components/template/components/select-text/select-text.component.html
src/app/shared/components/template/components/select-text/select-text.component.ts
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
- Support added for RTL for `select-text` component
- Styling fix made for Kuwait theme
Closes #2620 
RTL vs LTR

Bug Fix: Select-Text RTL styling in kw theme

---

src/app/shared/components/template/components/layout/popup/popup.component.html
src/app/shared/components/template/components/layout/popup/popup.component.scss
src/app/shared/components/template/components/layout/popup/popup.component.ts

PR Checklist
Targets branch of #2660 
Prefers use of inset instead of specific rtl/ltr detection and modifications
To confirm fixes the same issue as target pr
Closes #

review: pop-up-button-alt

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Styles the `<a/>` tag to contrast with the accordion background
Closes #2646

[STYLING] Kuwait Theme: Support added for accordion links

---

package.json

PR Checklist
Latest version bump
Closes #

ci: bump version number to 0.17.1

---

packages/api/package.json
yarn.lock

PR Checklist
Minor updates applied when updating the server
Not really required as the changes were applied as a hotfix on the server and confirmed API build and deploy after
Fixes incompatibility between node and typescript versions which would prevent API build
The server is currently pinned to this branch
Closes #

Server/updates 1.6.0

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds support for the [MultiPolygon](https://stevage.github.io/geojson-spec/#section-3.1.7) GeoJson geometry type
Closes #

chore: handle MultiPolygon geometry type

---

src/theme/themes/plh_facilitator_mx/_index.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss
src/theme/themes/plh_facilitator_mx/_typography.scss

@esmeetewinkel This has the Kids-kw css overrides

Created new facilitator_mx style based on kids_kw

---

src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Styling `box-*` variants according to the MX design.
`box-primary` styled according to the module design:
Closes #2712

[FEATURE] Mexico Theme: Styling box-* variants

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
src/theme/themes/plh_facilitator_mx/_index.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Adds a new variant for the round-button component: `primary_light`
Related to https://github.com/IDEMSInternational/open-app-builder/pull/2729
| Figma | [parent_list](https://docs.google.com/spreadsheets/d/14iUeYWUHIly3tyz61Wgz_tlPUVAqkI8aXFnlsrUA1ZY/edit?gid=928465497#gid=928465497) template |
|---|---|
| <img width="240" alt="Screenshot 2025-01-20 at 17 55 42" src="https://github.com/user-attachments/assets/bba46407-dda2-40ed-a388-370e9cdc09c3" /> | <img width="240" alt="Screenshot 2025-01-20 at 17 53 05" src="https://github.com/user-attachments/assets/7fc94566-3126-46cd-b182-6947a485106e" /> |

style: (MX) new variant for round-button component, primary_light

---

src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Fixes styling for the `select-text` component under the `plh_facilitator_mx` theme
Closes #108
[comp_select_text](https://docs.google.com/spreadsheets/d/1MX-sy4RLy7xPkl0vHZ0lfp-kzGWyohViWjNhyGn7Vts/edit?gid=845703892#gid=845703892)

style: plh_facilitator_mx theme select-text component styling

---

src/theme/themes/plh_facilitator_mx/_index.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Builds on #2738, should be merged after that PR.
Closes #109
[comp_title](https://docs.google.com/spreadsheets/d/1pBCI7KkNNtF9sQAs_l_hcdjjFfdjC4vEL4jvF5sNk9c/edit?gid=3937162#gid=3937162)

chore: add title banner variants support to plh_facilitator_mx theme

---

src/theme/themes/plh_facilitator_mx/_index.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Fixes text spacing for the `plh_facilitator_mx` theme by reinstating values used to determine spacing for text and title components
Closes https://github.com/ParentingForLifelongHealth/plh-facilitator-app-mx-content/issues/139
|---|---|
| <img width="240" alt="Screenshot 2025-01-24 at 17 15 03" src="https://github.com/user-attachments/assets/da36dc4e-9abb-4525-b831-1d8973ef9101" /> | <img width="240" alt="Screenshot 2025-01-24 at 17 14 35" src="https://github.com/user-attachments/assets/d5d95fdc-716f-49df-9335-b86872dcb1df" /> |

style: MX text spacing

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Changes the orientation of the legend and sliders within it to display vertically at the right hand side of the map, rather than horizontally along the bottom
Closes #
comp_map

feat(map): display legend vertically

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds the ability to set an icon asset to be displayed over point features on a mp vecotr layer.
Introduces two new map layer fields (data list columns):
- `point_icon_asset`
- If an image reference is provided, the image will be displayed as any point on the layer
- `point_icon_excluded_asset`
- If provided, this image will replace the default image for points excluded from the filter defined by the layer scale slider. If not provided, excluded points will use the same image with a lower opacity
Closes #
Example
[comp_map_layer_group_2](https://docs.google.com/spreadsheets/d/1KgLTrFhqZdGhcSk6Zt0KQoy2mYf7NCqhCJz_zS0KEYw/edit?gid=1396735088#gid=1396735088):
When a `point_icon_excluded_asset` is provided, this image will be used for excluded points:
Otherwise, the default …

Deployment dev/conflict forecast

---

src/app/shared/components/template/components/table/table.component.html
src/app/shared/components/template/components/table/table.component.scss

PR Checklist
Makes the header row of the table component sticky. In future, this should be exposed as a parameter.
Closes #
Demo:
https://github.com/user-attachments/assets/05f812ab-8ca7-485f-860a-c03d8be7fd5a

chore(conflict_forecast): make table header sticky

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Increases the timeout for applying the filtering to a newly visible layer, to increase chance that the layer has finished loading before the filtering is applied (hack).
Closes #

chore: increase filter application timeout

---

documentation/docs/developers/deployments.md

PR Checklist
Minor update to the docs section on configuring Firebase following #2634
Closes #

docs: updates to Firebase config and auth

---

src/app/shared/components/template/components/table/table.component.scss

PR Checklist
Follow-up to #2852 with a workaround for table height
Closes #

chore: table height workaround

---

package.json

PR Checklist
Bumps version number in anticipation of release of v0.17.2.
Closes #

ci: bump version number to 0.17.2

---

package.json

PR Checklist
Bump (minor) version number to 0.18.0
Closes #

ci: bump version to 0.18.0

---

src/theme/themes/plh_kids_tz/_index.scss

PR Checklist
Updates the colour of the progress bar to match the latest designs (as in https://github.com/ParentingForLifelongHealth/plh-kids-app-tz-content/issues/164)
Closes #

PLH Kids TZ: Update progress bar colour

---

src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Reduce margin around plh-task-card component (which appears on the homescreen of facilitatorapps) within the `plh_facilitator_mx` theme
Progress towards https://github.com/ParentingForLifelongHealth/plh-facilitator-app-ph-content/issues/18
Before / After:

Facilitator MX theme: Reduce plh-task-card margin

---

package.json

PR Checklist
Increase patch version number ahead of release
Closes #

ci: bump version number to 0.18.1

---

package.json
src/app/shared/components/template/components/button-apple-sign-in/button-apple-sign-in.component.scss

PR Checklist
- Fixes styling of the apple sign in button component for RTL languages
- Bumps code version number in anticipation of immediate release
Closes #
Before:
After:
LTR unchanged:

hotfix: apple sign in button RTL styling

---

packages/shared/src/utils/object-utils.ts
src/app/feature/user/pages/user-debug/user-debug.page.html
src/app/feature/user/pages/user-debug/user-debug.page.ts
src/app/shared/services/dynamic-data/actions/add_data.action.spec.ts
src/app/shared/services/dynamic-data/actions/index.ts
src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts
src/app/shared/services/userMeta/userMeta.service.ts
src/app/shared/utils/utils.ts

PR Checklist
Alt PR to #2824
Main changes
- Simplify user reset logic. Now includes reload after user import to simplify some of the more destructive operations
- Add debug page prompt to reset
- Add reset action spec tests
Should confirm same test cases passing as in original pr

Review: User Import Action (#2824)

---

src/theme/themes/_index.scss
src/theme/themes/plh_facilitator_mapa/_index.scss
src/theme/themes/plh_facilitator_mapa/_overrides.scss
src/theme/variables.scss

PR Checklist
- Support added for the Mapa design theme
Closes #2914

[FEATURE] MaPa App Theme

---

package.json

PR Checklist
Bumps version number to `0.19.0` ahead of next release
Closes #

ci: bump version to 0.19.0

---

src/theme/themes/plh_kids_tz/_index.scss
src/theme/themes/plh_kids_tz/_overrides.scss

PR Checklist
- TZ theme styling refactor for the audio component, to match KW theme style
Closes #2861 
Default:
Refactor:

[FEATURE] Audio Player Styling - TZ theme

---

src/theme/themes/plh_kids_tz/_overrides.scss

PR Checklist
Secondary button (coloured **yellow**) text colour refactored to darker shade, to increase accessibility.
Closes #2754 
Default:
Refactor:

[STYLING] TZ theme - Secondary button contrast

---

package.json

PR Checklist
Updates version number to 0.19.1 ahead of next release
Closes #

ci: update version number to 0.19.1

---

package.json

PR Checklist
Bumps version number to `0.19.2` in anticipation of next release.
Closes #

ci: bump version number to 0.19.2

---

package.json

PR Checklist
Bump version number to 0.19.3 in anticipation of next release.
Closes #

ci: bump version number to 0.19.3

---

package.json

PR Checklist
Bumps version number to 0.19.4 in anticipation of next release.
Closes #

ci: bump version number to 0.19.4

---

packages/data-models/flowTypes.ts
src/app/app.component.ts
src/app/shared/services/toast/toast.service.spec.ts
src/app/shared/services/toast/toast.service.ts

PR Checklist
Adds the toastService which allows the toast action to be used:
`click | toast | message: toast this`
[feature_action_toast](https://docs.google.com/spreadsheets/d/1WGR_pxk-7iBHKX2BDdzdmjiaVjiwe-qKIou47uZFqHo/edit?gid=99275306#gid=99275306)

Feature: Add toast action

---

src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.html
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
progress_percent added to task_progress_bar to allow authors to add percentage to be displayed
[component_task_progress_bar](https://docs.google.com/spreadsheets/d/1KenOF4C7BjVmg07zONWQgRygVWMDaXCOGLOSfC5vx7g)

Feat: Task Progress Bar parameter to override progress percentage

---

package.json

PR Checklist
Increases patch version number in anticipation of next release.
Closes #

ci: bump version number to v0.19.6

---

src/app/shared/services/auth/providers/firebase.auth.ts

PR Checklist
Alt PR to #3034
I've added a `force: restart` button to the `example_auth` template to make testing easier.
Would be good to confirm it fixes case in linked issue.
As mentioned in other threads, I think the underlying issue why the `force_restart` action would not reload auth is because the default native `authStateChange` event only fires on native app init, and not post web-restart
So to work around this, I've included two independent user checks:
A) - at end of service init
B) - when native authStateChange detected 
This should cover possible cases
**Service inits and native auth not settled.**
(A) will set `null` user, (B) will update with user loaded from native layer
**Service inits and native auth already settled**
(A) will set previous user correctly, (B) will trigger …

fix: automated login reload

---

.github/workflows/reusable-android-build.yml

chore: update gh action java version

---

package.json

PR Checklist
Bumps the patch version number to `0.21.2` ahead of anticipated release
Closes #

ci: bump patch version number to 0.21.2

---

packages/components/plh/parent-group/plh-parent-group.service.ts
src/app/feature/shared-data/providers/base.ts
src/app/feature/shared-data/providers/firebase.ts

PR Checklist
Alternative to #3106, adding static methods to avoid workaround to query subscriptions
Untested, should check against same issues in #3106
Closes #3106
Closes #3107

Feat: shared data static queries

---

package.json

PR Checklist
Bumps patch version number in anticipation of next release
Closes #

ci: bump version number to 0.22.1
