IDEMSInternational/open-app-builder

package.json
scripts/plh-spreadsheet/plh-spreadsheet.model.ts
scripts/plh-spreadsheet/process-content-spreadsheet.ts
scripts/plh-spreadsheet/toolbox-content.model.ts
scripts/plh-spreadsheet/toolbox.translator.ts
src/app/feature/calendar/calendar.page.spec.ts
src/app/feature/calendar/calendar.page.ts
src/app/feature/chat/chat.page.ts
src/app/feature/toolbox/toolbox-routing.module.ts
src/app/feature/toolbox/toolbox-topic/toolbox-topic-routing.module.ts
src/app/feature/toolbox/toolbox-topic/toolbox-topic.module.ts
src/app/feature/toolbox/toolbox-topic/toolbox-topic.page.html
src/app/feature/toolbox/toolbox-topic/toolbox-topic.page.scss
src/app/feature/toolbox/toolbox-topic/toolbox-topic.page.spec.ts
src/app/feature/toolbox/toolbox-topic/toolbox-topic.page.ts
src/app/feature/toolbox/toolbox.page.html
src/app/feature/toolbox/toolbox.page.scss
src/app/feature/toolbox/toolbox.page.ts
src/app/shared/services/chat/online/online-chat.service.ts
src/app/shared/services/local-storage/local-storage.service.spec.ts
src/app/shared/services/local-storage/local-storage.service.ts
src/app/shared/services/toolbox/one-one-one-time.ts
src/app/shared/services/toolbox/toolbox-topic-metadata.ts
src/app/shared/services/toolbox/toolbox-topics.ts
src/app/shared/services/toolbox/toolbox.model.ts
src/app/shared/services/toolbox/toolbox.service.spec.ts
src/app/shared/services/toolbox/toolbox.service.ts
src/assets/images/punched_paper_1.png
src/assets/images/punched_paper_left1.png
src/assets/sheet-content/toolbox-export.json

This includes changes to allow
- Export of toolbox content from content spreadsheet as a JSON file
- Reading of that JSON file by an Angular service
- App page with list of topics
- App page for each topic
- Unlocking of toolbox topics via Rapid Pro control message
Still needs full unit tests.

Toolbox pages + spreadsheet to JSON conversion

---

scripts/plh-spreadsheet/conversation.translator.ts
scripts/plh-spreadsheet/toolbox.translator.ts

PR Checklist
Updated paths to toolbox files in files related to translator scripts
_Closes #_
@chrismclarke @michaelclapham Could you confirm these changes are correct? I was getting errors with these lines when running `process-content-spreadsheet.ts` and this resolved the issues.

fixed toolbox paths in translator scripts

---

src/app/feature/home/home-buttons/home-buttons.component.scss
src/app/feature/home/home.page.html

PR Checklist
Make the home screen buttons have tighter padding when on a device with a short screen (like an iPhone 4).
Also removed Home header from iOS home screen.

Make home screen buttons fit on shorter screens

---

src/app/feature/chat/services/offline/chat.flow.ts

PR Checklist
Actually parse rapid pro variables in quick responses.
This should prevent seeing things like Talk to @fields.guide in the list of response options.

Prevent @fields from showing in response options

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/services/offline/rapid-pro-export.model.ts

PR Checklist
Generates Rapid Pro flow export UUID's (universally unique identifiers) in a deterministic way.
This means that when the spreadsheet to flowchart code is run on the same sheets the output will not be changed.
The UUID's now follow a format of
```
`uuid_${flowName}_${entityType}_${counter}
```
For example the first node in the flow example_main would have the id
uuid_example_main_node_0

Generate Rapid Pro flow UUIDs deterministically

---

src/app/feature/chat/services/offline/contact-field.service.ts
src/environments/environment.prod.ts
src/environments/environment.ts

PR Checklist
Angular environment variable now has array of flow names to use for pre-populating fields
Currently it only loads fields from the character_names flow

Make sure we always set inital variables (e.g for character names)

---

src/app/feature/chat/components/chat.page.html

PR Checklist
Removes code that makes messages that are 2 characters or less a larger font.
This was originally used for Emoji's in the emo check however these have been removed.

Don't make short messages large font

---

src/app/feature/chat/components/chat.page.ts
src/app/feature/chat/models/chat-msg.model.ts
src/app/feature/chat/services/offline/chat.flow.ts

PR Checklist
Show alert with text input for user to type their response when a message has no quick replies and the current or next node has a wait for response router.
_Closes #222

WIP: Show text input alert when user is supposed to type in custom response

---

src/app/app-routing.module.ts
src/app/feature/_deprecated/home/home.page.ts
src/app/feature/chat/chat-routing.module.ts
src/app/feature/module_page/module-page-routing.module.ts
src/app/feature/module_page/module-page.ts
src/app/feature/tips/tips-routing.module.ts
src/app/pages/settings/settings.page.html
src/app/pages/settings/settings.page.ts
src/app/shared/services/task/task.service.ts

PR Checklist
- Add additional redirect to `home` route to keep legacy functionality
- Make tip and conversation flows appear at `/[tip/conversation]/:flow_name` (without additional /flow) to make more consistent with module list and page routing, and make more obvious for authors
Before this is merged, we should:
- check content team are happy with the proposed changes to URL structures and happy to update existing flows
- check scripts still identify invalid routes in task actions
- create an issue to automate process for checking valid routes in conversations parser (exit links)
- update chat service to support relative routes in spreadsheets (e.g. defined as `tips/my_tips` in the sheet, and retaining the same path during conversation parser for an app build, but appending web URL for …

make routing more consistent

---

src/app/feature/chat/services/offline/chat.flow.ts
src/app/feature/chat/services/offline/offline-chat.service.ts

- Deal with flow end from router node
- Clear flows stack when starting new flow
- Fix flow continuation
PR Checklist
Fixes exceptions happenning when a flow should have eneded but didn't, causing it to try to enter a null node.
_Closes #159

Fix end of flow errors

---

src/app/feature/chat/components/chat.page.html
src/app/feature/chat/components/chat.page.ts

PR Checklist
When a message has an image in it, wait slightly longer before scrolling to bottom of messages.
This is because images take 250 - 500ms to show up and create enough height for scrolling to the bottom work correctly.
_Closes #160

Fix scrolling when chat messages have attachments

---

src/app/feature/chat/services/offline/chat.flow.ts

PR Checklist
This fixes a bug where entering a sub flow from another subflow was not working.
This is due to entering flows happening differently from Rapid pro after conversion from the Excel code.
In Rapid Pro uuid's are used to launch other flows, in the Excel code specification names are assumed to be unique and are used to launch flows.
_Closes #_

Fix entering child flow within a child

---

src/app/shared/components/plh-main-header.ts

PR Checklist
Clicking on the back button now uses the built in browser history.back() function.
This is unless the app page we are currently on is the first page the user has opened (i.e via a shared link). 
In this case the back button takes users to the home screen (module_list)
_Closes #241

Ensure back button goes to previous page (if there is a previous page)

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat.page.html

PR Checklist
<icon> In message text becomes inline image using media column image. 
This removes the media image from the normal list of attachments that appear below a message.
_Closes #_

<icon> in message text becomes inline image

---

scripts/src/plh-data-convert/parsers/conversation/conversation.parser.ts
src/app/feature/chat/components/chat.page.html
src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/components/chat.page.ts

PR Checklist
Use <story-image> in message text to allow story mode to have text above and below image.
Should be working after running `npm run sync-plh-content`
Demo by visiting /chat/example_story1
Example spreadsheet here: https://docs.google.com/spreadsheets/d/1xhM6ed9kyiy6vT-bZzLSASu1TBh-KdqRWBbiO7g1rBQ/edit#gid=2080729684
_Closes #242

<story-img> to place block image in msg bubble

---

src/app/feature/chat/components/chat.page.scss
src/app/feature/chat/components/chat.page.ts
src/app/feature/chat/services/offline/offline-chat.service.ts

- Fix white border on sides of story images
- Fix using type=exit to transition to next flow
PR Checklist
Fixes story image margin causing white edges.
Fixes using exit spreadsheet row type to transition to next flow. This was failing due to the previous flow end not having a subflow router. 
As a result instead of removing the finished flow from the flow stack, the flow that was just meant to start is removed, 
then the finished flow is removed resulting in no flows running.
The fix is when a flow is completed the flow stack removes that flow by name (instead of just the flow at the top of the stack).
_Closes #301 #302

Story image and transition bug fixes

---

src/app/feature/chat/services/offline/contact-field.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
Replace @fields.var_name in templates using the contact field service used for chatbot implementation.
Work in progress as we need to support a way of populating these values from content code.

Support @fields in templates

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/button.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/animated_section.ts
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/models/index.ts
src/app/shared/components/template/template-component.ts
src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

- Deep clone template on init
- Added showTemplates option to show borders
- Fix uncompleted action in nav_group callback
- Start of event handling system
- Added debug border for animated section
PR Checklist
event_id | action_id:arg1:arg2
Also fixes templates being modified by reference when switching between templates.
Also adds debugging borders.

Start of event handling system + various bug fixes

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
This issue was the value on the begin_nested_properties row was not being set.
The values inside were being set but not the value on the begin_nested_properties.
This was causing the content_box in workshop_activity to show undefined template not found.
In this example video_help variable on the context box was set, but the context_box variable on the workshop_activity template was not being set.

Fix value on begin_nested_properties not setting

---

src/app/feature/template-testing/template-testing.page.html
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/models/index.ts
src/app/shared/components/template/template-component.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
Adding templatename as a property of template and distinguished between when template.name and template.templatename are used to ensure correct implementation of excel authoring (when giving a name to a nested template)

bugfix so that template names are used correctly from excel authoring

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
set_local in addition to set_variable now sets a local variable. 
We should maybe remove set_variable and set_value and just keep
set_local and set_global ?
_Closes #357

set_local sets local variable

---

src/app/shared/components/template/services/template.service.spec.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/template/template.service.ts
src/data/template.ts

PR Checklist
Goes through all template sheets and any rows with set_global are saved to local storage on viewing of first template.
@global.global_var_name in text is implemented as demonstrated in /template/debug_set_global_1
Action set_global should also work but still being tested.
_Closes #360

Implement global variables

---

src/app/shared/components/template/components/slider/slider.component.ts
src/app/shared/components/template/template-container.component.ts

- Fix variable replace in parameter_list
- Fix slider undefined start value
PR Checklist
@local.var_name in a parameter_list or action_list (any array field on template row) was not being populated with it's value.
This fixes that, but still requires memoization optimization.
_Closes #366

Bug: Variables not working in parameter list

---

scripts/index.ts
scripts/package.json
scripts/src/gdrive-download/index.ts
scripts/src/plh-copy-app-data.ts
scripts/src/plh-data-convert/index.ts
scripts/src/sync-single.ts

- Download single workbook
- Check if assets folder exists before copy
PR Checklist
Allows syncing of only a single workbook (or workbooks) by file name by using command
```
npm run scripts sync-single -- workbook_name
```
**You must run npm run scripts sync-plh-content once before running this command**
_Closes #409

Script to sync single workbook (to save time and bandwidth)

---

scripts/src/plh-data-convert/parsers/default/default.parser.ts
scripts/src/plh-data-convert/parsers/template/template.parser.ts
scripts/src/plh-data-convert/parsers/utils.ts
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/components/radio-group/radio-group.component.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/app/shared/utils/utils.ts
src/data/template.ts

PR Checklist
- Convert paramater_list to key-value pairs in parser (to avoid needing to do in frontend code)
- Update frontend paramater_list type parsers (string, boolean, number) to reflect key-value pairs instead of array
- Update parser to convert rows with names containing `_list` to array (e.g. `@local.button_list`)
- Create new radio group example with local variable list to allow list in parameter list
- Refactor identified components where new parameter format breaking
- Radio button components cannot be tested properly as require parsing of recursive local variables (depends on refactor of #379)
- Would be good to test some of the other components that use parameter lists to check methods still behave as intended.
@michaelclapham - could you take a quick look at some of the …

Update system for parsing parameter lists

---

src/app/shared/components/template/services/template-nav.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
This PR improves the handling of navigation from templates via actions such as `go_to`. When go_to is triggered from `button_1` in `template_a`, with a go_to template `template_b` the following happens
1. Navigate to template_b with url parameters `nav_parent` and `nav_parent_triggered_by` to retain both the name (template_a) and row (button_1) that initiated the action
2. Listen for actions to be emitted from the child template. If emit completed or uncompleted navigate back to the previous template, with url parameters `nav_child` and `nav_child_emit` to retain both the name (template_b) and emit (e.g completed) of the second template
3. On return to template_a use the url parameters to lookup the go_to initiator and process any actions on the row that also match the emit …

Go_to actions (template nav)

---

scripts/src/plh-data-convert/index.ts

PR Checklist
Ensures all file paths in xlsxPath are / (same as HTTP / mac / linux) even when generated on Windows.
Going with / instead of \\ is largely because pasting in a / path in Windows explorer will still open the folder, however doing the reverse in a web browser or mac / linux file browser does not.

Script path fix

---

src/app/shared/components/debug-toggle.ts
src/app/shared/components/plh-main-header.ts
src/app/shared/components/template/template-container.component.html
src/app/shared/components/template/template-container.component.scss
src/app/shared/components/template/template-container.component.ts
src/app/shared/components/template/template.module.ts
src/app/shared/shared.module.ts

PR Checklist
- Refactor the debug mode toggle to standalone code to tidy template container component
- Move to menu bar to allow use throughout app, make easier to remove later and not take up space in template components
_Closes #_

refactor debug toggle to standalone menu component

---

src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/radio-group/radio-group.component.html
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- Provide access to sibling component variables through @local syntax
- Add method to update own row value via actions
- Update radio group to update own value for use in other components
- Only able to access one level of depth (e.g. @local.some_component not @local.some_component.nested_child)
- Only support for the `value` field to be returned (not parameters etc.)
- Issue identified when comparing strings explict quotation marks required (e.g. "@local.some_value"=="some_val")
Closes #488

Add support for local template row references

---

src/app/shared/components/template/services/template-nav.service.ts
src/data/global.ts
src/data/template.ts

- Fix nested template goto
- content sync for testing
- Actually go back to root template.
PR Checklist
Fixes bug where a embedding a template that contains a goto, would not go back to the correct template after clicking the go back (emit completed or uncompleted) buttons.
Example of template that reproduces this bug: template/debug_go_to_nest_top
_Closes #

Fix goto then go back in embedded template

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
Makes sure that condition column prevents a nested property from being set when the condition value returns false.
_Closes #_

Condition stops nested property assignment

---

src/app/shared/components/template/template-container.component.ts
src/data/template.ts

PR Checklist
- Add an extra arg in emit statements to emit from a different template
- Add children tracking to templates (like parent field), to be able to execute code from sibling container instances (i.e., accessing other children of current parent)
Demo: https://plh-teens-app1--pr523-feat-emit-from-whgsy42y.web.app/template/box_multi_1
Sheet: https://docs.google.com/spreadsheets/d/1NrMPEVnn_misvqrKzxvRLY3PN0-dg1yc4rhiedSiss8/edit?usp=sharing
_Closes #_

add emit-from feature for emit events

---

src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/image.ts
src/app/shared/components/template/components/layout/animated_section.ts
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/components/text-box/text-box.component.scss
src/app/shared/components/template/components/timer/timer.component.html
src/app/shared/components/template/components/timer/timer.component.scss
src/app/shared/components/template/components/tmpl-components-common.scss
src/app/shared/components/template/template-component.ts
src/app/shared/components/template/template-container.component.scss
src/global.scss
src/theme/variables.scss

PR Checklist
Update styles in tmpl-components-common.scss and tmpl-containter.scss for default center position.
Update padding in image, title, subtitle, timer, audio components.
Add default variables paddings:  --regular-padding(5px), --large-padding (5px);
Fixed ion-button height.
#482 
_Closes #_

feat: default center styles for components

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Previously go_to statements attempted to change previous urls on completion to also pass back information, but this system did not work well for cases where we had multiple nav actions.
This PR simplifies behaviour, using standard back methods on complete/uncomplete actions and not trying to update history
_Closes #_
https://user-images.githubusercontent.com/10515065/114398885-39ae7180-9b98-11eb-8c5c-0bcdd2112b5f.mp4

Add support for double go_to by removing child emits

---

src/app/feature/template-testing/template-testing.page.scss
src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/components/template/components/tmpl-components-common.scss
src/theme/variables.scss

PR Checklist
removed extra padding in progress bar and image below 
moved value of padding for main container into a global variable
_Closes #_

removed extra padding

---

scripts/src/plh-data-convert/index.ts
src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.ts
src/app/shared/components/template/components/dashed-box/dashed-box.component.html
src/app/shared/components/template/components/dashed-box/dashed-box.component.ts
src/app/shared/components/template/components/title.ts
src/data/template.ts

- Support bold or italics from excel
- Support formatting in more components
PR Checklist
Uses the formatting in the XLSX file itself (as opposed to markdown typed in) which is then converted to HTML and then shown to the user in the following components
- Text
- Title
- Dashed Box
- Button_
_Closes #_

Allow bold / italics formatting in spreadsheet (without markdown)

---

src/app/shared/components/template/components/layout/popup.ts

PR Checklist
Instead of always being all, only be as tall as popup content.
Also corrects centering of popup

Fix popup height

---

src/app/shared/components/template/template-component.ts
src/app/shared/model/flowTypes.ts
src/app/shared/services/tour/tour.service.ts
src/data/tour.ts

- Workaround for intro.js to support ng routes
- Tour can highlight template comp by name
PR Checklist
Workaround to deal with the fact that intro.js does not support single page applications.
When changing step, don't actually change step until navigation is done, then use workaround to select elements that are only just shown on page.
Also adds support for highlighting elements in a tour by their name in a template page.
_
_Closes #_

Fix intro.js to support Angular navigation

---

src/app/shared/components/template/components/tmpl-components-common.scss
src/data/template.ts
src/theme/variables.scss

PR Checklist
added new banner styles which are achieved through a defined style: 
- 'style: banner_welcome'
- 'style: banner_short'
added possibility to define background color of the banner. Example (style: banner_welcome active;)
[template link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)
_Closes #601

new banner styles

---

src/app/shared/components/template/template-container.component.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- Add a `start_tour` action type that can be used to demo a tour
- Add an example template (hardcoded into templates, not authored in excel so just temporary), as below:
```
{"flow_type": "template",
"flow_name": "example_tour_action",
"status": "released",
"rows": [{
"name":"start_tour_button",
"type":"button",
_nested_name:"start_tour_button",
"value":"Start Tour",
"action_list":[
{
"trigger": "click",
"action_id": "start_tour",
"args": [
"intro_tour"
],
},
]
}]}
```
_Closes #_
https://user-images.githubusercontent.com/10515065/118107175-5b3c8c00-b3d6-11eb-8699-0a8fbc167fa7.mp4

add start_tour action

---

src/app/shared/components/template/mocks/template-merge.mock.ts
src/app/shared/components/template/utils/template-utils.ts

PR Checklist
Fix templating script issue where deep nested merge was not removing dynamic references after merge (and so the value would revert to dynamic value), as seen in `debug_data_bottom` issue
_Closes #_

fix deep merge dynamic refs

---

src/app/shared/components/template/components/points-item/points-item.component.html
src/app/shared/components/template/components/points-item/points-item.component.ts
src/data/template.ts

PR Checklist
- added possibility to use lottie animation for parent points.
- in order to use animation just provide its link into lottie_src parameter 
- e.g. (lottie_src: lottie_animations/parent_points.json;) 
- see attached video
[Spreadsheet link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1364651462)
_Closes #737
https://user-images.githubusercontent.com/81557818/118262783-fa04dd80-b4e7-11eb-9d52-901b7726dc1e.mov

lottie animation for parent points

---

src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.ts
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/layout/form.ts
src/app/shared/model/flowTypes.ts
src/data/template.ts

PR Checklist
- added possibility to use the form component and advanced_dashed_box through the display group by adding a type to it. 
-  types (form | dashed_box)
[feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit#gid=1231713195)
_Closes #_

display group types

---

src/app/shared/components/template/services/template-row.service.ts
src/app/shared/components/template/utils/template-utils.ts

PR Checklist
Fix issue seen in `debug_hp_review_specific` where child content was not receiving parent content text correctly (was re-evaluating it without correct local variables)
- Prevent dynamic references being passed via nested variables
_Closes #_
https://user-images.githubusercontent.com/10515065/121740326-c8b10a80-cab1-11eb-8599-4eb67c78a9f2.mp4

fix dynamic nested inheritance

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Minor fix so that the automatic template reprocessing that happens after nav actions (e.g. popup close, back press) is only triggered from the top-most template (by default the action searches for the top-most template anyways and re-renders all templates, so this prevents duplicate rerendering)
This can be seen in the logs when navigating back to the weekly workshops page
_Closes #_

Remove duplicate nav re-renders

---

src/app/shared/components/template/components/slider/slider.component.ts

PR Checklist
As ngmodel was removed in #829 method requires update to restore previous value if `do not know` box checked and then unchecked. Also adds some minor data validation for parsing numbers
_Closes #_

fix slider previous value tracking

---

src/app/shared/components/template/components/tile-component/tile-component.component.ts

PR Checklist
Change the value for a left_icon_src parameter in the tile_component to "" from null. This is required as if it is null then the `*ngIf="left_icon_src"` in the file \parenting-app-ui\src\app\shared\components\template\components\tile-component\tile-component.component.html evaluates as true if the parameter is null. The consequence of having null is that for tiles that don't have the parameter left_icon_src the icon is not found as the location is "null" and it displays a default value if it exists in the authoring or a broken image if there is no default value. One example is the quickstart round icons in the home screen as shown below.
Screenshot of quickstart buttons going back to default values if null:
Screenshot of quickstart buttons going back to default values if "":

change null to "" if the parameter for left_icon_src is left empty

---

src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/model/flowTypes.ts
src/app/shared/utils/variables.utils.ts

PR Checklist
Add method to parser to check for dynamic expressions ending in full stops, and treat as a string full-stop instead of trying to access nested property
- As the fix is to interpret the dynamic expressions slightly differently, any content authored as a workaround should ideally be updated (change spaces before full-stops). Although could add short term _hack_ to automatically replace ```(space).``` in sentences if useful. Otherwise should be good to merge
_Closes #_

Support full-stops at end of dynamic variables

---

scripts/src/plh-data-convert/parsers/template/template.parser.ts
src/app/shared/components/common/components/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/audio/audio.component.ts
src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/debugger.ts
src/app/shared/components/template/components/points-item/points-item.component.ts
src/app/shared/components/template/components/slider/slider.component.ts
src/app/shared/components/template/components/timer/timer.component.ts
src/app/shared/components/template/components/video.ts
src/app/shared/components/template/models/index.ts
src/app/shared/components/template/services/template-action.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
As action lists are parsed and kept static, the values they refer to are always one step behind changes (if referring to self value in a row). Add workaround so that in cases where a row (e.g. `slider`) has an action (e.g. `set_field: some_field: @slider.value`), the self-reference is identified and populated when triggering the action (after the local reference updated)
- Create example sheet for testing (e.g. workshop_setup qs)
- Check for any issues
- (optional) remove additional authoring added to duplicate set fields in nav buttons
_Closes #_

WiP - Action list value updates

---

src/app/app.component.html
src/app/app.module.ts
src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Builds from #922 (merged to avoid type issues)
- Replace sidemenu with `app_menu` template
- Update `go_to` action to support direct navigation when previxed with a `/` (e.g. `/campaigns`)
Closes #920
https://user-images.githubusercontent.com/10515065/127236547-c2b71cf9-d1ce-4fe7-8045-4d5bb22b749b.mp4

add sidemenu template

---

packages/plh-data/model/flowTypes.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/group.ts
src/app/shared/components/template/services/template-row.service.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/components/template/utils/template-utils.ts

PR Checklist
- Add support for a `begin_items`  and `end_items` template block that can be used to iterate over items and provide dynamic methods to work with them
Closes #
[example_items sheet](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1082016302)
Corresponding data_list
Example output

Add support for item loops within templates

---

src/app/shared/components/template/services/template-calc.service.ts

PR Checklist
- Add `@calc(now())` function to generate current Date (wrapper around JS `new Date()`)
- Add `@calc(timestamp())` function to generate db-friendly string representation of date or time object (default current date)
- Examples added to [example_calc](https://docs.google.com/spreadsheets/d/15TccctjzepSPPv9xrLp46fhYldNN0wrho1zA5voTYcg/edit#gid=1595229908)
Closes #

add suport for calc now and timestamp statements

---

src/app/shared/components/template/components/layout/display_group.ts

PR Checklist
This PR covers the issue related to the height of images. This is the continuation of the [issue 
](https://github.com/IDEMSInternational/parenting-app-ui/pull/873). Now it is catered and the height of all the images will be the same.
closes #876

Update display_group.ts making same height of  images.

---

src/app/shared/services/tour/tour.service.ts

PR Checklist
The tour service currently implements its own methods for parsing rows (including manual replacement of global fields etc.), and so a manual method needs to be added to process translations
Would be better to fully integrate with exiting row processing service
Closes #987
https://user-images.githubusercontent.com/10515065/131152748-329b34c2-2f7a-48ce-924c-c7b276ec59c1.mp4

add translations to tour service

---

packages/plh-data/translations/from_translators/translated.za.tsa.json

PR Checklist
In the Setswana translation, some of the strings that should not have been sent in the first place were translated, causing problems with the ParentPoint count.

Fix ParentPoint count in Setswana translation

---

packages/data-models/flowTypes.ts

PR Checklist
Merge required updates to type definitions to support templates in tour messages (#1008) so that example templates can be marked as released without breaking build
Closes #

add type definitions for tour message_template

---

packages/plh-data/translations/from_translators/translated.es.spa.json
src/app/shared/components/template/services/template-translate.service.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
As discussed on the call, an issue exists where fields initialised with default values (e.g. `user_name_default: awesome parent`) are not updated when language changed because fields are only ever initialised once.
This PR provides a solution to the issue, by allowing `field_default` rows to point to `global_default` rows (actually no change required as global rows were always processed directly as strings and not evaluated), and adding `global_default` rows to the translation process with update on language change. 
In the user_name case, the field `@fields.user_name_default` is initialised with the value `@global.user_name_default`, so it will always show the updated global value unless the user has replaced with their own name. Even if the name the user replaced with …

add support for global default translations

---

packages/data-models/constants.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/utils/variables.utils.ts

PR Checklist
Assume none. In theory, any strings that use backticks already with dynamic fields e.g. `` `@fields.some_value` ``   would have previously been parsed and rendered between backticks, but no other backticks found in search on plh data so assume non-issue. 
Regular text can still use backticks if required.
- Add syntax so that dynamic fields wrapped in backticks,e.g. `` `@fields.some_value` `` are not parsed
- Add examples to [example_set_fields_in_action](https://docs.google.com/spreadsheets/d/1YRCwIrsPkTw8S6NRZPyRax0jE8jzHXKy7EoftTK-YXE/edit#gid=41221518)
- Minor improvements to parser regex comments
Closes #1018
[example_set_fields_in_action](https://docs.google.com/spreadsheets/d/1YRCwIrsPkTw8S6NRZPyRax0jE8jzHXKy7EoftTK-YXE/edit#gid=41221518)

add support for raw values

---

src/app/shared/components/template/services/template-variables.service.ts

PR Checklist
Reviewing the issue, I can't actually figure out a) why the translations worked initially (I though only support had been added for data lists, but the template uses campaigns) and b) why it stopped working. I think there might be something a bit deeper to do with the excel sheets (did maybe the global use to refer to one data list and then that changed?). But in any case a good reason to add a better/more general fix for translating dynamic content
- Add improved method to handle translation of dynamic objects (e.g. data lists and campaigns)
I've tested with the [debug_translation](https://docs.google.com/spreadsheets/d/1Bwh8eb2B43AAlDND4q0b4E-EXgnd6IRjmIFIf1Jbk1c/edit#gid=2032321486) sheet and also as a quick run through the first few app screens and all seems to be working …

fix dynamic list translation methods

---

.github/workflows/android-release.yml

PR Checklist
A recent API change broke the github action that submits apks to google play as part of the automated release process. This PR pins the version of the github action used to the previous working version
Issue on action: `https://github.com/r0adkll/upload-google-play/issues/80`
Closes #

pin gh-action upload-google-play version

---

src/app/shared/components/template/components/points-item/points-item.component.html
src/app/shared/components/template/components/points-item/points-item.component.scss
src/app/shared/components/template/components/points-item/points-item.component.ts

PR Checklist
After various other discussions and PRs (see slack thread), the cause of the screen flicker issue seems to be linked to the implementation of the parent point tiles (namely the celebration animation)
Previously every parent point renders a celebration animation component, and toggles a start play function when called. For whatever reason this proved problematic in recent versions of chrome (possibly because of too many animations on the page, how lottie implements non-started animations, the fact the animation is duplicated for each tile or any other combination of factors etc.)
This pr changes the celebration implementation to conditionally render the animation, only when it is triggered (to remove the duplicate animations from the dom). It appears to fix the screen flicker …

fix parent point flicker

---

src/app/shared/services/server/server.service.ts

PR Checklist
Previously the contact field that records last sync was outdated on the server because it only tracked the last saved value (which only is saved after a successful sync).
This PR changes the behaviour so that the time sync initiated is recorded, and if successful written locally so that server and local fields will match
Closes #
After clean start, initial sync now has a populated contact field for `_server_sync_latest`.

fix server sync timestamp

---

packages/app-data/data/template/template.component_demo.ts
packages/translations/examples/compiled/jsons/data_list.json
packages/translations/examples/source/data_list.json
src/app/feature/chat/components/chat.page.html
src/app/feature/chat/utils/message.converter.ts
src/app/shared/components/template/services/template-asset.service.ts

PR Checklist
- Update some legacy example data that still used `assets/plh_assets` prefixes, 
- Add fix to handle assets that start with `/` (e.g. `/plh_images/icons/heart.svg` instead of `plh_images/icons/heart.svg`)
Closes #

Fix legacy asset paths

---

.github/workflows/test-visual-compare.yml
.github/workflows/test-visual-generate.yml
packages/app-data/test/index.ts
packages/app-data/tsconfig.json
packages/test-visual/src/commands/compare.ts
packages/test-visual/src/commands/generate.ts
packages/test-visual/src/data/profiles.ts

PR Checklist
A small set of configuration changes and refactoring to give more control to authors for how tests will be run. Specifically:
- Add support for additional template names to include/exclude alongside template flow_types
- Refactor default page height, width and page-wait to app-data variables
- Add support for custom template page-wait and height overrides
Most of the changes should hopefully be obvious by the new fields available in `packages\app-data\test\index.ts` (see screenshot below)
As the test configuration changes defined here won't have yet been run on master branch, expect the compare script to still generate a number of differences (particularly where the 'before' image is not rendered) - should be more consistent moving forwards
The process of configuring page …

Visual test dynamic config

---

packages/scripts/src/app-data-copy.ts
packages/scripts/src/utils/file-utils.ts

PR Checklist
Closes #
Scripts now automatically assign a hardcoded type definition for translation strings, to prevent the compiler having to infer
Add the index-file level this results in a much simpler inference (it still infers the available language codes, but the individual file types are inherited)

Fix type inference issues for translation_strings

---

angular.json
package.json
src/app/shared/components/template/services/template-asset.service.ts
src/assets/_app_assets/README.md

PR Checklist
Fix issue where app assets are not shown on device. Culprit appears to be android/capacitor unhappy with asset paths starting with underscore prefixes.
Linked issue, was supposedly fixed in Capacitor v3 (which we are running) but perhaps was not: `https://github.com/ionic-team/capacitor/commit/c23d99315acea2f0894e5ff8a08dd42a867b2982`
Closes #

update app data assets path

---

documentation/docs/authors/template-component-parameter-list.md
documentation/mkdocs.yml

PR Checklist
As markdown docs are interpreted with a python interpreter (mkdocs), some of the formatting used in existing template component docs does not show correctly (tabs). Updated the docs to remove tabs, and also changed all the heading levels by one `#` so that the sidebar can display correctly
Additionally adds one minor fix for edit urls.
Note - cannot be tested easily locally, but should update once merged
Fixes issue identified in #1123
Closes #
**Before**
**After**

Tidy template components docs

---

src/app/shared/services/notification/local-notification.service.ts

PR Checklist
- Fix bug where notifications would not request permission on android due to irrelevant browser check failure
- Fix bug where app would not load on web if user fails to interact with notification enable prompt
Closes #
**Notifications now show as scheduled from the Notifications page**

fix notification permissions

---

src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/layout/display_group.ts
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/template-component.scss
src/theme/deployment/_components.scss
src/theme/deployment/_templates.scss
src/theme/deployment/components/_display-group.scss

Following core styles refactor PR (#1131 ), various minor issues to resolve:
This is now fixed from the dev side. The solution is a bit hardcoded, and depends on the parent container ending `nav_buttons` (e.g. intro_nav_buttons, outro_nav_buttons, etc.). There is also a small amount of padding between start and end, currently required because of not really knowing which of the 4 buttons will be shown and wanting to guarantee there's always spacing (could be fixed later with some additional authoring to change hidden conditions to disabled and updating hardcoded styles)
Update styles to make all dashed boxes full width
Linked to the tricky code referenced above. Now there should always be a gap (there might be instances with a gap twice the size, but assume this won't be much of an issue) …

Core style refactor fixes

---

src/app/shared/components/template/template-component.ts
src/theme/deployment/templates/_home_screen.scss

PR Checklist
Home screen animations have breakpoints to prevent animation getting too large at certain sizes, however they had been refactored to depend on the name of their parent component which gets changed during production build. Minor fix to make the styles depend on the row type instead (as all row types are mapped to the display component, but are not optimised in the same way)
Closes #

remove data-display-component styles

---

src/app/shared/components/template/components/layout/display_group.scss
src/app/shared/components/template/components/layout/display_group.ts

PR Checklist
Updates styles so that rows in display groups are spaced the same way that regular rows are (default 16px margin between columns or rows). 
Style updates have been specifically scoped to children of display groups to avoid wider breaking changes, but still possible to have some knock-ons where display groups used and either margins manually specified or not included (should be picked up by visual test).
The demo template used hasn't been synced to master yet so only available if testing locally. 
Closes #1147

Update display group padding to mimic template

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Add a tracking ID to popups to prevent hiding of popups triggered from within popups following navigation.
@EsmeeIDEMS - The nav/popup code is pretty messy and so while I _think_ that the changes should fix this use case and not break any others, it would be good to functional test anywhere else you can think of that we use popup/nav combos
Closes #1151
https://user-images.githubusercontent.com/10515065/148140015-3b2cb68d-9b8e-4bc0-8750-ba0377a59f04.mp4

fix nested nav popups

---

src/app/app.component.ts
src/app/shared/components/template/components/layout/layout.ts
src/app/shared/components/template/services/instance/README.md
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/components/template/services/instance/template-instance.service.ts
src/app/shared/components/template/services/instance/template-process.service.ts
src/app/shared/components/template/services/instance/template-row.service.ts
src/app/shared/components/template/services/template-nav.service.ts
src/app/shared/components/template/services/template-process.service.ts
src/app/shared/components/template/services/template-variables.service.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
Refactor template services to provide slightly cleaner and more scalable sharing of code both within the templating system and external modules
The templating system is broken down into various components and services tasked with different aspects of the system, such as processing templates, rendering rows or triggering actions. One of the downsides of this modularity is that sharing code between services can be tricky given the nature of cyclic dependencies (e.g. the template-processor service can't import from template-actions if template-actions also has a call to the template-processor, e.g. trigger re-process)
Another layer of complexity is added when we take into account that some services exist globally (single instance), whilst others are created at a per-template …

Improve template service dependency handling

---

src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.ts

PR Checklist
The code used to display workshop tiles contains a lot of hardcoded styles which are unmaintainable and leading to some confusing behaviours. 
This PR removes all styles related to changing screen size breakpoints (which are yet to be consistently defined across the app) and auto text size scaling based on screen width (which is just a bad idea). It also removes some of the fixed heights which will cut off content when not fitting perfectly, although means that not all the tiles will stay the same height if text is longer in one than the other (previously heights stayed fixed but text scaled to fit outside the box, which is also not good)
On first glance it appears to make content display better across screen sizes, although I'm basing this just on the `debug_dg_tile` and …

fix tile image heights

---

packages/@idemsInternational/gdrive-tools/src/commands/download.ts

PR Checklist
hotfix to prevent google drive keeping ignored assets in contents (avoid trying to copy missing file in later processing step)
Closes #

fix gdrive download filter

---

.github/workflows/test-appetize.yml

PR Checklist
Adds a github action to generate an android build and deploy to appetize.io for testing on a web-based android emulator.
Adding the label `Test - appetize` will trigger the process. This usually takes around 5-10 minutes and a preview URL will be recorded in the pr comments section.
The workflow is currently configured so that ONLY 1 build will be available at a time. That means if the label is added to multiple PRs only the one most recently updated will be the live build (the same URL will be shared for both). 
For testing, appetize.io provide a free tier that allows 100 minutes per month. I've used my own personal account/key for now, but in the future we should create a new account for the project and change the key.
The app does not appear to work on the emulator android …

feat: add appetize gh action

---

src/theme/deployment/components/_display-group.scss

PR Checklist
Reduce default margins in banner_short to _small_ (previously was top _regular_ and bottom _largest_). Any further reduction will require authoring fix as described in issue comment
Closes #1175

styles: reduce banner_short margin

---

src/app/app.component.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/components/template/services/instance/template-instance.service.ts
src/app/shared/components/template/services/template-translate.service.ts

PR Checklist
Following previous core template service refactor the translate service was no longer included with the action service, breaking the language select sheet. Fixes the issue and attempts to add an additional warning to help catch some similar issues in the future.
Minor fix working locally for me. I'm also tempted to suggest this might be the time to create another issue to add some more basic end-to-end tests that automate a few core functions and cover a reasonable amount of our manual testing strategy to make sure they always work. E.g. start app, select language, navigate to specific template, open popup, click button etc.
We already have a large part of the core in place needed for this so would hope it would only be a day or so's work to add some specific testing and …

fix(1199): injected translate service

---

.yarnrc.yml

PR Checklist
Add filter to ignore some specific log warnings that appear each time `yarn install` is run. These are pretty verbose and usually not significant nor actionable
"YN0076" INCOMPATIBLE_ARCHITECTURE
This occurs when the package contains scripts for multiple operating systems, and just to say that if running on windows, for example, linux scripts have been skipped
"YN0060" INCOMPATIBLE_PEER_DEPENDENCY
If dependencies a and b both require a third dependency c, only one version of dependency c will by default be installed corresponding to a version number that is marked as compatible with both. If one of the packages is outdated and the version numbers are not compatible (as is often the case), the system will opt to use the more recent version (which usually will have backwards …

chore: reduce yarn log warnings

---

packages/data-models/functions.ts

PR Checklist
Remove warnings presented when converting if the converter thinks there is a mismatch in the dynamic fields. This warning no longer works as it doesn't take into account nested dynamic fields (e.g. `@fields.@fields.some_value`), and wouldn't be actionable by authors even if it was. The warning is more to serve development purposes, and given the parser has been working as expected for many months now the warning no longer makes sense.
Closes #

chore: reduce converter warnings

---

src/app/shared/components/template/services/instance/template-action.service.ts

PR Checklist
We have 2 (confusingly named) actions `force_reload` and `force_reprocess` that both trigger re-evaluation of templates (with reload re-evaluating fully and reprocess just checking for variable changes). Neither, however re-evaluate content that is sat outside the current template page, such as the app menu.
As an interim solution I've added a `force_restart` action that does a more heavy-handed full page reload and redirect to the home page (like when running app reset).
I've also updated the authoring to perform a restart when changing between dev and user mode from the settings screen.
There's no easy way to review the changes, because when running locally the app is forced into dev mode regardless. So we will need to sync the latest content with the authoring changes and …

feat: add force_restart emit action

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
When popups are launched the template that created them are in charge of knowing when to close/reopen. When a popup is opened from a notification action there is no default template, so the popup stays open regardless of what is happening with any newly created templates that sit under it.
This PR adds a small workaround so that any popups triggered outside the templating system automatically close on page navigation.
This means that following navigation, if the user presses the back button whatever page they are on will no longer have the popup open (unlike normal popups, which automatically re-open on page back)
Closes #1214
https://user-images.githubusercontent.com/10515065/152617224-848ad36d-732d-45c4-8239-065ccaa7a146.mp4

fix: add standalone popup dismiss on nav

---

src/theme/deployment/_templates.scss

PR Checklist
Set the hard-coded grid gap on the parent centre from 32px to 20px.

Decrease grid gap in parent_centre

---

src/app/shared/components/template/services/instance/template-action.service.ts

PR Checklist
There are two different mechanisms in the app for syncing user data. A hardcoded/standalone system used to sync app user data (created to sync device info and contact fields), and a more generic system for syncing the database more generally (used for app_feedback).
This PR adds the second db sync to the action that manages the other user data sync (`emit:server_sync`). 
Will require adding feedback and checking if sync successful from setting sync button. If working could also consider additing the `emit: server_sync` action to be triggered after submitting feedback for instant upload.
At some point in the future it would make sense to combine, but considered lower priority for now
Closes #
https://user-images.githubusercontent.com/10515065/153935321-f163b976-d456-43ee-9de8-4 …

fix: add db sync to server_sync action

---

packages/data-models/constants.ts
src/app/shared/components/template/services/template-translate.service.ts

PR Checklist
Refactor app to allow default language to be specified from constants
The default language can now be changed from the `packages\data-models\constants.ts` file. This will only affect users that have not already specified a language. The default value has currently just been set as `en` which does not exist as a translation, and so defaults to the source strings (which are in generic English)
Closes #
Example loading app for first time with `tz_sw` specified as the default language
```
export const APP_LANGUAGES = {
/** Language used during first load. If translations do not exist will default to source strings (en) */
default: "tz_sw",
};
```
https://user-images.githubusercontent.com/10515065/155628336-21b3b73f-8727-4b5f-adae-7439cba63af4.mp4

refactor: add app default language to constants

---

src/app/app.component.ts

PR Checklist
Fix minor bug where the deployment name field was only being set after initial startup slides, and so unable to be used in overrides
Closes #1267
https://user-images.githubusercontent.com/10515065/159816893-b2870b01-8d39-4511-a297-284ed32eeca8.mp4

fix: ensure deployment name field populated

---

src/app/app.component.ts
src/app/shared/services/userMeta/userMeta.service.ts

PR Checklist
Remove legacy method that assigned temp user ids to `app_feedback` and `app_notification_interaction` tables when synced to the database. 
This should mean moving forward everything synced to the database should have consistent user ids, however as it will replace the temp ids with correct ones it will mean that any app feedback or app notification interaction data received up won't match up. I've added an extra field to track users who have had their temp id changed, although this is not synced to the server (assume not required as very little app_feedback or app_notification_interaction data has been sent, and this table is mostly legacy at this stage and will likely be removed in the future)
I've included a short video showing changes in the database that the …

fix: use device ids and not temp

---

package.json
src/app/feature/campaign/campaign.service.ts
src/app/shared/services/notification/local-notification.service.ts

PR Checklist
Add extra code to try and force notifications to use expandable format
There's a few minor refactoring points that have small potential for knock-ons, so would be good to have a quick functional test of a few different notifications (e.g. including dynamic/translated content). Testing for content can be done in the web preview, testing for expandable text in the appetize preview (as desktop notifications work a bit differently to android)
Closes #1297
https://user-images.githubusercontent.com/10515065/160260109-7ff90e62-2a11-49c8-b1a3-5e67baf7bc81.mp4

fix: force use of largeBody notification text style

---

src/app/feature/campaign/campaign.service.ts
src/app/feature/campaign/pages/campaign-debug/components/campaign-debug-row.ts

PR Checklist
Strips any markdown `**` from notifications as this does not show correctly
Small workaround to #1219
As we need to manually specify what markdown to strip I've just focused on bold text (the only example I could see). Are there any others we need to remove for now? I'm aware of not being too heavy-handed in case another author wants to use markdown characters as text (e.g. hashtags and underscores)
Closes #1314
Scheduling bold-markdown text shows the text that gets modified before sending
https://user-images.githubusercontent.com/10515065/165499396-6eaea873-e3c1-4155-832e-e7cc0354f466.mp4
Here is the message that arrived on my local device (ignore the bold heading, that isn't due to markdown just because the notification title and text are the same)

fix: strip bold markdown from notifications

---

documentation/docs/questions/images/display_group.png
documentation/docs/questions/parameters_styles.md
documentation/docs/questions/positioning_components.md
documentation/mkdocs.yml

PR Checklist
PR adds Q & A section to the documentation website and adds two questions to this section.
@jfmcquade @chrismclarke I don't think there is _need_ for you to review this, but if you have any suggestions for improvements before I move forward and add more questions let me know.

Add documentation of two questions

---

packages/app-data/sheets/template/example_hardcoded/example_hardcoded_fields.json
packages/data-models/constants.ts
src/app/app.component.ts

PR Checklist
Adds `_app_version` to `APP_FIELDS` to be dynamically referenced in templates using `@fields._app_version`

feat: allow templates to dynamically reference app version number

---

packages/app-data/sheets/template/splash_screens.json
src/app/shared/components/template/components/animated-slides/animated-slides.component.scss
src/theme/deployment/components/_display-group.scss

PR Checklist
Fixes but where splash screen slideshow didn't display properly on small screens, with some content being cut off (see issue #1384).
Also makes `display-group` with the style `two_columns_images` change its padding responsively, making the grid spacing smaller for screens less than 375px in width. Also renames 
Closes #1384 
The splash screens resizing responsively, displaying adequately on screens as small as 320px (the smallest size we support)
https://user-images.githubusercontent.com/64838927/174628349-d1d36cb3-7512-427a-abf8-615fa7d7fdd7.mov

bug: fixed splash screen styling on small screens

---

packages/app-data/sheets/template/component_demo/comp_select_text.json
packages/app-data/sheets/template/user_code.json
src/app/shared/components/template/components/select-text/select-text.component.html
src/app/shared/components/template/components/select-text/select-text.component.scss

PR Checklist
Addresses [this](https://github.com/IDEMSInternational/parenting-app-ui/issues/1006#issuecomment-1187596203) comment on reopened issue #1006, regarding the copy-to-clipboard component, namely:
1. The component now displays the `value` instead of the `name`
2. The text within the component now wraps properly (see images below)
3. The component is now styled in keeping with the rest of the app 
Currently this component reuses some of the styling from the `dashed_box` `display_group`, but the components are unrelated. In the future, the styling of both components could be coupled together.
Closes #1006 
The select text component, available at `template/comp_select_text`. Showing proper text wrapping
The `user_code` page making use of the component:

feat: fix and improve component for copying text to clipboard, and apply to user code screen

---

packages/app-data/sheets/template/splash_funders.json
src/theme/deployment/components/_display-group.scss

PR Checklist
The final funder in the list is represented by text rather than a log. This text needed to be styled to fit with the other funders' logos, but there was no way to do this from the template level.
This PR styles the text correctly by making use of the `display_group` with style `two_columns_images_overflow`.
Because the `text` component has the class `large` applied by default, it doesn't seem possible to resize text from the template level, either by using a parameter, e.g. `style: small`, or an explicit style in `style_list`, e.g. `font-size: 50%`. Therefore I used the `subtitle` component, for which the text size can be affected by `style: small`. This seems like a workaround and something that can be addressed with the theming system – I'm not sure why the `large` class is …

bug: fixed text sizing issue on overflow funder on splash_funders template

---

packages/app-data/sheets/template/debug/debug_lang_global_1.json
packages/app-data/translations/es_sp/strings.json
packages/app-data/translations_source/from_translators/translated.es_sp.json

PR Checklist
Update debug radio globals to show bug more clearly and include authoring workaround
Just as a quick update, I've looked more into the issue and at the core is the fact that the parameter list passed to the radio-group component is stored as strings retaining | characters, i.e.
0: "name:happy | text: Text and @global.language_global_1"
1: "name:ok | text:ok"
2: "name:sad | text:sad"
So everything that can be translated in a generic way is done so before, but the final form that arrives is more like "name:happy | text: Text and @global.language_global_1" , so the translation doesn't match as intended.
The obvious fix is to move all separation of parameters to a higher level where they can be processed in a more general way, e.g. converted to json {"name": "happy", "text": …

Update debug radio globals

---

packages/app-data/sheets/index.ts
packages/app-data/sheets/template/component_demo/comp_colour_palette.json
packages/data-models/flowTypes.ts
src/app/app.component.html
src/app/feature/theme/theme-service/theme.service.ts
src/app/shared/components/template/components/colour-palette/colour-palette.component.html
src/app/shared/components/template/components/colour-palette/colour-palette.component.scss
src/app/shared/components/template/components/colour-palette/colour-palette.component.spec.ts
src/app/shared/components/template/components/colour-palette/colour-palette.component.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/select-text/select-text.component.scss
src/theme/_layout.scss
src/theme/themes/default.scss
src/theme/themes/utils/generate-theme.scss
src/theme/variables.scss

PR Checklist
Continues work to generate and apply theme variables – introduces incremented colour variant system using 50-900 weights, and deprecates previous `-light` and `-lighter` colour variants. 
Deprecates `$light`, `$dark` and `$quaternary` – `$tertiary` is extant for now but will be deprecated.
Also adds support for overriding background colour at the theme definition level.
There should be no visual changes to the app, other than some very minor colour changes, almost undetectable. This is confirmed by the visual tests, which I have manually checked and look good, accounting for the usual false positives.
Closes #

refactor: Theming – introduce 50-900 colour variants

---

packages/@idemsInternational/gdrive-tools/src/commands/download.ts
packages/@idemsInternational/gdrive-tools/src/commands/watch.ts

PR Checklist
Add filter to limit gdrive watch files to only those currently used by the app and last modified by user
- Run sync watch `yarn workflow sync --content-watch`
- Make changes to files in drive both inside and outside app sheet folder
- Only changes recorded should be for the files inside the app sheet folder
Closes #

fix: gdrive watch files and modified user

---

src/app/shared/components/template/components/layout/nav_group.ts
src/app/shared/utils/utils.ts

PR Checklist
Provides a workaround for Issue #1467, in the case of a `nav_group` component using template names from a data list.
A `nav_group` can now be passed a whole data list as its `value` using `@data`, and if that data list contains a `template` column then the values of that column are used to populate the template array of the `nav_list`.
From [example_items_nav](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1360411654)
NB: example shows 4 "stepper" steps because the source data list contains a row for the CONCATENATE workaround tested in #1467, but this row could be removed

feat: nav_group can receive a data_list as value and extract template names

---

src/app/app.component.ts

PR Checklist
Fixes a bug where notifications were not properly scheduled on initial app launch, see Issue #1496. 
This was due to the fact that the "local notifications" service is required by the "campaign" service to schedule notifications, but the latter was being initialised before the former. Switching the order of these initialisations doesn't seem to have any negative effects from a quick functional test, but perhaps @chrismclarke could assess whether we would expect any knock-on effects relating to changing the order of initialisation of the various core services.
(The fact that the services need to be initialised in this order is actually mentioned in the function description for `initialiseCoreServices`)
As outlined in Issue #1496, no notifications were initially scheduled when …

Fix: Notifications now properly scheduled on initial app launch

---

.github/workflows/test-preview.yml

PR Checklist
Fix issue where deploy preview action no longer correctly interpreting deployment name variable. 
The issue does not appear to be related to any of our own code changes, so assume just down to some core updates within how git processes actions
Closes #

fix: hosting preview

---

src/app/app.component.ts

PR Checklist
Fix regression bug created in #1498. A lot of confusing dependency management going on, we had deferred campaign service evaluation to after local notifications, but realise that the campaigns can be called during the templateProcessService which is used to process some standalone (non-rendered) templates at startup with rows `@campaign.some_campaign`.
Longer term it would be better to ensure some sort of ready$ observable on services that can track if a service is initialisings or has been initialised on demand, so that the exact order the the app.component.ts file is not so important.
Closes #

fix: app services init order

---

packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.ts
src/app/shared/components/template/services/instance/template-row.service.ts

PR Checklist
Fixes bug where template post-processing was not being applied, meaning that variables were not being evaluated and items loops were broken.
Checkout this feature branch, then run `yarn workflow clear_workflow_cache` followed by `yarn workflow sync_sheets` to process all sheets with the updated parser. In Source Control, the only file differences should be genuine changes made since the last content sync. I suggest testing extensively on this branch, perhaps authoring sheets to test the new data-pipe functionalities.
Further investigation is required to look into the source of the issue: as far as I understand it, templates parsed since PR #1490 should have been parsed incorrectly, not receiving post-processing. This didn't seem to be the case. Potentially an issue related to …

Bug: Fix bug where template post-processing was not being properly applied

---

packages/scripts/src/commands/app-data/convert/index.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts

PR Checklist
A further bug fix following on from PR #1514.
The method used to assign template overrides was not being called by the sheets processor, since PR #1490. 
This PR makes the `postProcessFlows()` method for each parser explicitly called within `flowParser.postProcess()` to ensure that `templateParser.postProcessFlows()`, which handles assigning the template overrides, is called. There may be a more idiomatic way to achieve this, in the context of our parsers, but I believe this approach meets our current needs.
This PR also updates the version code for the `AppDataConverter` in order to invalidate any author's previous caches and force all the sheets to be reprocessed using the updated parser.
Because the `AppDataConverter` version number is updated, you shouldn't need to …

bug: fix template overrides

---

packages/data-models/flowTypes.ts
packages/scripts/src/commands/app-data/convert/utils/app-data-action.utils.ts
src/app/shared/components/template/components/points-item/points-item.component.html
src/app/shared/components/template/components/points-item/points-item.component.scss
src/app/shared/components/template/components/points-item/points-item.component.ts

PR Checklist
Adds an optional "info" button to the top right of the `parent_point_box` component. The button is present iff an `info_icon_src` is provided to the component. The actions triggered on click of this icon are set at the template level, via the new `info_click` trigger in the action list of the `parent_point_box` component.
See [example_parent_point_box](https://docs.google.com/spreadsheets/d/1OzJtUnbn8b4km7x7eYmCajOugn9syQhdzWEUzuILIkc/edit#gid=63099847).
The star containing the counter is shifted to the left of the box in order to put the info button in its most natural place (even when there is no info button).
Adding a new type of action trigger, in this case `info_click`, is generally not desirable, but I think it is potentially justified here – it offers a very efficient …

feat: add info button to 'parent point box' component

---

src/app/shared/components/template/components/points-item/points-item.component.ts

PR Checklist
Clicking on the info button on the `parent_point_box` component sometimes undesirably caused the box itself to be click also. See issue #1536.
Closes #1536 
Video showing the component in [example_parent_point_box](https://docs.google.com/spreadsheets/d/1OzJtUnbn8b4km7x7eYmCajOugn9syQhdzWEUzuILIkc/edit#gid=63099847) working as expected. The output of the `info_click` `set_field` action can be seen in the console log. 
https://user-images.githubusercontent.com/64838927/194067033-3ae551dd-65d0-4338-b8b9-06c04eb89d77.mov

fix: prevent info button sometimes triggering click on box below

---

documentation/docs/authors/quickstart.md
packages/data-models/workflows/sync.workflows.ts
packages/scripts/src/tasks/providers/gdrive.ts

PR Checklist
Just running a belated re-review of #1519, all looks good to me although I've previously been trying to deprecate some of the `yarn scripts` commands in favour of workflows so added a quick PR here to migrate the code a little.
Namely
- add a `sync_authorize` workflow and update getting started readme accordingly (note, I don't think this actually needs to be explicit as first run will prompt if auth does not exist, although probably good to keep for reference if we ever want people to manually re-authenticate)
- update the authorize command to also remove existing auth (I found I wasn't being prompted to create new credentials but the old kept failing)
- code tidying on the `gdrive` tasks to add authorize command (to call from task instead of app-data), and refactor a bit of …

chore: add authorize workflow

---

packages/scripts/src/commands/app-data/convert/index.ts
packages/shared/src/models/dataPipe/operators/concat.spec.ts
packages/shared/src/models/dataPipe/operators/concat.ts
packages/shared/src/models/dataPipe/utils.ts

PR Checklist
Fix issue identified where concatenating 2 lists with columns in mixed orders would populate data incorrectly
- Add normalisation step to concat operations to ensure columns aren't accidentally omitted
- Ensure normalisation also enforces consistent column order
- Add additional test data and spec test for local testing
Recommend testing against the example data. 
I've gone ahead and bumped the parser core version which should invalidate all existing cached data. Syncing locally I can see there are definite changes, so just needs to be cross-checked if the changes are as expected
Closes #1515
Closes #1557

fix: concat normalisation

---

packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts

PR Checklist
When appending columns using data pipes, references to `@row` are evaluated too early (against their original sheet) instead of the context of the row that the column is being appended to. This PR omits `@row` default parsing step for all data_pipe, instead evaluating in the context of the full row when processing in the data pipeline
A weird side-issue emerged during this where actually it's only rows with `{@row.some_column}` are lost, so an original example of `hello: @row.id` was still working but not `hello: prefix_{@row.id}_suffix` - I can't quite pinpoint why this is the case so for now will just proceed with the fix above and can revisit if the issue emerges again
Closes #
Updated sheets looks like fields should be populated correctly

fix: prevent data pipes replacing @row self refs

---

package.json
packages/data-models/flowTypes.ts
src/app/shared/components/template/components/carousel/carousel.component.html
src/app/shared/components/template/components/carousel/carousel.component.scss
src/app/shared/components/template/components/carousel/carousel.component.spec.ts
src/app/shared/components/template/components/carousel/carousel.component.ts
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/template.module.ts
src/global.scss
yarn.lock

PR Checklist
Adds a `carousel` component.
Our current use case is on the home page of the new ["professional" skin](https://github.com/IDEMSInternational/parenting-app-ui/issues/1455). Currently this component includes the minimal functionality for this use case, but it could be expanded upon in future to offer additional functionality and expose more options to the templates, making use of the features of the [SwiperJs](https://swiperjs.com/angular#swiper-component-props) library.
Closes #
Demo of basic functionality, using the template [comp_carousel](https://docs.google.com/spreadsheets/d/1f_vq3KFGlExf1-g1PwPiDad9gOZkIOdRE5X99jCIRsM/edit#gid=569531329).
https://user-images.githubusercontent.com/64838927/197522625-8b6e2115-eeec-4457-b001-2f09ed6b83b6.mov

feat: Carousel component

---

packages/shared/src/models/dataPipe/operators/concat.spec.ts
packages/shared/src/models/dataPipe/operators/concat.ts
packages/shared/src/models/dataPipe/pipe.spec.ts
packages/shared/src/models/dataPipe/pipe.ts
packages/shared/src/models/dataPipe/utils.spec.ts
packages/shared/src/models/dataPipe/utils.ts

PR Checklist
- Add log of explicit duplicate ids that are thrown in error when apply index to dataframe (e.g. during concat operation in data pipes)
This is mostly just a quick fix to include a bit more error information. To provide full context (e.g. template names, path to excel etc.) it would need tighter integration with the current logging system which would need a larger PR. So suggest for now we move to merge these incremental changes and flag a new issue in the future if we find difficulty troubleshooting further errors. 
The only way to functionally test would be to author data pipes with known errors. This would probably be good to have more generally, but might be a bit time-consuming to do right now.
Closes #1578
When creating a dataframe that expects unique index values (e.g. …

chore: improve error logging during data pipe ops

---

src/app/shared/components/template/components/carousel/carousel.component.ts

PR Checklist
Minor PR to apply our usual template parameter naming convention to the parameters for the `carousel` component.
- `slidesPerView` -> `slides_per_view`
- `spaceBetween` -> `space_between`
Also updated the [comp_carousel](https://docs.google.com/spreadsheets/d/1f_vq3KFGlExf1-g1PwPiDad9gOZkIOdRE5X99jCIRsM/edit#gid=569531329) sheet

chore: applied correct naming convention to carousel component's parameters

---

src/app/shared/components/template/components/task-card/task-card.component.html
src/app/shared/components/template/components/task-card/task-card.component.ts
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
The task-card component should be passed the following parameters (in addition to `title`, `subtitle`, `image`, `style`, `in_progress_icon` and `completed_icon`):
- `task_group_id`: i.e. a `workshop_id`, e.g. `w_self_care`
- `task_group_data`: the data list that lists the constituent tasks of the task group e.g. `w_self_care_task_gs` (or just `w_self_care_tasks`?) 
- `completed_field`, the field that store whether this particular task group is complete, e.g. `w_self_care_completed`
Previously, just the `task_group_id` was passed, and the other 2 values were inferred from it. However this involved appending hardcoded suffixes within the code (`_task_gs` and `_completed`)
[module_card](https://docs.google.com/spreadsheets/d/1WGXQpDIzsS-FbDX_aLXJ4geT03Uqjdc4Fm4m2C2W2fY/edit#gid=1 …

chore: task-card takes additional params: task_group_data_list and completed_field

---

packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_list.parser.spec.ts

PR Checklist
Add spec tests for data_list specific code. These were drafted while debugging some other issues, so thought would be a good time to add (will still need to add future tests for template and default parsers)
- The data_list parser extends the default parser, and so doesn't actually handle many extra features. It would be good to review the features it does handle and see if still relevant (not sure `notification_schedule` is used in any data_lists)
- Run the tests via `yarn workspace scripts test:watch`. Any single test can be run standalone by converting `it(...)` to `fit(...)`
Closes #
**Specific data_list capabilities added to test spec**

test: add data list parser tests

---

src/app/shared/components/template/components/task-card/task-card.component.html
src/app/shared/components/template/components/task-card/task-card.component.ts
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
The task-card component now triggers the "completed" actions when all of its constituent actions are completed for the first time. 
This, in conjunction with adding `nav_resume | emit: force_reload` to pages that display task-cards for modules, allows us to fix the issue outlined in #1605. The task-cards for modules must also handle the `completed` actions at the template level, namely by triggering a `force_reload` when the component fires a "completed" trigger (`completed | emit: force_reload`).
Closes #1605
[home_screen_mod_reload_1](https://docs.google.com/spreadsheets/d/1Whi-zledVspIAd_hmAiItv2OxWnmtOVs8PEuCl0Eu8U/edit#gid=1677084943)
Example of completing a module, demonstrating the expected behaviour of marking that module as completed and marking the following module …

Fix: Task card components update to reflect changes in completion status

---

src/app/shared/components/template/components/task-card/task-card.component.html
src/app/shared/components/template/components/task-card/task-card.component.scss
src/app/shared/components/template/components/task-card/task-card.component.ts
src/app/shared/components/template/components/toggle-bar/toggle-bar.scss

PR Checklist
Adds a new style parameter option to the `task-card` component: `style: button`. Makes the task card display as a narrow button with the image appearing small and on the right. A toggle can also be provided in the child rows of the component. This is visually equivalent to the existing `button` component with `style: card`, but, as outlined in Issue #1608, the `task-card` component supports displaying the completion status of its related task, e.g. a green tick.
Closes #1608 
[comp_task_card](http://localhost:4200/template/comp_task_card) updated with examples of new style.

feat: added 'button' style param to task-card

---

src/app/shared/components/template/components/drawer/drawer.component.html
src/app/shared/components/template/components/drawer/drawer.component.scss
src/app/shared/components/template/components/drawer/drawer.component.ts

PR Checklist
Adds an optional `style` parameter to the `drawer` component. When `style` is set to `secondary`, the background colour of the drawer takes the secondary colour of the active theme.
Currently the text colour of the component with `style: secondary` is hardcoded as white, in order to match the designs of the modular skin (see issue #1604). 
Closes #1604 
From template [comp_drawer](https://docs.google.com/spreadsheets/d/1NY-FwPH7AZNlBoaS3Oi0E5j20ppdZwt0zbnqh72D1Tk/edit#gid=569531329)
https://user-images.githubusercontent.com/64838927/199278347-b0028fff-88c0-4674-983f-4274b1f1a118.mov

feat: add 'secondary' style to drawer component

---

src/app/shared/components/template/components/drawer/drawer.component.ts

PR Checklist
Fixes a bug whereby the drawer component would sometimes not fully open (Issue #1628).
This bug was due to the "open height" for the drawer being calculated on initialisation of the component, which would sometimes happen before the drawer element and its children had finished loading. This PR forces the open height to be recalculated each time the drawer is expanded, ensuring that the value is up to date with the DOM. This has the additional benefit of allowing for the drawer's contents to change dynamically between being opened, should this functionality be required.
Closes #1628
Demonstrating the drawer working as expected in the template [home_screen_modular](https://docs.google.com/spreadsheets/d/1Whi-zledVspIAd_hmAiItv2OxWnmtOVs8PEuCl0Eu8U/edit#gid=1771109624). As the …

fix: drawer component always expands fully

---

src/app/shared/components/template/components/task-card/task-card.component.html
src/app/shared/components/template/components/task-card/task-card.component.ts
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.html
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
Adds 2 optional parameters to the `task_card` component: `highlighted_text` and `progress_units_name`. If provided, the values replace the strings that were previously hardcoded into the component: "Active" and "sections" respectively.
This enables these strings to be included in the translation system. These parameters should be specified, with the values "Active" and "sections", for all instances of the `task_card` component currently in the templates that display a task group (i.e. a workshop in our current usage), along with taking any other steps to ensure that the values of these parameters are included in the translation system. 
Closes #
Demonstration of custom values in [feature_task_card_params](https://docs.google.com/spreadsheets/d/1_RY8HbsATOAZU2EDXY5R9OOE_YBEbW0E …

feat: override strings in task-card from templates

---

packages/scripts/src/commands/app-data/copy.ts
packages/scripts/src/utils/string-utils.ts

PR Checklist
Where an active deployment filtered for language codes (i.e. when it specified `filter_language_codes`), theme asset folders were not being included when syncing. E.g. in the case of the `plh_tz` deployment, the assets in the `theme_professional` folder were not being included when syncing assets, as outlined in #1622.
This PR ensures that theme asset folders are not automatically excluded when a deployment filters on language codes. Additionally, it applies a filter on the theme asset folders, excluding any assets that are in folders relating to themes that are not included in the list of `available` assets for that deployment. This allows for the case of sub-deployments (or deployments with the same gdrive `assets_folder_id`) with different "available" themes – the assets …

Fix: Handle theme asset folders when syncing from different deployments

---

src/app/shared/services/task/task.service.ts

PR Checklist
The task service was causing a breaking error for builds of deployments that did not make use of the task system. Specifically, the task service currently uses a hardcoded value, `workshop_tasks`, to look up the data list of task groups that can be highlighted. If this data list was not present for a given build, the app would error on initialising the core services.
This PR offers a workaround by not fully initialising the task service unless the `workshop_tasks` data list is found. There is further discussion to be had about the potential for generalising the "task" system in a way that makes sense across deployments.
Closes #
The bug as it previously presented:

fix: deployments without task groups do not error on initialisation

---

packages/scripts/src/commands/app-data/copy.spec.ts

PR Checklist
Spec tests for copy script were likely written before changes to theme support, and so fail on recent builds. Minor fix to provide default available themes for spec tests
Closes #

fix: add default app themes to copy spec

---

packages/app-data/sheets/template/pair.json
src/app/shared/components/template/components/layout/animated-section.scss
src/app/shared/components/template/components/layout/animated_section.ts

PR Checklist
- Add fade animation for animated sections
- Includes authoring fix for #1356
To test issue in 1356 will need to run PR preview link in chrome 80 and go to `/template/w_stress_read_1_temp` - should be working whereas not working on something like the plh-global web app version
https://chromium.cypress.io/win64
Otherwise can view animated section fade by viewing any animated section content (including the link above). 
Note - the video below is a little bit more jerky than live version
Closes #1356
[Parenting App (3).webm](https://user-images.githubusercontent.com/10515065/204918575-d9fa807d-ab81-45e3-8e61-1c7bfaaac577.webm)

feat: add fade animation to sections

---

src/polyfills.ts

PR Checklist
This fixes a bug for older devices that do not support the `matchAll` function (as noted in #1660)
Whilst this will fix the bug, for reasons noted in #1615 it isn't actually a very good solution, as there's enough other issues with older browsers that fixing this alone is unlikely to achieve very much. But it does at least give a good example for how we can add specific support in the future is similar issues arise
The final implementation is very minimal, so review more just for reference/interest
Support is added by including a link to the relevant polyfill in the polyfills.ts file. It uses the same polyfills that angular exposes in the `core-js` package (no install needed, part of angular deps). 
This is particularly tricky to test as it involves running a legacy browser …

fix: add string matchAll polyfill

---

src/app/shared/components/template/services/instance/template-process.service.ts

PR Checklist
A workaround to fix issue #1640.
This workaround handles the cyclic dependency between the `template-process-service` and the `campaign-service` by forcing the latter to reinitialise after the former has finished processing the startup templates. The performance load of reinitialising the campaign service should be significantly lower after #1673.
Closes #1640
New behaviour shown in video. See issue for previous behaviour.
https://user-images.githubusercontent.com/64838927/206680541-5a5261c0-1d8a-4f13-9ad9-a4ddace124cf.mov

fix: hack: reschedule campaign notifications after processing startup templates

---

.github/workflows/sourcemaps-upload.yml

PR Checklist
Pushing any branch was causing the `sourcemap-upload` action to fail, as [here](https://github.com/IDEMSInternational/parenting-app-ui/actions/runs/3656503088), with the error `No event triggers defined in 'on'`.
This PR adds a trigger to the github action. I've assumed that we want the action to trigger on pushes to master, but I'm happy to be corrected.

chore: add push to master branch trigger for sourcemaps-upload github action

---

src/app/feature/tour/tour.service.ts
src/app/shared/components/template/services/instance/template-action.registry.spec.ts
src/app/shared/components/template/services/instance/template-action.registry.ts
src/app/shared/components/template/services/instance/template-action.service.ts

PR Checklist
Currently, any actions triggered from the template-action service need to first be registered from within the action service. This is somewhat an anti-pattern, as it means the action service needs to import every other service it will interact with (e.g. template, field, tour, analytics, theme etc.), and quickly leads to confusing dependency issues. To make matters more confusing, the action service is instantiated per template container, resulting in a large number of references to the same global services.
This PR tries to reverse this pattern by creating a separate template action registry which can be used to register action handlers from within the child service they originate from. This provides an alternative way to register actions without import into the action …

feat: add support for template action registry

---

angular.json

PR Checklist
Since we updated Angular to version 15 in PR #1694, when running `yarn start` I would receive a prompt asking whether to share anonymous usage data with the Angular Team.
This prompt would disappear without allowing time for a response, but not providing a response would prevent the `yarn start` processes from completing successfully.
This PR commits the changes enacted by responding `N` to the prompt, so it should not be triggered in future.
(Similar to this issue: https://stackoverflow.com/questions/56355499/stop-angular-cli-asking-for-collecting-analytics-when-i-use-ng-build)
On a branch without this change (e.g. master), run `yarn start`. On my machine, the process does not complete: the terminal hangs on this message and the app is not be available on localhost
Now …

chore: configure angular to not share usage data

---

src/app/shared/components/template/components/task-card/task-card.component.scss

PR Checklist
Fixes a visual bug concerning the task-card component with the parameter `style: button`: longer strings of text would wrap prematurely and the button would not expand to fit in all text.
Closes #1727 
The template [comp_task_card](https://docs.google.com/spreadsheets/d/1_RY8HbsATOAZU2EDXY5R9OOE_YBEbW0EjTP5zxYP2aA/edit#gid=569531329), showing the new styling:
The "One-on-One Time" [module_details](https://docs.google.com/spreadsheets/d/1WGXQpDIzsS-FbDX_aLXJ4geT03Uqjdc4Fm4m2C2W2fY/edit#gid=1796638918) component, before and after comparison:

Fix: styling of task-card with button style can handle longer strings of text

---

src/app/shared/components/template/services/template-variables.service.ts

PR Checklist
When updating a local value from within an items context the reference is not populated correctly as the `_nested_name` property is excluded from dynamic variable evaluation. The local variable is automatically set by any component that updates its own value (e.g. text_box or combo_box inputs), so all of these will break whenever more than 1 item is displayed on the page (both will have a nested_name like `@item.id.text_box`). 
This PR fixes to include _nested_name in the list of fields that get evaluated for dynamic references
Closes #1720
http://localhost:4200/template/debug_teen_ages
[Parenting App (4).webm](https://user-images.githubusercontent.com/10515065/213838520-d044ea37-8ad1-4ef4-9199-6b65713928b4.webm)

fix: items nested name

---

packages/scripts/src/commands/deployment/get.ts

PR Checklist
I noticed a bug after #1756 was merged, whereby the CLI would enter an infinite loop – I believe this was when trying to set the deployment after the current deployment's config had been updated. See video below. This PR should fix this issue.
Closes #
https://user-images.githubusercontent.com/64838927/215776024-9f9837e8-b98c-4dca-9a91-bd6d8b3d68e1.mov

fix: set deployment after config update bug

---

packages/app-data/sheets/data_list/number_data.json
packages/app-data/sheets/template/debug/debug_teen_ages.json
packages/app-data/sheets/template/demographics_teen_age.json
src/app/shared/components/template/processors/item.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/components/template/services/template-variables.service.ts

PR Checklist
Setting and using values from nested items does not work due to inconsistencies in how the nested name is referenced. This PR aims to fix by providing moving the logic to evaluate nested names into the item generator itself (previously the main template parser), which also has improved support for delimited templates.
I've also updated the debug sheet to use the delimited item syntax, and the data list to remove some empty rows (not problematic but side-effect of testing lots of different things)
Closes #1765
[Untitled_ Jan 31, 2023 11_09 PM.webm](https://user-images.githubusercontent.com/10515065/215975262-14baabe8-7069-40d7-aa80-dfa6c29e9859.webm)

fix: dynamic item nested names

---

.github/workflows/documentation-lint.yml
cspell.config.yml
documentation/docs/authors/feedback.md
documentation/docs/authors/notifications.md
documentation/docs/authors/quickstart.md
documentation/docs/authors/template-component-parameter-list.md
documentation/docs/components/round_button.md
documentation/docs/contributors/documentation/authoring.md
documentation/docs/developers/deployments.md
documentation/docs/developers/device-testing.md
documentation/docs/developers/quickstart.md
documentation/docs/index.md
documentation/docs/questions/hidden_condition.md
package.json
yarn.lock

PR Checklist
- Add tool to spellcheck documentation (cspell)
- Add github action to automatically run spellcheck whenever documentation files change
I haven't corrected all the spelling, it would be great if somebody else could help make the required fixes.
Run the spellchecker locally via
```
yarn lint:docs
```
This will show a list of all potential typos, e.g.
Any words that aren't recognised but spelt correctly can be added to the list of words in `cspell.config.yml`, e.g.
```yml
"words":
[
"idems",
"quickstart",
"glitchtip",
```
Any lines that should specifically be ignored should include a comment to disable
```yml
E.g. `1ja6lzbphZaxnVv5mpQ4YHnn2qmxMiEBW`
```
Similarly sections of files or entire files can be disabled as required, discussed in more detail in [CSpell …

feat: add docs spellcheck lint and action

---

src/app/app.component.ts
src/app/shared/services/seo/seo.service.spec.ts
src/app/shared/services/seo/seo.service.ts
src/index.html

PR Checklist
- Add a service to handle update of any SEO metadata
- Add placeholders for future SEO properties
- Remove default `title` from main page HTML ("Parenting App" for all deployments)
- Set page title from deployment
The only property being set is the document title, which is what the browser tab uses for a name. So can just test that on a couple different deployments (should be same as app header title)
I expect we will also want to include an authoring option to change the icon that appears in the browser bar, this would be best as a follow-up issue as we will likely need to update the deployments a little so better after #1763 sorted.
We may also want to provide best-practice info for authors, e.g.
https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/ …

feat: add seo service

---

packages/@idemsInternational/gdrive-tools/src/commands/download.ts
packages/@idemsInternational/gdrive-tools/src/utils/file.utils.ts
packages/scripts/src/tasks/providers/gdrive.ts

PR Checklist
Minor PR (extracted from #1755), to add additional housekeeping to gdrive download scripts, namely:
- Delete any downloaded files that are no longer included in the deployment (previously would keep download and just omit on copy)
- Clear any empty folders
- Add support for passing filter functions to gdrive download script (included already in deployment config but never implemented)
Shouldn't have any real knock-ons anywhere, if you had previously synced lots of files into a workspace there might be some lingering folders that get removed from the tasks cache (e.g. `.idems_app\deployments\plh_global\tasks\gdrive\outputs\1dp9QAQ84m8pm0IBQTSPXe1ramyynKPNn`).
When running a sync myself saw no changes to the files actually populated into the main app, and when repeating sync …

chore: add gdrive empty folder deletion

---

src/app/feature/campaign/campaign.service.ts
src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/services/task/task.service.ts

PR Checklist
Offers a workaround for #1799 – upon the highlighted task group (aka "highlighted module") changing, all campaign notifications will be re-evaluated. This ensures that the scheduled status of any campaign notifications that depend on the current highlighted task group is up to date.
#1799 should be left open as the requested feature is still desirable

feat: reschedule campaign notifications when the highlighted task group changes

---

src/app/feature/notification/pages/notifications-debug/components/notification-debug-interacted-row.component.ts
src/app/shared/services/notification/local-notification-interaction.service.ts

PR Checklist
Interacting with a notification whilst on the `notifications` page of the app would cause an error to be thrown repeatedly and indefinitely. This was, I think, only an issue when running in browser, and only applies when the user has the notifications page open (which is only available in dev mode), so is not an important issue.
This PR provides a workaround so that sent notifications appear correctly when interacting with them from the `/notifications` page.
I believe this is just an issue on web and that this is a workaround.
Previously, interacting with a notification caused the notification to be saved to the database, however the `notification_meta` was not saved, as the `sessionNotifications$` observable did not update to trigger the `notification_meta` being saved for …

Fix: infinite errors thrown when entering the app through a notification

---

.idems_app/deployments/plh/config.ts
.idems_app/deployments/wash/config.ts

PR Checklist
This enables the opt-in "in-app updates" feature (introduced in PR #1803) for the deployments `plh` (and therefore its children) and `wash`.
I've also updated the respective `launch_actions` templates for [plh](https://docs.google.com/spreadsheets/d/1MJzzdTYDZg0VkS5zxrXY4lKV5Oi954pw1sIVJUOOzWM/edit#gid=1876097204) and [wash](https://docs.google.com/spreadsheets/d/1EBMsJnyEEbNZPwkwHzdjm3f5av8kNethAGMpTJ7HOC0/edit#gid=1876097204), but I have not included a content sync in this PR.
The template that will be shown as a pop-up when the user has finished downloading an update is [here for plh](https://docs.google.com/spreadsheets/d/1H6VhPmnxOIV5tw9p4XbVYS0tfNU3M7KZzgH9GmomNPI/edit#gid=1422144003) and [here for wash](https://docs.google.com/spreadsheets/d/1EBMsJnyEEbNZPwkwHzdjm3f5av8 …

chore: enable in-app updates for plh and wash deployments

---

android/app/build.gradle
package.json
packages/app-data/sheets/template/w_self_care_reward_tz.json

PR Checklist
Fixes an issue where the final "next" button on the w_self_care_reward template wasn't working.
Closes #1860

fix: navigation not progressing after completing w_self_care_reward with tz override

---

packages/data-models/deployment.model.ts
packages/data-models/index.ts
packages/scripts/src/commands/deployment/common.ts
packages/scripts/src/commands/deployment/compile.ts
packages/scripts/src/commands/deployment/utils.ts

PR Checklist
Changes to deployment config defaults can break local developer config if not recompiled. There is a versioning variable used to force recompile, however it's hidden away in script configuration file and so easily missed.
This PR moves the deployment config version variable to the config model file itself, and bumps to force recompile of developer configs following updates in #1873
Check out branch and set deployment same as current. This should force config to recompile (previously would have remained the same)
Closes #
You can see if a config is being recompiled by the `Compiling:` console output

refactor: deployment config recompile tracking

---

packages/data-models/workflows/sync.workflows.ts
packages/scripts/src/commands/workflow/run.ts

PR Checklist
While working on #1893 discovered content-watch mode no longer working as expected (possibly due to dependency upgrades or workflow name changes). Options set at the top level `sync` command were not filtering down to child commands
Running `yarn workflow sync --content-watch` should now listen for keep connection alive and update on content updates
Closes #

fix: workflow-options

---

cspell.config.yml
documentation/docs/developers/images/firebase-hosting-add-site.png
documentation/docs/developers/web-previews.md
documentation/mkdocs.yml

PR Checklist
Documents the process required to create a new web preview for a given deployment (adding a Firebase Hosting site and associating that site with the deployment). This process may change once we have separate [git repos for deployments](https://github.com/IDEMSInternational/parenting-app-ui/milestone/5), however I wanted to document this proces for @esmeetewinkel, and I see no harm in including it in the public docs in the interim.
It may be desirable to eventually have a workflow that handles making the changes to the files. However, using the Firebase CLI to generate the files would require the dev/author having the required permissions and logging in via the CLI. Additionally, I believe that creating the new Firebase Hosting site is not something that can currently be done …

docs: add docs for creating a new web preview for a deployment

---

packages/scripts/src/commands/app-data/postProcess/assets.ts

PR Checklist
Fixes an issue where the asset sizes logged when running `yarn workflow sync` were incorrect. I believe this should have been picked up when testing #1874. 
1. Checkout master, and set the active deployment to plh_global – `yarn workflow deployment set plh_global`
2. Run `yarn workflow sync_assets` and note the log of the asset size breakdown. It should be similar to the following screenshot. Note that, as well as "theme_default theme", there is an extra entry for "default theme" which will always display 1MB.
3. Now checkout the feature branch, `git checkout fix/asset-size-breakdown`
4. Run `yarn workflow sync_assets` again, and you should see the following. Note that the default global assets are now being included correctly in the total size.
Closes #
The asset size …

fix: log of asset size breakdown

---

packages/scripts/src/commands/app-data/postProcess/assets.ts
packages/scripts/src/utils/string-utils.ts

PR Checklist
- Add `app_core` to asset breakdown (currently hardcoded as rough approximation of current app)
- Include core build in quota warning (and bump to 150MB)
- Fix rounding bug in size_mb calculations
In the future we will likely want to add a step to build/ci pipeline to automatically update core build, but for now would be good to just redo manually following pdf component pr or any other prs known to add sizeable assets
Closes #

feat: add asset core size

---

packages/scripts/src/tasks/providers/git.ts

PR Checklist
After #1755, and some additional changes to the the [app-debug-content repo](https://github.com/IDEMSInternational/app-debug-content), a git error was triggered when trying to refresh the remote content from that repo (e.g. when running `yarn workflow sync` from a local clone of the parenting-app-ui repo, with the `debug` deployment active).
Whilst we haven't found the exact cause, this PR fixes the issue by specifying the remote branch to pull from when running a programmatic `git pull`.

fix(git repos): specify branch to pull from when syncing remote content repo

---

.github/ISSUE_TEMPLATE/crashlytics.md
.github/ISSUE_TEMPLATE/glitchtip.md

PR Checklist
Updates our github issue templates to reflect the move to using Glitchtip error tracker from Crashlytics
Closes #

chore: change github issue template 'crashlytics' -> 'glitchtip'

---

angular.json

PR Checklist
As a temporary workaround to minimise the app bundle size for the plh_tz deployment, it was agreed in a 23/05/23 meeting that the assets required by the pdf viewer library used in the pdf viewer component introduced in #1918 should be excluded from the build on the plh_tz deployment branches. This means that the pdf viewer component will not work on builds created from these branches, which is acceptable in the short term as this deployment does not make use of that component.
Closes #1940

chore: excluded ngx-extended-pdf-viewer assets from build

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts
src/app/shared/components/template/components/toggle-bar/toggle-bar.html
src/app/shared/components/template/components/toggle-bar/toggle-bar.scss
src/app/shared/components/template/components/toggle-bar/toggle-bar.ts

PR Checklist
- Adds a new variant for the button component, `card-portrait`
- Adds an additional parameter related to this variant: `image_asset` (NB, this uses the new `_asset` suffix convention as suggested in #1979)
- Adds a new variant for the toggle bar component, `icon`
- Adds additional params related to this variant: `icon_true_asset` and `icon_false_asset`
This continues the "variant" convention introduced in #1970 . We may want to alter this convention according to changes we decide to make in relation to #1971 (e.g. "variant" may end up being a column rather than a component parameter). However, the convention followed in this PR would still represent a step in the right direction, and this component variant is needed urgently.
It seemed sensible to me to leave the inclusion of …

feat: new 'card-portrait' variant for button component

---

.idems_app/deployments/plh/config.ts
.idems_app/deployments/plh_tz/config.ts

PR Checklist
In order to reduce the size of the app bundle to under the 150MB Play Store limit, which the `plh_tz` deployment was in danger of exceeding, it was decided that we could compress the audio files that are included in the app. 
All audio files for the `global` and `tz_sw` languages have now been compressed, reducing their size by around 60%, and reducing the size of all assets included in the `plh_tz` deployment to around 98MB. We agreed that any loss in audio quality was very difficult to detect (see [this Mattermost thread](https://chat.idems.international/all/pl/ux8jhtkhcjfu88yyzbh7qyr19a) for discussion and description of the compression process).
In order to keep the original uncompressed audio files, in case there are any issues with the compressed versions and …

feat: exclude uncompressed audio assets from plh deployments

---

src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
src/app/shared/components/template/components/dashed-box/dashed-box.component.ts

PR Checklist
It fixes the error of too much padding in the dashed-box component, and handles the issue of there being a TypeError when no value is passed (see discussion under #2014).
Closes #2017

Fix: Too much padding on the dashed_box; handle case of no value

---

src/app/shared/components/template/components/accordion/accordion.component.html

PR Checklist
Fixes an issue whereby text in the titles of accordion sections would not wrap, meaning text would be cut off on smaller screens.
Closes #2036
[example_accordion](https://docs.google.com/spreadsheets/d/1gfnWmr59DF0ZsuSuBh0K1o9fMqEg-z6Qa7eJNsiB-rQ/edit#gid=63099847) template:
[w_svp_learn_use_voice](https://docs.google.com/spreadsheets/d/1sW2Cx4JdLLFzy-2zn4syUiFcXJECku6nNtyo02EIM38/edit#gid=715202550) template

fix: text-wrap on accordion titles

---

src/app/shared/components/template/components/accordion/accordion.component.html
src/app/shared/components/template/components/animated-slides/animated-slides.component.html
src/app/shared/components/template/components/layout/accordion-section/accordion-section.component.html
src/app/shared/components/template/components/layout/advanced-dashed-box/advanced-dashed-box.component.html
src/app/shared/components/template/components/layout/animated_section.ts
src/app/shared/components/template/components/layout/animated_section_group.ts
src/app/shared/components/template/components/layout/display-grid/display-grid.component.html
src/app/shared/components/template/components/layout/form.ts

PR Checklist
Some components, e.g. `accordion`, loop over their child rows and render each one. Some rows, e.g. `set_variable` are not intended to be rendered, and so should be excluded from the iterable. A solution to filter out such rows from the list to be rendered was already applied to some components, notably `display_group`. This PR applies that solution to the accordion component, fixing #2083, as well as to all other remaining components that loop over their child rows (`animated-slides`, `accordion-section`, `advanced-dashed-box`, `animated-section`, `animated-section-group`, `display-grid` and `form`).
Closes #2083
[debug_accordion_variables](https://docs.google.com/spreadsheets/d/1AkNZZWGCCwU8olUaoLsAozmZ_7DJaOaEuHOa-LhGci8/edit#gid=1216295414)

fix: for all components that render child rows, filter out non-display rows

---

.idems_app/.gitignore
.idems_app/deployments/debug_gdrive_multiple/.gitignore
.idems_app/deployments/debug_gdrive_multiple/config.ts
packages/data-models/deployment.model.ts
packages/scripts/src/commands/app-data/convert/convert.spec.ts
packages/scripts/src/commands/app-data/convert/index.ts
packages/scripts/src/commands/app-data/convert/processors/base.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.spec.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/scripts/src/commands/app-data/postProcess/assets.spec.ts
packages/scripts/src/commands/app-data/postProcess/assets.ts
packages/scripts/src/commands/deployment/templates/config.default.ts
packages/scripts/src/tasks/providers/appData.ts
packages/scripts/src/tasks/providers/template.ts
packages/scripts/test/data/input/sheets_additional/test_additional_input.xlsx
packages/scripts/test/helpers/utils.ts
packages/shared/src/utils/file-utils.ts
packages/workflows/src/deployment.workflows.ts
packages/workflows/src/sync.workflows.ts

PR Checklist
Adds support for specifying multiple google drive sheet and asset `folder_ids`, to allow syncing content from multiple data sources.
All deployment configs should now specify an array of google drive `sheets_folder_ids` instead of a single `sheets_folder_id`, and an array of `assets_folder_ids` instead of a single `assets_folder_id`. A warning will be displayed if not the case, but should still continue to work as before (functionality deprecated but not removed).
While working on code it appears that `google_drive.sheets_filter_function` wasn't being properly passed to google drive sync scripts. I'm not sure if any deployments were using this, but would be good to ensure everything working as intended if they are. This function filters based on google drive entry (e.g. …

feat: sheets multiple folder ids

---

README.md
documentation/docs/developers/deployments.md

PR Checklist
Updates the Deplyoments page of the docs with the new syntax for multiple gdrive folder_ids in deployment configs, introduced by #2088.
Adds clarification to the top-level Quickstart readme regarding setting a deployment, which had caused some confusion.
Closes #
Updated sections of [Deployments](http://127.0.0.1:8000/developers/deployments/) page:

docs: update deployment config format for multiple folder IDs; clarify deployment set in top-level readme

---

packages/workflows/src/sync.workflows.ts

PR Checklist
Following #2091, fix for issue where `sync --content-watch` workflow would break for deployments with multiple `sheets_folder_ids` specified
There will be some duplicate logging of 'watching drive changes...' for each folder looped over in watch scripts. While we could just move the console log to the workflow itself, I think probably good to retain as a reminder that in the future we could probably optimise better (find a way to use one watcher across multiple folders)
I have tested to check that even with multiple watchers the file change script is only triggered once (screenshot below)
Should use `debug_gdrive_multiple` deployment and `--content-watch` sync flag. Making changes to sheets within folders trigger reload
Folder links: …

fix: gdrive watch mulitple

---

src/app/shared/components/template/components/dashed-box/dashed-box.component.ts
src/app/shared/components/template/pipes/markdown.pipe.ts
src/app/shared/utils/utils.ts

PR Checklist
Hyperlinks written in markdown are now interpreted such that the link always opens in a new tab when using the app in a browser.
There may be cases in the future where we do not want a link to open in a new tab. For example, as mentioned in the issue (#2099), if we implement links to other pages within the app, we would not necessarily want these to open in a new tab. However, handling that use case can be considered as part of #1504.
Run the app locally from this feature branch and verify that the links on the templates [debug_markdown_links](https://docs.google.com/spreadsheets/d/1b0FK3Eggz76H_C9lRdFVVLUxUBEZPruoyaF0d6YeWSI/edit#gid=1510672503) and [debug_dashed_box](https://docs.google.com/spreadsheets/d/1_gnFbp23_wovBK5mtsppiHpYmqNfS3fvb0fYnP66qZI/edit#gid=669305399) open …

feat: links open in a new tab

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Pop-ups will now dismiss when the child template emits "completed" or "uncompleted". This was already the case for full-screen pop-ups, but now extends to non-full-screen pop-ups.
This seems to be the expected behaviour, however it is possible that this may interfere with some existing functionality, so if necessary we could expose `dismissOnEmit` as an action parameter (and possibly default to `false`).
See new [debug_pop_up_dismiss](https://docs.google.com/spreadsheets/d/1XDugKSTqqEScibrWH0OkTTFf-lqsZREob37EeieQUWI/edit#gid=963655109) template for testing functionality.
Previous [example_pop_ups](https://docs.google.com/spreadsheets/d/1K9JZ9Glnj73CFJmpfGIRa5dRA2TBxSsJmaguV6GL8Pc/edit#gid=402992224) seems to be out-of-date – the functionality described in the comments does …

fix: pop-ups dismiss on completed or uncompleted

---

src/global.scss

PR Checklist
Sets the word-wrapping property for hyperlinks to "break-word" globally across the app. This will ensure that links for long URLs do not cause styling issues, as was observed for the `dashed_box` and `advanced_dashed_box` components in issue #2094.
Closes #2094 
[debug_long_link_dashed_box](https://docs.google.com/spreadsheets/d/14Fub-lf6xLc6nG3_Mnab1qAcfLK88yfYJzlJQGXi-2M/edit#gid=861085862)

style: 'break-word' wrapping for hyperlinks

---

src/app/shared/components/template/services/template-calc-functions/plh-calc-functions.ts
src/app/shared/components/template/services/template-calc.service.ts

PR Checklist
When a calc function tries to refer to another calc function everything works fine in development, however in production there is a mismatch in the names of functions made available to evaluator context, and the names of the functions as minified by the angular compiler. 
This PR adds a small workaround so that all calc functions can also be accessed via a `window.calc` method, which preserves the names. 
Create a production build
```sh
yarn build
```
Use npm `serve` module to serve the contents of the production build locally (reads from local `seve.json` for config)
```sh
npx serve
```
I've added to #2131 as a reminder to try and address this issue in a better way in the future if possible (currently still possible for developers to write functions that work locally but not …

fix: plh-function shared references

---

src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Offers a workaround for #2120. Please see [this comment](https://github.com/IDEMSInternational/parenting-app-ui/issues/2120#issuecomment-1795487136) on that issue for context.
Adds a parameter to the `go_to` action, `dismiss_on_return`, to be used in the specific case of using a `go_to` from an active pop-up. If this parameter is passed `true`, then on returning to the parent template from which the pop-up was launched, the pop-up will be closed.
Whilst the `dismiss_on_return` action arg does what it says on the tin and so is potentially a legitimate feature, it is a workaround/hack for our current use case and doesn't fully demonstrate the desired functionality. The intermediary template (the pop-up) will dismiss on return to the parent template regardless of how the user …

feat: new go_to action argument: dismiss_on_return

---

packages/data-models/flowTypes.ts
src/app/shared/components/template/services/template-nav.service.ts

PR Checklist
Possible alternate implementation for behaviour in #2134
Added by @jfmcquade: Also renames the parameter passed to the `go_to` action: `dismiss_on_return` -> `dismiss_pop_up`. This more accurately describes the behaviour of the feature. This is a breaking change that will require changes to the templates that implement this feature, which appear to be [in_person_unreported](https://docs.google.com/spreadsheets/d/1S7q_hrEpSG-owuRC9oEwMHnTa-ywTJwT2_SEc1rNF1g/edit#gid=1606639158) and [virtual_unreported](https://docs.google.com/spreadsheets/d/1S7q_hrEpSG-owuRC9oEwMHnTa-ywTJwT2_SEc1rNF1g/edit#gid=1696774054). (Alternatively we could support both syntaxes to avoid deprecation, but it should be easy to make the changes at this stage and avoid including the deprecated syntax in the …

refactor!: popup-nav-dismiss

---

src/theme/themes/_index.scss
src/theme/themes/pfr.scss
src/theme/themes/utils/generate-theme.scss
src/theme/variables.scss

PR Checklist
Adds a new theme specifically for the PfR deployment. 
The new theme uses the colours black and red as the two source colours from which the theme is generated. It also uses the specific shade of green, taken from the logo, as the "success" green colour used throughout the app (e.g. for the green ticks on completed modules). I did experiment with other combinations of the colour scheme, but these resulted in red and green being too prominent, which looks odd but also conflicts with the standard use of red and green as "success" and "warning" colours in apps (although currently we don't use red anywhere by default). See the screenshots at the very bottom of the PR description for the rejected colour schemes.
It may be that further tweaks are necessary as a follow-up, either to …

Feat: PfR theme

---

packages/shared/src/utils/async-utils.ts
packages/shared/src/utils/cli-utils.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/logging/console-logger.ts
packages/shared/src/utils/logging/file-logger.ts
src/app/shared/services/data/app-data.service.spec.ts
src/app/shared/services/data/app-data.service.ts
src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

PR Checklist
Fix issue where calling multiple dynamic-data service queries in parallel could lead to multiple db collection creation requests throwing rxdb error. Specifically:
- Implement a queue-type system to prevent duplicate db create requests when creating multiple queries in parallel
- Add test case
Additional work is included to refactor the app-data mocks 56a749a, to fix a regression issue brought in by changes to the app-data mocks in #2107. Data had been copy-pasted from the app-data mock to the dynamic-data mock (which is super fragile), breaking tests when source app-data mock changed. Now mock services can specify their own data when implementing the app-data mock. 
This is also another good reminder why we should try to  fix up the rest of the ng test suite and integrate …

fix: dynamic data service multiple queries

---

.github/workflows/reusable-android-build.yml
android/app/build.gradle
package.json

PR Checklist
PR increase version number to 0.16.24

chore: increase version number to 0.16.24

---

packages/scripts/src/commands/version.ts
packages/shared/src/paths.ts

PR Checklist
As suggested in [this comment](https://github.com/IDEMSInternational/parenting-app-ui/pull/2170#discussion_r1428199826), adds an ugly workaround whereby running `yarn scripts version` updates the version values targeted for replacement by `.github/workflows/reusable-android-build.yml` to match the new values populated to `./android/app/build.gradle`.
As mentioned, this is a temporary workaround pending directly addressing #2136.
With this PR branch checked out, run `yarn scripts version` with a sensible value, and ensure that the changes to all 3 files look correct
Closes #

hotfix: yarn scripts version also updates strings targeted by android build action

---

.github/workflows/reusable-android-build.yml
android/app/build.gradle

PR Checklist
The [android_release action on the plh-facilitator-mx repo](https://github.com/IDEMSInternational/plh-facilitator-app-mx-content/actions/runs/7716921308/job/21035275279) is failing. This is likely due to the merging of #2170 – the plh-facilitator-mx repo targets release v0.16.23 of the code, but uses the `reusable-android-release` action from master. As this action looks for a specific release number string to be replaced, and as #2170 had updated the target number, the number was not being replaced correctly.
This is a temporary workaround: the action should be reworked to target a placeholder variable instead of a specific version number, or a more thorough improvement should be implemented, as suggested in #2136 
Closes #

hotfix: revert version number in build.gradle and reausable-android-build action

---

src/assets/icon/shared/start.svg
src/assets/images/github.png
src/assets/images/splash-screen/0.svg
src/assets/images/splash-screen/1.svg
src/assets/images/splash-screen/2.svg
src/assets/images/star.svg
src/assets/images/sync.svg
src/assets/logos/PLH.svg
src/assets/logos/Unicef.svg
src/assets/logos/WHO.svg
src/assets/shapes.svg

PR Checklist
As I was playing around with `favicon.png`, I discovered some legacy assets in the code repo under src > assets. This PR is removing the ones that I'm convinced are not used. 
1. Could you confirm I'm not breaking anything by removing these? 
2. Potentially some more images could be removed (remaining ones in screenshot below)

chore: Remove legacy images

---

packages/data-models/deployment.model.ts
src/app/shared/services/seo/seo.service.ts

PR Checklist
Exposes a property for setting the path to a custom favicon icon from a deployment config, `config.favicon_asset`. The path should be relative to the gdrive assets folder, e.g. "images/icons/favicon.svg". (NB, the property is not named "favicon_path", as the values of properties whose names end with "_path" are converted to absolute paths when the deployment config is compiled, which is not desirable here).
If no custom favicon asset is set, then the default is used. This default icon has been changed from the ionic logomark to the IDEMS trefoil knot logomark.
With this feature branch checked out, add the line `config.favicon_asset = "images/icons/favicon.svg"` to `.idems_app/deployments/debug/config.ts` and run `yarn workflow deployment set debug` to compile the config. Now …

feat: expose favicon asset path to deployment config

---

src/app/shared/services/seo/seo.service.ts
src/assets/icon/favicon.png
src/assets/icon/favicon.svg
src/index.html

PR Checklist
Changes the default favicon, which is displayed in browsers when the `config.favicon_asset` value is not overridden as is possible since #2192, from the ionic logo to IDEMS's trefoil knot logomark
Closes #
Browser tab showing the new default favicon:

feat: replace default favicon with IDEMS trefoil

---

.github/workflows/reusable-android-build.yml
documentation/docs/developers/in-app-updates.md
package.json
packages/scripts/src/commands/version.ts

PR Checklist
Targets #2198 
- Updates version script to be callable by `yarn run version` (alongside original `yarn scripts version`)
- Separates versioning for `package.json` and android `build.gradle`, using flags to specify (e.g. `yarn run version --android`)
- Add android build version check using existing value from `build.gradle`
- Adds support to existing version script to directly provide target version, e.g. `yarn run version 1.0.5 --package --android`, which will automatically populate android build and package.json version codes
- Improves regex to ensure android versionCode and versionName are replaced even if string value appears instead of number (e.g. current `*versionCode*` placeholder text)
- Improves version code generator to allow integer values if desired (e.g. `yarn …

refactor: use version script in reusable actions

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
Fix issue where templates rendered from data-items would not detect changes. All template container elements now include a call to mark changes when child content rendered.
I assume the issue is due to some way by which angular cdr limits change detection for child components from a parent with onPush strategy (haven't tracked down source reference for this, just a hunch).
We could also consider moving all components (notably template and container) to onPush strategy as well, although given the potential for highly breaking changes might make more sense to wait until we implement an alternative rendering system.
Issue discussion in #2215:
https://github.com/IDEMSInternational/parenting-app-ui/pull/2215#discussion_r1508967183
Debug sheet: …

fix: data-items cdr

---

src/app/shared/components/template/template-container.component.ts
tsconfig.json

PR Checklist
Fix regression from #2221 where calls to change detection mechanisms fail for popup templates.
The likely reason for this is the changeDetector is being called during service constructor methods, which can happen before the app has had a chance to inject the changeDetector (likely happens after all other constructors). 
This fix defers retrieval until after explicitly required for a template, and changes the `emitDecoratorMetadata` tsconfig setting which has been linked to [similar issues](https://github.com/search?q=emitDecoratorMetadata+repo%3Aangular%2Fangular&type=issues&s=created&o=desc) and removed in default angular starter templates (although I think it now defaults to `false` anyway when using esbuild, but possibly not webpack compiler)
Should check before/after …

fix: cdr injection

---

src/app/shared/components/template/components/navigation-bar/navigation-bar.component.html
src/app/shared/components/template/components/navigation-bar/navigation-bar.component.scss
src/theme/variables.scss

PR Checklist
Reduces the height of the `navigation_bar` component, used in the footer.
In the future, we should expose options to authors to determine the footer height, as in follow-up issue #2225.
NB no deployment currently uses the option of icons and text together for the nav bar, only icons are used.
Closes #2148 
Updated [feat_footer](https://docs.google.com/spreadsheets/d/10iy1Vq-pfD2ERBX6xY66-GY87B8_srAnBKz9hOpRYIo/edit#gid=960980632) template:
|--------|-------|
|   <img width="300" alt="Screenshot 2024-03-07 at 14 13 45" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/74bdceda-7581-4cf7-9ff1-34faa3c05d52">    | <img width="300" alt="Screenshot 2024-03-07 at 14 28 36" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/ …

style: reduce footer nav bar height

---

src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss

PR Checklist
Adds a drop-shadow effect to the clickable items that appear within the radio button grid component, to match those of the radio group component.
This effect is hardcoded and editable at the theme level, as opposed to being exposed as an authorable parameter on the component.
Closes #2231
[comp_radio_button_grid](https://docs.google.com/spreadsheets/d/1yHLQHxZQuxs34gBU-ny95ZWs9e8-HybC4IAeFxwpcVw/edit#gid=569531329) template
|-------|-------|
| <img width="300" alt="Screenshot 2024-03-12 at 15 25 25" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/ea460e8c-3b9d-40ee-ac3e-9e3916fed5b4"> | <img width="300" alt="Screenshot 2024-03-12 at 15 22 00" src="https://github.com/IDEMSInternational/parenting-app-ui/assets/64838927/6bdd1b38-77d2 …

style: add drop-shadow to radio button grid component items

---

src/app/shared/components/header/header.component.html
src/app/shared/components/header/header.component.scss

PR Checklist
Follow up to #2216. As pointed out in [this comment](https://github.com/IDEMSInternational/parenting-app-ui/pull/2216#issuecomment-1986181000), when the header colour is `none`, the icons and text in the header should appear in the primary app colour.
Closes #
With deployment config:
```js
config.app_config.APP_HEADER_DEFAULTS.colour = "none";
```
With deployment config:
```js
config.app_config.APP_HEADER_DEFAULTS.colour = "none";
config.app_config.APP_HEADER_DEFAULTS.variant = "compact";
```

style: use primary colour for icons and text in header when header colour is 'none'

---

packages/@idemsInternational/env-replace/.gitignore
packages/@idemsInternational/env-replace/README.md
packages/@idemsInternational/env-replace/package.json
packages/@idemsInternational/env-replace/src/index.spec.ts
packages/@idemsInternational/env-replace/src/index.ts
packages/@idemsInternational/env-replace/test/child/.template.env
packages/@idemsInternational/env-replace/test/test_basic.template.json
packages/@idemsInternational/env-replace/tsconfig.json
packages/@idemsInternational/env-replace/tsconfig.spec.json
yarn.lock

PR Checklist
- Create new `env-replace` workspace used to manage utility methods for future template file replacement
- Add core `replaceFiles` method used to rewrite `.template` files using global environment variables
- Add basic testing suite and tests
Whilst drafting a PR to populate android and ios template files I realised the code was quickly becoming unmanageable as there are various combinations of files to convert at different times with variables read from multiple places (e.g. Android config has about 5 file replacements but some need to leave templated strings in whilst others need to replace).
To reduce complexity I've moved the core replacement utility into its own workspace, and will make a follow-up pr to call specific methods from it as required. 
The utility is designed …

feat: env-replace workspace

---

packages/data-models/deployment.model.ts

PR Checklist
Previously, all deployment configs for remote repos needed to specify a config value for `app_data.output_path`, namely `"./app_data"`. Now that all deployments have associated remote repos, the default value should be updated so that such configs no longer need to specify the value explicitly.
Closes #

chore: update default app data output path to reflect remote repos

---

packages/scripts/src/tasks/providers/android.ts

PR Checklist
Fix issue where android workflow would try to populate firebase templates
Should be able to successfully run the android workflow command with any deployment set that is configured for android
```sh
yarn workflow android
```
Closes #

fix: android workflow variables

---

.github/workflows/reusable-deploy-web-preview.yml

updates deploy preview action to take in hosting site to allow for content repos to post to multiple sites. This allows a released version on firebase and a development version. This will not affect PR release hosting.

Update web preview action to take in different hosting sites

---

ios/App/App.xcodeproj/project.template.pbxproj
ios/App/App/PrivacyInfo.xcprivacy

PR Checklist
Follows on from [this discussion on mattermost](https://chat.idems.international/all/pl/zfsp4cyeufgpx8uwk3p3tpf5nr).
We received the following notification from Apple:
> ITMS-91053: Missing API declaration - Your app’s code in the “Formando Conciencia” file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryFileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: …

Feat: add ios privacy manifest

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss

PR Checklist
Inconsistencies have been noticed to the way different browsers handle toggle element nested inside button for `comp_button` template. This is likely due to different ways the `position: absolute` property of the rendered children span is interpreted (this should be nearest element that has relative positioning, it appears chrome stops if it doesn't find an element when reaching shadow-dom parent component whilst webkit continues further up dom root).
This PR explicitly sets relative positioning on the button container element to ensure children are rendered with correct positioning
As the bug has only been noticed on ios/safari browser, testing on windows should be done via the playwright test framework, accessing the underlying webkit browser
```
npx playwright install
npx …
```

fix: button child layout positioning

---

packages/data-models/functions.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
src/app/feature/campaign/campaign.service.ts

PR Checklist
Code tidying of function that generates parser lists of dynamic dependencies. This should not change the format of output data, but instead tidies up some of the recursion logic to improve type-safety of return
The changes should only impact sheets when synced. I've updated the flowParser cache version which should force all sheets to re-sync. 
Assuming the code logic is working as expected there shouldn't be any changes to synced content
Closes #

Refactor: extract dynamic fields

---

.prettierignore
.prettierrc
package.json
packages/api/package.json
src/theme/themes/default.scss
src/theme/themes/pfr.scss
yarn.lock

PR Checklist
Upgrade the version of the `prettier` package. This resolves an issue wh (see [changelog](https://github.com/prettier/prettier/blob/main/CHANGELOG.md#do-not-add-trailing-comma-for-grouped-scss-comments-15217-by-auvred)).
Either on the master branch, or on this PR branch before running `yarn install`, run `yarn prettier --write src/theme/themes/pfr.scss` to run prettier on the `pfr.scss` file. In source control, you should see that an additional comma has been added at the end of the commented out line 51.
Now with this PR branch checked out, run `yarn install` to update your prettier version, then run `yarn prettier --write src/theme/themes/pfr.scss` again. No changes should be made to the file.
Closes #

chore: upgrade prettier package version

---

packages/shared/src/models/appStringEvaluator/appStringEvaluator.spec.ts
packages/shared/src/models/appStringEvaluator/appStringEvaluator.ts
packages/shared/src/models/dataPipe/operators/appendColumns.spec.ts
packages/shared/src/models/dataPipe/operators/appendColumns.ts
packages/shared/src/utils/string-utils.spec.ts
packages/shared/src/utils/string-utils.ts

PR Checklist
Targets branch of pr #2307
- add generic `parseStringValue` string util and tests to cover conversion of string to boolean, number, null or undefined
- update `appStringEvaluator` to no longer parse boolean strings, instead applying new method only to `appendColumns` operator
I couldn't decide between making the conversion more specific to the `appendColumns` operator or generally to the `appStringEvaluator`, but in the end felt keeping it more specific for now might be better as fewer potential knock-ons and can consider making more general in a follow-up PR if useful.
Closes #

refactor: data-pipe parse string

---

packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/shared/src/models/appStringEvaluator/appStringEvaluator.spec.ts
packages/shared/src/models/appStringEvaluator/appStringEvaluator.ts
packages/shared/src/models/dataPipe/operators/appendColumns.spec.ts

PR Checklist
Fixes an issue where values of data list columns added via the data pipe `append_columns` operation would not be parsed as boolean values as expected when the value is a boolean string (`"TRUE"`, `"false"` etc.)
Incorporates #2308:
- add generic `parseStringValue` string util and tests to cover conversion of string to boolean, number, null or undefined
Run `yarn workspace shared test` and ensure tests are passing as expected:
With this PR's branch checked out, and assuming https://github.com/IDEMSInternational/app-debug-content/pull/66 has been merged, set the active deployment to `debug`. Run `yarn workflow sync_sheets` and `yarn workflow repo open` to inspect the differences. There should just be one changed file, `app_data/sheets/data_list/generated/example_pipe_appended.js …

fix: data pipe append_columns operation can handle boolean strings

---

src/app/shared/components/template/components/data-items/data-items.component.spec.ts
src/app/shared/components/template/components/data-items/data-items.component.ts

PR Checklist
Fixes an issue where `set_item` and `set_items` actions would not function as expected when the row was deeply nested within an item loop, e.g. within a `display_group` component inside an item loop.
This was due to the `setItemContext` meta only being applied to actions within the top-level `action_list` inside the items loop.
Issue identified in [this mattermost thread](https://chat.idems.international/all/pl/spto5y6f53b4xfm1k6p8x91dpc).
See new [debug_data_items_actions](https://docs.google.com/spreadsheets/d/1HvJOcbYGtrkPxwkPp8lvNW63ngsvworzz_jEUo5Swe0/edit#gid=1007541292) component. The buttons on all actions now function as expected – on `master`, the buttons in the second items loop, nested inside `display_group`s, do not trigger the action correctly and an error is …

fix: set_item actions nested inside item loop

---

src/app/shared/components/template/components/button/button.component.scss

PR Checklist
Fixes an issue where the background of the button component with `variant: card` applied would turn transparent when scrolled off screen and back again.
This is a frustratingly simple solution to an issue that cause some headaches: the card variant of the button component had an extra drop-shadow filter applied, in addition to the `box-shadow` applied to the ionic button component. Removing this additional drop-shadow fixes the issue.
Before I removed this filter, the behaviour was very strange (I've added some [brief notes](https://github.com/IDEMSInternational/parenting-app-ui/issues/2287#issuecomment-2077349271) to #2287 in case they're useful in future). I think there is possibly a genuine bug that could be reported to ionic (or even Apple), along the lines of "Setting …

fix: ios button card style issue

---

src/app/shared/components/template/components/data-items/data-items.component.ts
src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

PR Checklist
As documented in #2311, item rows within a `data-items` loop are sorted according to their ID value by default. Whilst we do have a `sort` operation that can be applied to the items via the parameter list of the data-items component, which can be used to sort the list based on some property of the items, there is currently no way to reference the original order of the items in the data list.
This PR makes it the default that data-items render in the order that matches the original data list.
Closes #2311
Template [debug_data_items_order](https://docs.google.com/spreadsheets/d/1HvJOcbYGtrkPxwkPp8lvNW63ngsvworzz_jEUo5Swe0/edit#gid=1681985300), reading from [debug_data_list_order](https://docs.google.com/spreadsheets/d/1HvJOcbYGtrkPxwkPp8lvNW63ngsvworzz_jEUo5Swe0/edit#gid=2755997 …

fix: data items are sorted according to original order by default

---

packages/data-models/appConfig.ts
src/app/app.component.html
src/app/app.component.ts
src/app/shared/components/template/services/template-translate.service.ts

PR Checklist
Adds minimal support for right-to-left languages. As identified in #2254, there are likely to be further changes required to address issues with the app when in RTL "mode" (the changes go beyond just the appearance of text). These could be added as follow-ups following user testing with someone who understands the expected behaviour of an RTL app.
The metadata for a language (currently just a boolean value for `rtl`, but could be expanded to include other properties in future) can be set at the level of the deployment config. For example, the debug deployment config has been updated in https://github.com/IDEMSInternational/app-debug-content/pull/69 to support an RTL language with the name "en_rtl" (the language can be set via the template …

feat: add support for RTL languages

---

packages/api/package.json
packages/api/src/db/index.ts
packages/server/docker/docker-compose.yml

PR Checklist
- Bump API version to `1.5.1`
- Fix issue where local api connection failing (SSL not enabled locally)
The updates have already been deployed to the server along with updates from #2296, so this PR is more just for reference.
It should now at least be possible to check the updates from #2296 on a live server (if using a deployment that has user backup/restore and been recently updated to include code)
I'm assuming the reason now that errors were being seen is either changes to the auto-update on postgres (pinned as `v13` but could have included in minor patch), or to the API packages themselves (been a while since we've pushed server changes and remember a few non-deployed from #2270
The error message seen was `no pg_hba.conf entry for host` (with various ip/db name …

Server/updates 1.5.0

---

src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

Add support for storing data-items with underscore properties (previously rejected by rxdb regex)
PR Checklist
- Update `dynamic-data` service to support using data lists that include `_` prefixed fields (e.g. `_translations`)
- Add tests
I looked at initially adding a new prefix to all `_` prefixed fields and then extracting back out but it seemed a little more efficient to just combine in a single top-level property. The only downside to doing things this way (that I'm aware of) is losing the rxdb ability to query on the field, although given these are mostly computed metadata fields I don't think that's overly useful anyways.
I've only added handling for populating the `_` fields as part of initial data list read, and not as part of dynamic data write operations. This means that …

fix: data-items underscore properties

---

packages/shared/src/models/appStringEvaluator/appStringEvaluator.spec.ts
src/app/shared/components/template/components/data-items/data-items.component.ts
src/app/shared/components/template/processors/item.ts
src/app/shared/components/template/services/instance/template-row.service.ts
src/app/shared/components/template/services/template-variables.service.ts

PR Checklist
**TODO**
Add support for using dynamic values within the parameter list of `items` and `data_items` components. E.g.
```
filter: @item.number < @local.test_value
filter: @item.string === @local.some_string
```
Should confirm if passing tests cases from [example_items_pipe_2](https://docs.google.com/spreadsheets/d/1n82prWaYx-HWKW0ibxv-sO_Vuw9WxvuNLRJ_jI_WXtk/edit#gid=1871410965) (see current output in screenshot below)
I expect this won't solve the issue in https://github.com/IDEMSInternational/parenting-app-ui/issues/2303 (but could be tested). If confirmed not working should probably handle in a follow-up instead of this PR
Worth testing against both `items` and `data_items` syntax to test if working as expected. The fix did have to change a couple parts of the items code …

Fix: item parameter_list dynamic context

---

packages/shared/src/models/dataPipe/operators/filter.spec.ts
packages/shared/src/models/dataPipe/operators/merge.spec.ts
packages/shared/src/models/dataPipe/operators/merge.ts

PR Checklist
The data pipe `merge` fails and throws an unhandled error in the case that no `input_source` is provided. This PR handles that case by throwing a custom error in that case. 
Also tidies some of the pre-existing data pipe operator tests (thanks, @chrismclarke).
#2341 also suggests the existence of another possible issue to do with applying the merge operator to data lists that contain nested JSON data. I think it is sensible to handle this case as a follow-up if it does persist after applying the changes of this PR. In that case, a new debug sheet that exhibits the broken behaviour would be required.
See [example_data_pipe_merge](https://docs.google.com/spreadsheets/d/1imxKEBQ31qpdu7NeXuH3UyK88G_G1jitLdw9CRZ9ZIY/edit#gid=751466229). Run a sync and ensure no errors are thrown, …

fix: data pipe merge operator handles case of no input source

---

.github/workflows/documentation-deploy.yml

PR Checklist
The documentation site currently redeploys any time there is a push to master branch, and uses the latest commit from the mkdocs-deploy github action.
It appears that recent commits to the action have broken deploy [Example failed action](https://github.com/IDEMSInternational/open-app-builder/actions/runs/9667038054), so this PR simply pins the version of the mkdocs-deploy action to a previous working commit.
I've manually triggered the docs deploy from this branch and confirm passing: 
[example passed action](https://github.com/IDEMSInternational/open-app-builder/actions/runs/9667166110)
This is a short term workaround, it might be worth pinning to a more defined/stable version in the future (although [release cycle](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/relea …

Fix: docs deploy action

---

README.md
documentation/docs/developers/deployments.md
documentation/docs/index.md

PR Checklist
- Updates README to specify recommended Node version, and for general clarity
- Mirrors changes to README in external docs intro page, `index.md` (this had become out of sync with the README)
- Restructures "Deployments" docs page to put "Import Existing" section at the top
- This is by far the most commonly relevant section for readers of the docs
Closes #

docs: updates to README and Deployments section

---

cspell.config.yml
src/app/shared/components/template/components/progress-path/progress-path.component.html
src/app/shared/components/template/components/progress-path/progress-path.component.scss
src/app/shared/components/template/components/progress-path/progress-path.component.ts
src/app/shared/components/template/components/task-card/task-card.component.scss
src/theme/themes/default.scss
src/theme/themes/early_family_math.scss
src/theme/themes/pfr.scss
src/theme/themes/plh_facilitator_mx.scss
src/theme/themes/professional.scss

Targets branch for PR #2370
- Recreate svg element to avoid use of nested groups and transformations. 
- Make SVG generation dynamic (to support variable width and height)
- Fix inheritance of stroke color. 
- Remove path-line-weight variable (as image distorts when using different weight)
The changes started as minor edits to SVG to inherit color properly and remove unnecessary grouping, however I noticed that the SVG I was working from had been altered since to include more vertical space, which had knock-ons of breaking various layout aspects. It didn't help that the SVG itself had viewbox for one static size and rendering at another (auto-scaling), whitespace within the SVG element and then deeply nested fixed sizes for components that it had to adjust for (e.g task card text content) …

review: task-journey-component

---

packages/scripts/src/commands/app-data/convert/index.ts
packages/shared/src/utils/logging/file-logger.ts
packages/shared/src/utils/logging/memory-logger.ts

PR Checklist
fix regression from #2376  where script warnings were not been logged correctly (due to typo on `warn` vs `warning`)
Closes #
**Example issue**

fix: warning log invalid naming

---

cspell.config.yml
packages/data-models/deployment.model.ts
packages/scripts/src/tasks/providers/appData.ts
packages/scripts/tsconfig.json
packages/shared/src/utils/file-utils.ts
src/app/shared/services/deployment/deployment.service.spec.ts
src/app/shared/services/deployment/deployment.service.ts
src/test/utils.ts

PR Checklist
Currently full deployment configuration is made available to the app at build time by directly importing the `activeDeployment.json` file into the angular `environment.ts` file. A few issues with this include:
- Large amount of developer-specific code exposed (e.g. local workspace directories)
- Deployment config changes require full app rebuild to run (actively running angular compiler)
- Potentially sensitive data exposed (e.g. config tokens)
This PR is the first of two designed to dynamically import minimally required deployment config during runtime.
**Main Changes**
- Create separate type definitions for deployment config variables used at runtime
- Update scripts to populate runtime config to file and 
- Create service and tests to enable access to runtime config
Can …

Feat: runtime deployment config

---

.github/workflows/deprecated/deployment-hosting.yml
.github/workflows/deprecated/sourcemaps-upload.yml
.github/workflows/reusable-android-build.yml
.github/workflows/reusable-android-release.yml
.github/workflows/reusable-appetize.yml
.github/workflows/reusable-deploy-pr-preview.yml
.github/workflows/reusable-deploy-web-preview.yml
.github/workflows/test-preview.yml
.github/workflows/test-visual.yml
.github/workflows/web-build.yml
packages/actions/templates/app-build/template.yml
packages/actions/templates/deploy-firebase/template.yml
packages/actions/templates/pr-preview-firebase/template.yml
src/app/shared/components/template/components/data-items/data-items.component.spec.ts

PR Checklist
- Make consistent the version of upload/download artifacts across all actions
Testing done by triggering actions from Temp content repo PR https://github.com/IDEMSInternational/app-debug-content/pull/82 
**Before**
Example [Failed Action](https://github.com/IDEMSInternational/app-debug-content/actions/runs/10820932897/job/30022078872?pr=82) when targeting `master` branch from debug deployment content repo
**After**
Example [Passing Action](https://github.com/IDEMSInternational/app-debug-content/actions/runs/10820985652/job/30022481832) when targeting this branch
There is some confusion as various actions use both `upload-artifact` and `upload-pages-artifact`. The `upload-pages-artifact` is simply a lightweight wrapper around `upload-artifact` (some minor modifications to …

Chore: update action artifact versions

---

packages/scripts/src/commands/app-data/postProcess/assets.ts

PR Checklist
Fix regression introduced by #2423 
Default app_config variables are no longer loaded until runtime, however there appears to be an instance where scripts that post-process assets expect to access the app_config theme variables. This would results in any deployments without themes defined being unable to compile
This fix simply adds fallback empty array for cases where deployment doesn't specify themes. An more robust solution should probably include improving type-definitions to asset config is only partial during script processing, and to move the theme config to the top-level deployment config - however likely not worth the time involved right now. 
Closes #

fix: scripts app_config

---

.github/workflows/documentation-deploy.yml

Should prevent the open-app-builder.com site from going down every time there is a commit to the master branch.
The 'documentation-deploy' flow overwrites everything in the 'gh-pages' branch every time there is a push to the master branch - that is why files like CNAME go missing, which causes downtime. There is a setting on the action that generates the site that should set a custom domain name, and this has been set appropriately.
Upgraded the checkout action. Removed commented code and todo.

Set custom domain for documentation site

---

.idems_app/deployments/local/.gitignore
packages/data-models/flowTypes.ts
packages/scripts/src/commands/app-data/convert/cacheStrategy/jsonFile.mock.ts
packages/scripts/src/commands/app-data/convert/cacheStrategy/jsonFile.ts
packages/scripts/src/commands/app-data/convert/convert.spec.ts
packages/scripts/src/commands/app-data/convert/processors/base.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.spec.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.spec.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.spec.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.ts
packages/scripts/src/commands/app-data/postProcess/sheets.ts
packages/shared/src/models/templatedData/templatedData.spec.ts
packages/shared/src/models/templatedData/templatedData.ts

PR Checklist
Fix issue where outputs generated from data_pipe or generator operations aren't processed (if output as data_pipe or generator operators)
As the changes impact the main parser, should ideally test updates against a content repo that has recently been synced to see if there is any content diffs. The only expected change is that `data_pipe` flows should no longer be stored within the generated content (these have already been used to generate the populated data_lists, so aren't useful to the app runtime)
I create a content sync for the latest sheets from master branch on the debug repo at:
https://github.com/IDEMSInternational/app-debug-content/pull/88
Then, using this branch see updated content sync at:
https://github.com/IDEMSInternational/app-debug-content/pull/89
Should …

Fix: generator chained flows

---

packages/scripts/src/commands/deployment/set.ts
packages/scripts/src/commands/deployment/utils.ts
packages/workflows/src/deployment.workflows.ts

PR Checklist
Fix issue where setting config for first time (e.g CI actions) fails to include encrypted deployment values.
Should be able to confirm if supabase config loaded in test-preview action
The reason deployment config would be loaded before decrypt was to handle the case where the name of the deployment isn't known (in which case the deployment set action prompts name input). I've updated the workflow to add a standalone step to handle ensuring a name is provided (either as a command arg or through prompt), and using that can force deployment to be decrypted before compiling the full deployment json.
Closes #

fix: encrypted deployment set

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Fixes an issue where the stroke colour of vector layers would override authored values when a scale fill was applied
Closes #

fix(map): scale colour no longer overrides stroke value for vector layers

---

.husky/pre-commit

PR Checklist
I've recently started using [FNM](https://github.com/Schniz/fnm) to manage node version. There seems to be a slight issue when trying to create commits from vscode, where it doesn't detect the environment variables correctly for node/yarn, which are used as part of our git pre-commit hook (calls the `lint-staged` package)
This PR adds explicit support in the hook to re-evaluate the environment for fnm if using.
The only thing to check is that as a user not using fnm that you can still add commit and trigger the pre-commit hook without issue. So recommend taking this branch and just attempting to add a commit to it. Note that the commits only trigger the `lint-staged` command when applying the actual commit (not just stage), so would need to commit via vscode interactive …

chore: update husky hook

---

packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/shared/src/models/appDataEvaluator/appDataEvaluator.spec.ts
packages/shared/src/models/appDataEvaluator/appDataEvaluator.ts
packages/shared/src/utils/delimiters.spec.ts
packages/shared/src/utils/delimiters.ts

PR Checklist
- Fix regression from #2461 where expressions like `{@row.id}_suffix` would be evaluated as JS (-> `undefined`) instead of templated data (-> `some_id_suffix`) for `data_pipe` append operator
- Fix issue where evaluation would break when using multiple different variable types, e.g. `@row.number > @local.number`
- Update tests to capture new cases
Should confirm if fixes issue originally outlined in [mattermost thread](https://chat.idems.international/all/pl/krgfwnfdi7yfi8xrd7o53bwhoh)
Should be able to confirm tests passed from github action. 
As for possible knock-ons, it's only the `appendColumns` operator that uses the code, so changes should show up in parser for any given deployment repo that has example content.
Closes #
_If useful, provide screenshot or capture to …

fix: app-data evaluator

---

packages/shared/src/utils/file-utils.ts
packages/shared/src/utils/object-utils.spec.ts
packages/shared/src/utils/object-utils.ts

PR Checklist
Move the `arrayToHashmap` shared util from `file-utils` to `object-utils`. This is required as the `file-utils` contain node-specific logic, and so can't import from the file in web (issues with webpack polyfills for `os`). 
The `object-utils` doesn't contain any node-specific code and makes more sense as the location for this method. 
Also adds basic tests.
I've checked for any files that import the method from `file-utils` however all import from the top-level `shared` so shouldn't have any issues with the moved method.
Closes #

chore: move arrayToHashmap function

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

PR Checklist
Upgrades the Android Gradle Plugin from version 8.3.1 to 8.7.1 in the android build files.
I was prompted to run this upgrade via Android Studio's AGP Upgrade Assistant when opening the project in Android Studio.
From the [release notes](https://developer.android.com/build/releases/gradle-plugin), I believe devs will need to upgrade their Android Studio to the latest version ("Ladybird").

chore(android): upgrade gradle

---

src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
- Moves the legend to display under the map (previously it displayed on right hand side)
- Makes the legend scale bars be displayed horizontally (previously vertically)
Closes https://github.com/IDEMSInternational/conflict-forecast-content/issues/9
[comp_map](https://docs.google.com/spreadsheets/d/1KgLTrFhqZdGhcSk6Zt0KQoy2mYf7NCqhCJz_zS0KEYw/edit?gid=569531329#gid=569531329) template:

chore: make legend scales horizontal; move legend to under map

---

android/app/capacitor.build.gradle
android/app/src/main/assets/capacitor.plugins.json
android/capacitor.settings.gradle
ios/App/Podfile
ios/App/Podfile.lock
package.json
packages/data-models/flowTypes.ts
src/app/app.component.ts
src/app/shared/services/screen-orientation/screen-orientation.service.spec.ts
src/app/shared/services/screen-orientation/screen-orientation.service.ts
yarn.lock

PR Checklist
Adds a new template action to lock screen orientation to either portrait or landscape.
- Action ID: `screen_orientation`
- Possible arguments: `portrait` | `landscape`
- Example: `click | screen_orientation: portrait;`
This is a step towards resolving #2114. As mentioned in [a comment on that issue](https://github.com/IDEMSInternational/open-app-builder/issues/2114#issuecomment-1791018473), we would like to be able to set the screen orientation of a given template at the level of metadata on templates, and have the orientation set automatically upon navigation. However, it made sense to me to break this down into steps: this PR adds the base functionality to lock the screen orientation, exposed to an action, and a follow-up will handle setting the orientation automatically on …

feat: screen_orientation action

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds a new map layer property, `scale_slider`, which takes a boolean value (default `false`). When true, the scale in the legend gets two slidable handles added, which can be used to set a range to filter which features are visible on the map. See demo below
Closes #
Updated [comp_map_layer_data](https://docs.google.com/spreadsheets/d/1KgLTrFhqZdGhcSk6Zt0KQoy2mYf7NCqhCJz_zS0KEYw/edit?gid=1695224840#gid=1695224840):
https://github.com/user-attachments/assets/09e30683-141d-4c9e-a26b-4b3e7a54f8d5

feat: add slider/filter fucntionality, toggled on for a given layer via the scale_slider property

---

packages/scripts/src/tasks/providers/git.ts

PR Checklist
- add progress indicator for `deployment import` workflow
This adds gray text below the cloning console log and updates to provide overall status
Import a deployment repo to see updates. E.g. 
```sh
yarn workflow deployment import https://github.com/ParentingForLifelongHealth/plh-kids-app-kw-content.git
```
It turns out `simple-git` hass support for progress callbacks that can be used for logging updates. The clone action provides processed, total and an overall percentage value.
Closes #
**Example - progress updating**

feat: deployment clone progress

---

packages/scripts/src/commands/app-data/convert/index.ts
packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts

PR Checklist
Just to confirm whether this fixes the issues seen at deployment repo. It might also be good to check whether the amount of whitespace this introduces is desirable or not (e.g. there's quite a few instances of `\r\r` which now becomes `\n\n` and should result in a full empty line - but worth checking it looks as expected)
I tried to identify the root cause but was unsuccessful. Interestingly when trying to open sheets locally excel automatically replaces the `\r`, but definitely does appear to be in the google sheets so I'm guessing somehow coming from copy-paste operations elsewhere. In any case seems sensible to me to just replacee with a newline character.
Closes #2499

chore: fix linebreaks

---

src/app/shared/components/template/components/text-bubble/text-bubble.component.html
src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
src/app/shared/components/template/components/text/text.component.html
src/app/shared/components/template/components/text/text.component.scss
src/app/shared/components/template/components/text/text.component.ts
src/theme/_typography.scss

PR Checklist
Text passed to as the `value` to the `text-bubble` component is now parsed as markdown, in line with other components like `text`.
It makes sense to me that when we're rendering text as a standard paragraph, we should be calling an instance of the `text` component itself rather than replicating its logic. This PR implements a pattern, previously used in #2460, of
instantiating the text component and passing in an ad-hoc template row.
One issue with this is that we can't directly modify the styles of the child `text` component from the parent component (without using `ViewEncapsulation.none`, `::ng-deep` etc.), making it tricky to apply a minor styling change to the text as it appears in context. Some styling changes can be achieved through the `text` component's existing API, …

fix: text bubble component handles markdown

---

src/app/shared/components/template/components/accordion/accordion.component.scss
src/app/shared/components/template/components/audio/audio.component.scss
src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/layout/accordion-section/accordion-section.component.scss
src/app/shared/components/template/components/layout/display-grid/display-grid.component.scss
src/app/shared/components/template/components/number-selector/number-selector.component.scss
src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss
src/app/shared/components/template/components/radio-group/radio-group.component.scss
src/app/shared/components/template/components/slider/slider.component.scss
src/app/shared/components/template/components/text-area/text-area.component.scss
src/app/shared/components/template/components/text-box/text-box.component.scss
src/app/shared/components/template/components/tile-component/tile-component.component.scss
src/app/shared/components/template/components/timer/timer.component.scss
src/global.scss
src/theme/deployment/components/_display-group.scss
src/theme/deployment/components/_modal.scss
src/theme/themes/default.scss
src/theme/themes/early_family_math.scss
src/theme/themes/pfr.scss
src/theme/themes/plh_facilitator_mx.scss
src/theme/themes/plh_kids_kw/_index.scss
src/theme/themes/professional.scss
src/theme/themes/utils/generate-theme.scss

PR Checklist
- `professional` theme: Makes the default border colour grey/gray
- `plh_kids_kw` theme: Makes the default border colour grey/gray
- Minor refactor to default border styles: remove unused global style variables
There should be no changes to component styles for the `default` theme. Below is a comprehensive list of all the components that make use of the variable that has been updated by this PR. If you come across any components that you would expect to be changed in accordance with #2426 but are not affected by this PR, then they do not use the default variable and can be refactored as part of this PR or as a follow-up.
@FaithDaka I've applied these changes to the `plh_kids_kw` theme (see #2426 for justification). I imagine that any custom styling you've been applying as …

style: make border default gray for professional and plh_kids_kw themes

---

packages/data-models/flowTypes.ts
src/app/feature/template/template.page.html
src/app/feature/template/template.page.ts
src/app/shared/components/template/services/template-metadata.service.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/services/screen-orientation/screen-orientation.service.ts
src/app/shared/utils/angular.utils.ts

PR Checklist
Targets branch of #2501 
Main changes:
- Simplify template-metadata service logic using signals
- Tracked currently locked orientation and only change if different value provided
- Add support for unlocking orientation
- Add angular utility function for route subscription
I've also updated the demo template:
https://docs.google.com/spreadsheets/d/13KnDdmBicPDZaWFNnlIck7WNMLlM02HjD0-_UiqZ4z8/edit?gid=569531329#gid=569531329
For now I've kept enabled on web when not in production (local testing) to see clearly the console logs when orientation changes are being called, let me know if things work as expected to you and we can remove before pushing into production.
I haven't tested on a physical device, but using logs to see if appears to trigger as expected
Closes #
_If useful, …

Review: 2501

---

src/app/shared/components/template/components/layout/display-group/display-group.component.scss
src/app/shared/components/template/components/layout/display-group/display-group.component.ts

PR Checklist
Adds a new variant for the display group: `box_white`. The border colour and weight are determined by the new theme variables introduced in #2503, so currently the border colour is "primary" for the `default` theme and light grey for the `professional` theme. One knock-on is that the border weight of the other `box_*` variants is also now thinner for the professional theme, in line with the theme-level styling introduced in #2503.
Closes #2437 
| Theme: default | Theme: professional |
|------|------|
| <img width="280" alt="Screenshot 2024-11-07 at 12 54 08" src="https://github.com/user-attachments/assets/ae612aa7-2c4a-4601-80d4-9ce0cf2f9108"> | <img width="280" alt="Screenshot 2024-11-07 at 12 58 22" src="https://github.com/user-attachments/assets/a6ab1167-e155-4669-a69b-2620 …

feat: display group variant box white

---

src/app/app.component.ts
src/app/feature/template/template.page.html
src/app/feature/template/template.page.ts
src/app/shared/components/template/services/instance/template-process.service.ts
src/app/shared/components/template/services/template-metadata.service.spec.ts
src/app/shared/components/template/services/template-metadata.service.ts
src/app/shared/components/template/services/template-nav.service.ts
src/app/shared/components/template/services/template.service.ts
src/app/shared/components/template/template-container.component.ts
src/app/shared/services/screen-orientation/screen-orientation.service.ts

PR Checklist
Introduces a new template metadata parameter, `orientation`, which can be set on a particular template through the `parameter_list` on within the content list. Setting `orientation: landscape` for a given template forces the screen orientation to be set to landscape when that template is being displayed. Setting `orientation: portrait` for a given template forces the screen orientation to be set to portrait when that template is being displayed. For all other templates, the screen orientation is unlocked, meaning that it should match the user's native screen orientation settings.
As there is no screen orientation API on web, this feature can only be tested on native devices.
See appetize builds:
- [Android](https://appetize.io/apps/android/international.idems.debug_app)
- …

Feat: landscape mode

---

src/app/shared/services/seo/seo.service.ts

PR Checklist
Fix issue where seo service fails to initialise if deployment does not have any app header config set
The reason for the issue is that the seo-service was importing app config via the deployment config (which only includes config overrides), instead of app config service (which includes full merged config). So when accessing nested properties it would throw an error if no APP_HEADER_DEFAULTS had been overwritten.
Most deployments typically have app header overrides so would mostly go unnoticed, it was only when running the local deployment that the error was noticed. Searching the codebase this is the only service that I could see that tried to access app config in this way.
Closes #
**Source code search for other services accessing app_config** - only case is a comment in …

fix: seo service config

---

packages/data-models/flowTypes.ts
packages/shared/src/utils/object-utils.ts
src/app/shared/components/template/services/instance/template-action.registry.ts
src/app/shared/components/template/services/template-field.service.spec.ts
src/app/shared/services/data/app-data.service.spec.ts
src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
src/app/shared/services/dynamic-data/dynamic-data.actions.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.actions.ts
src/app/shared/services/dynamic-data/dynamic-data.service.mock.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts
src/app/shared/services/dynamic-data/dynamic-data.utils.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.utils.ts
src/app/shared/services/error-handler/error-handler.service.mock.spec.ts
src/app/shared/services/error-handler/error-handler.service.spec.ts

PR Checklist
Add actions to support data_list manipulation from outside of `data_items` context loops, originally discussed in [RFC 21. Data Actions](https://docs.google.com/document/d/1qJi9Nk--CFwGTPMn9ksmOgoVq_dnXrTMlN9a_i7kUyY/edit?tab=t.0#heading=h.93c0t57zwuyv)
This PR originally started in #2454, but has been separated out. This does not include any changes to `set_item` syntax or `data_items` loop handling (will be addressed in follow-ups)
**Main Changes**
- add `set_data` action
- add `reset_data` action 
- add tests
**Additional Changes**
- Create new [feat_data_actions](https://docs.google.com/spreadsheets/d/1nREviZhw2HG1YQy6KA1S9PU4Q36RRVHdwSYf3TMbduk/edit?gid=434509236#gid=434509236) sheet for demo
- Minor test tidying
**Future Follow-ups**
**Syntax**   
See examples in sheet …

Feat: set data action standalone

---

packages/components/plh/index.ts
packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.html
packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.spec.ts
packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.ts
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
`plh_module_list_item` created and styled. Corresponding debug sheet: [Link](https://docs.google.com/spreadsheets/d/1Tq8Ib_ZcJsABW9U9XbQxgnmtv_uayXk28DXoa94j1aE/edit?usp=sharing)
`plh_module_list_item` component with the following `parameter_list`:
- `module_image_asset`: The image attached to the module item.
- `text_transform` (optional): The format of the text on the module item. Default null- `nav_image_asset`: For the navigation icon
- `locked_image_asset` (optional): For the locked icon
- `is_locked` (optional): The boolean that marks the module as locked or unlocked
Closes #2534
| Design    | LTR Style |  RTL  Style |
|---------------|-------|-------------|
| <img width="250" src="https://github.com/user-attachments/assets/f473598d-e5b0-4d41-9911-b7fc1d382ced">      | …

Kuwait Theme: Module List Item Component

---

packages/data-models/flowTypes.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_list.parser.spec.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_list.parser.ts
packages/scripts/test/helpers/utils.ts

PR Checklist
Add methods to parser to add a `_metadata` column to data_lists and track data types of non-string columns
This is designed to improve on the type infer methods used in #2513 (can update post-merge), so that `set_data` operations can correctly use the expected column data types. 
**Use**
There are 2 methods now included to infer data types within the parser
1. If the author includes an `@metadata` row can manually specify `type: number/boolean` within the corresponding column cell.
2. Find first non-empty data entry and use type from that (will check all rows if required).
Note - only `number`  or `boolean`  types need to be specified as assume `string` by default, an if using nested `object` types these will automatically be detected when creating the data_list (columns …

Feat: data list metadata

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
- Moves legend (scale bars) position to display over map
- Expose parameter to display map layer selection in dropdown
- Param `controls_style`, possible values `dropdown` (new default), `list` (old default)
- fixes an issue where sometimes the map layer controls list would not render
TODO: handle multiple dropdowns to display multiple "layer groups"
Closes #
https://github.com/user-attachments/assets/77156526-4293-47cb-85bf-5449fc764e8d

feat(map): legend displayed over map; exposes option to display map layer controls in dropdown

---

packages/components/demo/index.ts
packages/components/plh/index.ts
src/app/shared/components/template/template.module.ts

PR Checklist
Fixes an issue where the components defined in the PLH components package (`packages/components/plh`) were not available in the app. On `master`, these components defined in packages cannot be instantiated from templates (no error is thrown, the component row is just not rendered), and do not appear in the list available on the `/component` page.
Based on when this issue was first observed (by @FaithDaka a couple of days ago), this is likely a regression introduced by #2520. I haven't been able to track down why those changes would cause the issue, but it seems to be likely due to some circular imports between our different module and component declaration files that is resolved by this PR.
I've marked is at a `hotfix` because it seems to move us in the wrong direction with …

hotfix: plh components loading from external package

---

src/app/shared/utils/utils.ts

PR Checklist
Fixes an issue with the `getBooleanParamFromTemplateRow()` method, used when a component parameter has a boolean value, would not parse the correct value in the case that the parameter value was provided via a local variable (#2560)
Closes #2560, #2561 
[comp_plh_module_list_item](https://docs.google.com/spreadsheets/d/1Tq8Ib_ZcJsABW9U9XbQxgnmtv_uayXk28DXoa94j1aE/edit?gid=569531329#gid=569531329) displaying as corrected, in contrast to screenshot on the issue:

fix: get boolean param from template row

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Fixes an issue where filtering through the legend slider would not work for layers consisting of Point geometry.
Closes #

fix: filtering on Point layers

---

src/app/shared/components/template/template-container.component.ts

PR Checklist
Alt proposal for #2583, with additional fix to container input error logs
The `templatename` input has been changed from `input.required` to regular `input` as it's not set when calling headless. 
Ideally this could be reverted back in the future if we can decouple the render/processing logic from the container component to allow it to truly be called in a headless way (added TODO comment in the code). 
Closes #2583

fix: template container error alt

---

src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts

PR Checklist
#2558 added variants to the `task_progress_bar` component, however it didn't handle the case of setting the variant to the default (`"bar"`) when the component is instantiated within a parent component (e.g. the `task_card`). This PR resolves that.
Closes #2590

fix: progress-bar-component post-2558

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.html
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Includes styling of Navigation and Module `comp_round_button` under Kuwait theme. [Link](https://docs.google.com/spreadsheets/d/161GZue4jkQNJzyfYvMWesMp2vwvbkJgpNqkDlVIGJDw/edit?usp=sharing)
Refactors the `rounf_button` component to use varaints. `style` is still supported, but should be considered legacy.
Round Button with `navigation` variant can be used for **back** buttons and now appears as:
Round Button with `module` variant can be used for module navigation and now appears as:
Round Button with `no-background` variant:
Closes #2578
| variant  | Design        | Kuwait Theme    |
|----------- |---------------|----------|
| `module` | <img width="250" src="https://github.com/user-attachments/assets/1442d5ac-c36a-49ae-a934-34073a433462"> | <img width="180" …

Kuwait Theme: Round Button Variants

---

src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
src/app/shared/components/template/components/index.ts
src/app/shared/components/template/components/layout/display-group/display-group.component.html
src/app/shared/components/template/components/layout/display-group/display-group.component.scss
src/app/shared/components/template/components/layout/display-group/display-group.component.ts
src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.html
src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.ts
src/app/shared/components/template/components/manifest.ts

PR Checklist
Targets branch of #2564 
Rework to move all sticky display logic to separate component
To confirm if still functions identically to target branch pr
This creates a child `display-group-sticky` component that is rendered within the main `display-group` component, with the sole purpose of tracking content height for use in the included padding offsets.
Most of the code was copy-pasted, although I wasn't sure whether it still needed all the logic to calculate additional padding, given that it is now still rendered inside the main display-group component (I think maybe not). I also wasn't sure if the CSS z-index that references nav-stacks is required (commented out, but should be removed if not needed).
Although it declares a new `display_group_sticky` component, that is only to …

refactor: display group sticky component

---

src/app/shared/components/template/components/audio/audio.component.ts

PR Checklist
Fix issue where audio component would accidentally close any parent nav_stack it is presented in
Alt fix to #2603
The only other component that I could see that interacts directly with modal logic is the `combo_box`, so it might also be worth investigating if similar problems appear there, although it looks like the logic is setup to dismiss from inside the created modal so I think shouldn't be able to accidentally close the wrong one. 
Closes #2603
https://github.com/user-attachments/assets/924fa60a-b7cb-4c66-952f-dea2a29c1938

fix: audio modal close trigger

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Previously, the `excluded_features_color` was being applied inversely, i.e. to those features that are included in the filter. This PR fixes that.
Closes #

fix: filtered/excluded colours reversed

---

src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.ts

PR Checklist
Refactors the logic for setting the fixed position of the display group with the `sticky` parameter set.
The #2564 SCSS implementation of of setting the `top`/`bottom` position of the sticky header element used the `ng-reflect-*` property, see [this file](https://github.com/IDEMSInternational/open-app-builder/pull/2564/files#diff-492b1201007ae8d64daf79c9373c48770dc5bbfb6c950a00aefe397915c99fa1). For whatever reason, these CSS rules were not being applied as expected on the web preview of the KW deployment (I couldn't replicate this locally). In this screenshot, the element was not having the styling `top: 0` applied:
This PR uses a different approach, recommended on the [linked thread](https://github.com/angular/angular/issues/53888), to achieve the same result of applying …

fix: sticky header position

---

src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.html
src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.ts
src/app/shared/components/template/components/combo-box/combo-box.component.ts
src/app/shared/components/template/components/data-items/data-items.service.ts
src/app/shared/utils/utils.ts

PR Checklist
Add support for providing a `data_items` list to a combo_box to generate answer options
See updated example in [comp_combo_box](https://docs.google.com/spreadsheets/d/1uIkaMlDjoDN7uTpHkSeEQ6Yp-4ehX9IrBQMrolpfjQc/edit?gid=569531329#gid=569531329)
Note - if passing a data_list it is expected that the list has columns for `name` and `text`, same as hardcoded lists. The `data_items` loop should not contain any child rows
If using `data_items` list there is not quite the same safeguards in place as with some of the hardcoded lists (e.g. filtering out incomplete item rows) - this is due to the assumption that data_lists are less prone to authoring error than long lists of hardcoded variables. 
There isn't currently any integration between the system used by combo_boxes to add …

feat: add support for combo_box child data_items

---

src/app/shared/components/template/components/layout/popup/popup.component.html
src/app/shared/components/template/components/layout/popup/popup.component.ts

PR Checklist
Fixes a bug where templates launched as part of app launch actions would not have the app's RTL config applied to them.
The template [debug_launch_actions](https://docs.google.com/spreadsheets/d/1zofHkaZ9NMcUgM7U7fPXxclVw4qXN8crHkXcQf-HCr8/edit?gid=1541644091#gid=1541644091) has been updated such that launch actions can be tested from the debug deployment. On first app launch, you will be prompted to select a language. This will not apply on subsequent app launches, until the app data is reset.
On `master`, run a sync to pull the latest changes to [debug_launch_actions](https://docs.google.com/spreadsheets/d/1zofHkaZ9NMcUgM7U7fPXxclVw4qXN8crHkXcQf-HCr8/edit?gid=1541644091#gid=1541644091). Run the app and confirm that the bug documented in #2615 is present for the language …

fix: rtl language config is applied to app launch templates

---

packages/data-models/appConfig.ts
packages/data-models/skin.model.ts
src/app/shared/components/header/header.component.ts
src/app/shared/services/skin/skin.service.spec.ts
src/app/shared/utils/angular.utils.ts

PR Checklist
Header config removes override for functions `should_show_menu_button`, `should_show_back_button` and `should_minimize_app_on_back`. All of these functions were by default linked to whether on app home page or not, and typically not overridden by deployments. Now that there are more specific parameters such as `back_button.hidden: true` that can be used to handle specific functionality
NOTE - probably good to mention this in the target PR if merging, although I'm not aware of any deployments that modify these functions
Targets branch of #2631 
- Remove some app header config defaults where they can be implied (`undefined` as falsy default)
- Refactor menu/back button home-specific side-effects to be included in component code (remove authoring override)
Closes #
_If useful, …

refactor: header defaults and functions

---

src/app/shared/components/template/components/layout/display-group/display-group.component.scss

PR Checklist
Fixes an issue where the spacing between components within a display group with `style: row` (the default style) would not appropriately handle the app language direction being RTL.
As well as the two templates referenced in #2621, the issue can be observed in the debug template [example_dg](https://docs.google.com/spreadsheets/d/1i6Th92RAkGfardxSJdJYWVoMtTkaNr-Xn2kIHDvtQoQ/edit?gid=1745157248#gid=1745157248). On `master`, setting the app language to RTL (via the template `feature_rtl_language`), observe that the button has a margin applied to its left that should be applied to its right:
This is resolved on this PR branch:
Closes #2621 
Templates referenced in #2621:
[debug_dg_button](https://docs.google.com/spreadsheets/d/19qLXy1PF6BOH9GZ-qpcZJ3-bOfxXAgj7J8H67Nfp9MM/edit?gid …

fix: display group spacing RTL support

---

src/app/shared/components/template/components/audio/audio.component.html

PR Checklist
The audio component handles cases where the app language direction is right-to-left (RTL). This is achieved by enforcing the player controls to be displayed in their default LTR styling, regardless of app language direction, in accordance with the description of #2617.
Closes #2617
| Theme | Language direction: LTR | Language direction: RTL |
|-----|-----|-----|
| Default | <img width="180" alt="Screenshot 2024-12-28 at 12 14 58" src="https://github.com/user-attachments/assets/b13c896c-1e33-4446-bbd9-a51ce2f067fd" /> | <img width="180" alt="Screenshot 2024-12-28 at 12 14 43" src="https://github.com/user-attachments/assets/a8429b0d-40b6-4f2e-80cf-c2ebac240028" /> |
| `plh_kids_kw` | <img width="180" alt="Screenshot 2024-12-28 at 12 16 08" …

chore: audio component handles RTL languages (LTR player controls enforced)

---

src/app/shared/components/template/components/title/title.component.ts

PR Checklist
Fixes an issue where text within the title component would remain left-aligned when the app language direction was RTL, resulting a noticeable inconsistency when said text wrapped over multiple lines.
Closes #2640 
[comp_title](https://docs.google.com/spreadsheets/d/1pBCI7KkNNtF9sQAs_l_hcdjjFfdjC4vEL4jvF5sNk9c/edit?gid=569531329#gid=569531329):
| Language direction: LTR | Language direction: RTL |
|-----|-----|
| <img width="180" alt="Screenshot 2024-12-28 at 12 42 47" src="https://github.com/user-attachments/assets/89f73418-e7b6-462b-82aa-8bb9c9e59c5a" /> | <img width="180" alt="Screenshot 2024-12-28 at 12 43 10" src="https://github.com/user-attachments/assets/3edd1889-3e1b-4b78-9884-8ed7b4c22199" /> |
| <img width="180" alt="Screenshot 2024-12-28 at 12 43 43" …

fix: text wrapping in title component for RTL languages

---

src/app/shared/components/template/components/layout/popup/popup.component.html
src/app/shared/components/template/components/layout/popup/popup.component.scss

PR Checklist
Handles repositioning the pop-up close button when the app language direction is RTL. Changes applied to both fullscreen and non-fullscreen pop-ups.
Closes #2618
Pop-ups launched from [example_pop_ups](https://docs.google.com/spreadsheets/d/1K9JZ9Glnj73CFJmpfGIRa5dRA2TBxSsJmaguV6GL8Pc/edit?gid=402992224#gid=402992224):

fix: pop-up close button position for RTL languages

---

packages/data-models/flowTypes.ts
packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
packages/scripts/src/commands/app-data/convert/utils/app-data-action.utils.ts
src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/data-items/data-items.component.ts
src/app/shared/components/template/components/data-items/data-items.service.spec.ts
src/app/shared/components/template/components/data-items/data-items.service.ts

PR Checklist
Add a custom `data_changed` action trigger that updates in sync with data_items loops.
This can be used to set local or field values depending on data queries
**Follow-up Tasks**
The action list is defined in the normal way, with the exception that the `@items` variable will contain the value of the associated item list
| type             | value    | action_list                                                 | parameter_list          |
|------------------|----------|-------------------------------------------------------------|-------------------------|
| begin_data_items | my_items | data_changed \| set_local : total_completed : @items.length | filter: @item.completed |
| end_data_items   |          |                                                             | …

feat: data_items triggered actions

---

packages/api/package.json
packages/api/spec-export.json
packages/api/src/app.module.ts
packages/api/src/db/index.ts
packages/api/src/db/migrations/008-auth-user-column.ts
packages/api/src/endpoints/app_users/app_user.model.ts
packages/api/src/endpoints/auth_users/auth_user.controller.ts
packages/api/src/endpoints/auth_users/index.ts
packages/api/src/endpoints/index.ts
packages/data-models/fields.ts
packages/server/docker/docker-compose.yml
src/app/shared/services/auth/auth.service.ts
src/app/shared/services/server/server.service.ts

PR Checklist
The contact field `_app_auth_user` has been renamed to `auth_user_id` and is no longer formatted as json but instead just an id. I'm not sure if this protected field was included in any templates beyond debug ones. It has been updated in [example_google_auth](https://docs.google.com/spreadsheets/d/12xo0ewDN0bbeVrs3klWd9J8DkFQLTCYX1zhGWnovqIo/edit?gid=579616705#gid=579616705)
The current `app_user_id` remains unchanged
Adds an `auth_users` endpoint to the server that can be used to retrieve a user by a given `auth_user_id`. It also creates an explicit `auth_user_id` column within the `app_users` table to make it more efficient to retrieve (instead of looking at contact_fields)
Updates server sync code to include `auth_user_id` when available
These server updates are required …

Feat!: Auth user db sync

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Sets the text alignment in the `combo-box` input field to center by default
Closes #2668

[Bug Fix] Kuwait Theme: Combo box center align text

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/button/button.component.ts
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
- Button component with `variant: card-portrait` now handles `disabled` param
- Previously this param would have no effect on this variant, but now the button will appear faded and will not be clickable
- Custom styling of button component with `variant: card-portrait` for `plh_kids_kw` theme
- Repositions child rows for use as a button in activity library. See example in [comp_button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit?gid=569531329#gid=569531329) below for proposed authoring
While it may make sense to create a new dedicated plh component, minimal changes were needed to the existing button card-portrait variant to achieve the desired result. Note that I've proposed authoring the locked icon and toggle bar both as child …

feat: button card-portrait variant handles disabled param; custom styling of button card-portrait variant for plh_kids_kw theme

---

src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Fixes an issue where the speaker label on the text bubble component would be incorrectly positioned when app language direction is RTL.
Closes #2619
[comp_text_bubble](https://docs.google.com/spreadsheets/d/1Yo8X4TrTW2lzEgusDplAQ-y-JJvQOIqXGNLVON1uvRo/edit?gid=569531329#gid=569531329)
LTR:
RTL:

fix(plh-kids-kw): text-bubble speaker position for RTL language

---

src/app/shared/components/template/components/button/button.component.scss
src/theme/deployment/_overrides.scss
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Makes the alignment of text responsive to language direction (LTR/RTL). In particular this applies to text within the button component, but there may be desirable knock-ons for other components that use the same pattern to align text.
Note that this does not fix the `text_align` parameter on the button component (marked by a very old comment as "to be removed" in the [comp_button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit?gid=569531329#gid=569531329) template)
The text alignment throughout the app is a bit of a mess, with bits of CSS code in various places overriding each other. For now, I've left everything as it is structurally, but replaced relevant instances of `text-align: left` and `text-align: right` with `text-align: …

fix: make button text alignment responsive to language direction

---

ios/App/Podfile
ios/App/Podfile.lock

PR Checklist
Updates the `FirebaseCore` cocoapod to its latest version, which in turn updates various other dependencies.
Release notes [here](https://firebase.google.com/support/release-notes/ios#11.0.0).
Closes #
Resolves this issue:

chore(ios): update FirebaseCore cocoapods

---

src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
src/theme/variables.scss

PR Checklist
Fixes an issue where the top of a nav-stack could be cut off when accessing the app via Safari on iOS.
iOS appetize [link](https://appetize.io/app/ios/international.idems.debug-app?device=iphone14pro&osVersion=16.2).
Closes #2680 
I've included screenshots of the fullscreen pop-up component, as this is the other component that makes use of the CSS property that has been updated in this PR. The behaviour of fullscreen pop-ups is unchanged as shown here.
|   | Native app | Safari |
|---|---|---|
| nav-stack | <img width="200" alt="nav-stack native app" src="https://github.com/user-attachments/assets/8e8eba89-4596-472e-a7f4-2be167bae261" /> | <img width="200" alt="nav-stack safari" src="https://github.com/user-attachments/assets/ee9ff753-67b2-495f-ae8c-5ef33e82db64" /> |
| …

fix: ios browser nav-stack height

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss

PR Checklist
For the `round_button` component with `style: no-background`, the colour of the source icon is not altered. Previously, the icon would be recoloured to contrast with colour of the background of the button – as there is no background colour in this case, the colour of the icon should not be altered.
Closes #
Updated [comp_round_button](https://docs.google.com/spreadsheets/d/161GZue4jkQNJzyfYvMWesMp2vwvbkJgpNqkDlVIGJDw/edit?gid=569531329#gid=569531329):

style: round icon button icon colour

---

src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
src/app/shared/components/template/components/layout/popup/popup.component.scss

PR Checklist
Fixes an issue where the content of fullscreen pop-ups may not all be visible when accessing the web app via Safari on iOS. Whilst I haven't been able to recreate this issue more generally, it's possible that it was also occurring when accessing the native iOS app, which should also be fixed by these changes.
As these changes refactor some of the styling for pop-ups in general, we should test every pop-up type for every platform. I have attempted this in the videos embedded below. In each case, we should be ensuring that all the content is visible (particularly relevant for scrolling content) and that all the spacing looks correct – e.g. the space around the non-fullscreen pop-up element; the positioning of the close button.
Pop-up types:
- Available via …

fix: iOS fullscreen popups

---

src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Fixes #2690 (a regression issue following #2688). The changes in #2688 caused the `plh_kids_kw`-specific "completion modal" component to display off the top of the screen. 
Closes #2690
Completion modal launched from [example_pop_ups](https://docs.google.com/spreadsheets/d/1K9JZ9Glnj73CFJmpfGIRa5dRA2TBxSsJmaguV6GL8Pc/edit?gid=402992224#gid=402992224).
Desktop browser:
iOS native:
iOS Safari:

fix: completion modal

---

package.json
src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts
src/app/shared/components/template/template.module.ts
yarn.lock

PR Checklist
- The scale in the legend now displays labelled "steps"/"ticks"/"increments"
- Configurable via the new layer property, `scale_increment`
- Should be a number representing the size of each increment. E.g. if `scale_min = 0` and `scale_max = 100`, then setting `scale_increment = 5` will divide the scale into 20 different sections, with gaps of 5 between each
- If no value is provided, the default is to divide the total by 10 to render 10 increments
- New layer property: `scale_slider_snap`
- Default `false`
- if `true`, the slider will snap to the increment markers
- Refactors to use a different library to handle the interactive slider functionality
- Previously this used the ionic [ion-range](https://ionicframework.com/docs/api/range) component, however this does not support …

feat(map): scale increments; change scale slider library

---

src/app/app.component.ts
src/app/shared/components/template/components/layout/display-group/display-group.component.scss
src/app/shared/components/template/utils/render-utils.spec.ts
src/app/shared/components/template/utils/render-utils.ts
src/theme/deployment/_overrides.scss

PR Checklist
- Fixes an issue where the `app_config` property `LAYOUT.page_padding` would not be correctly interpreted as a shorthand CSS property for setting the padding on multiple sides, e.g. `24px 0` or `24px 32px 10px 24px`
- Updates `inline_padding` variant of the display group component
- Previously, the size of the padding was read from the same ionic padding variables that are set from the app config level, meaning that if the page padding was set to 0, the padding applied to the `inline_padding` variant would also be 0. 
- This variant was originally introduced for convenience when dealing with sticky display groups, which ignore page padding by default (see #2589).
- In theory, this variant shouldn't be necessary as it should accomplish the same thing as a single line of custom …

fix: app config page padding property is properly interpreted as shorthand

---

.github/workflows/reusable-deploy-pr-preview.yml

PR Checklist
As mentioned in [GH Actions Docs](https://docs.github.com/en/actions/sharing-automations/reusing-workflows), secrets can only be inherited by reusable workflows if originating from the same github org. 
>Workflows that call reusable workflows in the same organization or enterprise can use the inherit keyword to implicitly pass the secrets.
```yml
jobs:
call-workflow-passing-data:
uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
with:
config-path: .github/labeler.yml
secrets: inherit
```
As such when calling actions such as the pr-preview, the optional `DEPLOYMENT_PRIVATE_KEY` variable would not be passed if the workflow were triggered from a content repo outside of the IDEMSInternational org
This PR makes the required secrets explicit for reusable …

chore: make pr preview action secrets explicit

---

.github/workflows/reusable-android-build.yml
.github/workflows/reusable-deploy-web-gh-pages.yml
.github/workflows/reusable-deploy-web-preview.yml

PR Checklist
Follow up to #2721, see that PR for a full explanation.
Makes the `DEPLOYMENT_PRIVATE_KEY` secret explicit for all workflows that call the `reusable-app-build` workflow.
Closes #

chore(ci): make deployment private key secret explicit in all relevant reusable workflows

---

.github/workflows/reusable-android-release.yml
.github/workflows/reusable-appetize.yml
.github/workflows/reusable-content-sync.yml

PR Checklist
Follow-up to #2722. Covers three additional workflows that were missed in that PR that don't directly call the the `reusable-app-build` workflow but make use of the `DEPLOYMENT_PRIVATE_KEY` secret.
Closes #

chore(ci): make deployment private key secret explicit in second-order workflows

---

src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
src/theme/themes/plh_facilitator_mx/_index.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
- Reduces size of `round_button` component to closer resemble figma designs
- Further reduces size of `navigation` variant of `round_button` component to closer resemble figma designs
Closes https://github.com/ParentingForLifelongHealth/plh-facilitator-app-mx-content/issues/114
In combination with authoring changes (no specific content PR to point to as multiple changes are being worked on simultaneously):
- Makes `group_add.svg` icon white rather than dark
- (Renamed existing asset -> "group_add_dark.svg" but didn't remove, updated `group_add.svg` to be white)
- Added custom 12px margin-bottom to dg on [edit_parent_group](https://docs.google.com/spreadsheets/d/14iUeYWUHIly3tyz61Wgz_tlPUVAqkI8aXFnlsrUA1ZY/edit?gid=1081278670#gid=1081278670) and …

style: MX theme: reduce size of round-button component; further reduce size of navigation button

---

src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
PR branch accidentally builds on the PR branch of #2740, so that PR should be merged first. 
Fixes styling of markdown inside accordion component for `plh_facilitator_mx` theme, in line with #2699.
Closes #
[comp_accordion](https://docs.google.com/spreadsheets/d/1He3nS_qWno-_kJrzizhcUdC1vONKWaluPzC1rr-RfSw/edit?gid=569531329#gid=569531329):
|---|---|
| <img width="220" alt="Screenshot 2025-01-22 at 11 10 27" src="https://github.com/user-attachments/assets/a2454154-84dd-4976-a381-57ab8515959f" /> | <img width="220" alt="Screenshot 2025-01-22 at 11 10 07" src="https://github.com/user-attachments/assets/83f64074-f89e-457d-a069-d907097df193" /> |

Fix: MX accordion markdown styling

---

src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.scss
src/app/shared/components/template/components/combo-box/combo-box.component.ts

PR Checklist
Adds a new disabled state for the combo-box component. 
- The combo-box is disabled if manually set to disabled via a new `disabled` parameter (i.e. `disabled = true`
- Else the combo-box is automatically disabled if no answer list is provided, or if the answer list is empty.
- When the combo-box is disabled, it will display any text provided to a new parameter, `disabled_text`
Also fixes an issue where the displayed text in the combo box may not update correctly to reflect the value.
Every configuration of the combo-box should be tested to ensure no functionality is broken. The [comp_combo_box](https://docs.google.com/spreadsheets/d/1uIkaMlDjoDN7uTpHkSeEQ6Yp-4ehX9IrBQMrolpfjQc/edit?gid=569531329#gid=569531329) component was quite confusing, I've updated it and am satisfied …

feat: combo-box component disabled state

---

src/app/shared/components/template/components/data-items/data-items.service.spec.ts
src/app/shared/components/template/components/data-items/data-items.service.ts
src/app/shared/components/template/services/template-translate.service.spec.ts
src/app/shared/components/template/services/template-translate.service.ts
src/app/shared/services/data/app-data.service.mock.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

PR Checklist
- Fix issue where data_items loops do not translate text from source data_lists
- Update tests
The default template parser has various fallback methods that would attempt to translate data_list columns regardless of whether they had been marked for translation or not. This PR does not change default/legacy behaviour, but does add specific method for use within data_items loops that expects any data_list to include `my_column::eng` syntax for any translatable columns in the data_list 
See video below for [debug_translation_data_items](https://docs.google.com/spreadsheets/d/1Bwh8eb2B43AAlDND4q0b4E-EXgnd6IRjmIFIf1Jbk1c/edit?gid=650194570#gid=650194570) sheet
Have also manually checked `comp_data_items` still behaving as expected, but would also be good to check any deployments …

Fix: data items translations

---

src/app/shared/components/template/components/button/button.component.html

PR Checklist
Fixes an issue for MX and KW themes where the `button` with `card-portrait` variant would incorrectly apply styling as if child rows were present (regression from #2675)
Closes #
|---|---|
| <img width="240" alt="Screenshot 2025-01-24 at 18 16 48" src="https://github.com/user-attachments/assets/d6eee192-c2fa-4907-9588-a48b178d1fce" /> | <img width="240" alt="Screenshot 2025-01-24 at 18 36 36" src="https://github.com/user-attachments/assets/83b8b812-e720-49a5-bfc2-08e478d91512" /> |

fix: button card-portrait styling

---

src/app/shared/components/template/components/base.ts
src/app/shared/components/template/components/combo-box/combo-box.component.html
src/app/shared/components/template/components/combo-box/combo-box.component.ts

PR Checklist
Follow-up to #2733, which I merged too hastily.
- Ensures the dropdown variant of the combo-box component emits "changed" as expected
- Removes some unused code
@ChrisMarsh82 could you test that this works with your MX use-case?
@esmeetewinkel could you test the general combo box functionality for all variations included in [comp_combo_box](https://docs.google.com/spreadsheets/d/1uIkaMlDjoDN7uTpHkSeEQ6Yp-4ehX9IrBQMrolpfjQc/edit?gid=569531329#gid=569531329), to ensure I've not missed anything in testing the changes across this PR and #2733)
Closes #
Updated [comp_combo_box](https://docs.google.com/spreadsheets/d/1uIkaMlDjoDN7uTpHkSeEQ6Yp-4ehX9IrBQMrolpfjQc/edit?gid=569531329#gid=569531329):

fix: combo-box dropdown variant emits 'changed' as expected

---

src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Adds a new variant for the button component, only for the `plh_facilitator_mx` theme: `faq`
Originally I had thought it might make sense to make this a generally available variant of the button. However, due to the way that the `plh_facilitator_mx` theme level overrides are applied, it is difficult to add new styling from the component level that overrides them.
Closes https://github.com/ParentingForLifelongHealth/plh-facilitator-app-mx-content/issues/141
[comp_button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit?gid=569531329#gid=569531329)

feat: MX theme button variant 'faq'

---

src/app/shared/components/template/components/base.ts

PR Checklist
Fixes a bug where the value of the text-box would sometimes not update as expected.
This is quite a difficult issue to create a debug template for, since really we want direct access to the component's `value()` signal to check that it updates correctly, which is how I was debugging as a dev. I think it should suffice to confirm that the issue as observed is now resolved.
Technically, this PR resolves a general issue with components' `value()` computed property not always being updated as expected via the `setValue()` component method (#2706 is relevant).
In debugging the issue, I observed that the component's `value()` computed property would not update as expected, even though `rowSignal().value`, on which it depends, was updating as expected. I observed that removing the …

fix: text box value bug

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.ts

PR Checklist
Targets branch of #2757
- Update parameter_list handling to update on change (not just init)
- Replace mapped params with signal
Confirm example/test cases targetted in original PR branch still work
Looking through button code and proposed changes I didn't think it fully made sense to make just one single param responsive whilst keeping the others as is. 
I think moving forward it would make sense to move away from `ngOnInit` methods to process parameter_list variables, and instead use signals to compute component params whenever the author `parameter_list()` signal updates. 
This is a little awkward as for whatever reason we have a bunch of utility methods that take the entire row before parsing parameter list values to specific types (e.g. `getStringParameterFromRow`), but …

Refactor: button disabled dynamic

---

src/app/shared/components/template/components/button/button.component.html
src/app/shared/components/template/components/button/button.component.ts

PR Checklist
Enables the button component’s disabled/enabled state to dynamically reflect updates to the `disabled` parameter.
Additionally, this PR removes support within the button component for the row-level `disabled` property, which is considered deprecated. See follow-up #2761 to roll out this change to other components.
As we've discussed previously (for example, [this comment thread](https://github.com/IDEMSInternational/open-app-builder/pull/2493#issuecomment-2446930347) on #2493), it would make sense to embrace angular signals more fundamentally in how we handle component parameters. This PR doesn't make any progress towards achieving this more generally, but ultimately it would likely make sense for all our authorable parameters to be parsed to computed/signal values that react …

feat: make 'disabled' parameter of button component dynamic

---

.github/workflows/test-visual-generate.yml
.github/workflows/test-visual.yml
packages/test-e2e/package.json
packages/test-visual/.env.sample
packages/test-visual/package.json
packages/test-visual/src/commands/download.ts
packages/test-visual/src/commands/generate.ts
packages/test-visual/src/config/index.ts
packages/test-visual/src/config/test.ts
packages/test-visual/src/helpers/github.ts
packages/test-visual/src/index.ts
packages/test-visual/src/utils/index.ts
packages/test-visual/tsconfig.json
yarn.lock

PR Checklist
The visual screenshots test has been failing since last December, due to incompatibilities introduced with automated updates to github actions runner and outdated code dependencies
This PR aims to fix both the code to generate screenshots (applied on merge to master) and compare function (triggered by pr's labelled with `test - visual`)
**Potential Follow-ups**
Once merged authors should start being able to use the `test - visual` action again to compare against master branc
Previously base screenshots would be generated on every merge to master branch. This isn't ideal as it ends up generating lots of screenshots that are never used for comparison, and also fails to take into account authoring changes which may be the cause of differences (author changes wouldn't trigger new …

Fix: ci screenshots

---

src/app/shared/components/template/components/layout/display-group/display-group.component.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss

PR Checklist
Adds a new variant to the display group to handle the use case referenced [here](https://github.com/ParentingForLifelongHealth/plh-facilitator-app-mx-content/issues/140#issuecomment-2616147702).
This variant, `box_secondary_alt`, applies a background colour, border and corner radius to the group, in line with the existing `box_*` variants. Additional styling for the use case should be handled through other means, see example below.
Corresponding debug content PR: https://github.com/IDEMSInternational/app-debug-content/pull/142
I wasn't sure how best to handle this use case. While defining the styling itself is relatively trivial, there is a decision about how much styling to include in a variant vs relying on additional authored styling, to achieve a balance between …

style: new display group variant for MX button use case

---

src/app/shared/components/template/components/data-items/data-items.service.ts
src/app/shared/components/template/services/instance/template-action.service.spec.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/components/template/services/instance/template-process.service.ts
src/app/shared/components/template/services/instance/template-row.service.ts

PR Checklist
Fix regression introduced by #2767 where data_items no longer passed outer local variables to inner items
Minimal reproduction of issue available at [comp_data_items_debug_2](https://docs.google.com/spreadsheets/d/1khGTrDekzqDQyW1r2x0ADqknanrlkmhOz1RRzhP6-7c/edit?gid=1510685976#gid=1510685976)
Should be broken on master but fixed in branch. Should also confirm original issue resolved
I should have been a bit more careful when adding the additional variable that is meant to stay in sync with the templateRowMap, not realising that the rowMap was updated in multiple places not just the main processor. As part of this fix I checked the codebase for anywhere the `templateRowMap` was updated and tried to ensure the related `templateRowMapValues` was also.
A better solution might …

hotfix: data-items local variables

---

src/app/shared/components/template/components/map/map.component.html
src/app/shared/components/template/components/map/map.component.scss
src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Adds a new layer property, `scale_id`, used to identify layers which should share the same scale.
If no scale ID is provided, the layer functions as before, and any associated scale is rendered for that layer when it is visible. If multiple layers share a `scale_id`, then only one scale associated to these layers will ever be shown, and filters applied using that scale slider will apply to all such layers with that scale ID. Authors should ensure that each layer with a given scale ID has the same configuration for its scale (e.g. `scale_max`, `scale_min`, `scale_increment`, `scale_title` etc.)
The implementation is quite hacky. Currently, different scales are shown for different layers with the same `scale_id` (up to a maximum of 1) depending on which layers are visible, but …

feat(map): support multiple layers sharing the same scale

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
Follow up to #2782: fixes issue where filter would not be applied when making a layer visible that belongs to a scale ID group with a filter currently active
Closes #

fix(map): handle showing new layer with same scale_id

---

.github/workflows/web-build.yml
package.json
src/app/feature/theme/services/theme.service.mock.spec.ts
src/app/feature/theme/services/theme.service.spec.ts
src/app/shared/components/template/components/data-items/data-items.service.spec.ts
src/app/shared/components/template/services/template-calc.service.mock.spec.ts
src/app/shared/components/template/services/template-calc.service.spec.ts
src/app/shared/components/template/services/template-calc.service.ts
src/app/shared/components/template/services/template-variables.service.spec.ts
src/app/shared/services/app-events/app-events.service.mock.spec.ts
src/app/shared/services/data/app-data-variable.service.spec.ts
src/app/shared/services/data/app-data.service.spec.ts
src/app/shared/services/data/data-evaluation.service.mock.spec.ts
src/app/shared/services/db/db.service.mock.spec.ts
src/app/shared/services/db/db.service.spec.ts
src/app/shared/services/local-storage/local-storage.service.mock.spec.ts
src/app/shared/services/local-storage/local-storage.service.spec.ts
src/app/shared/services/local-storage/local-storage.service.ts
src/app/shared/services/skin/skin.service.spec.ts
src/app/shared/services/userMeta/userMeta.service.ts
yarn.lock

PR Checklist
- Add `ng test` to ci test workflow to ensure all ng tests are passing before merge
- Change mock db to use dexie with `fake-indexeddb` instead of stubbing methods
- Alter various mock test suites to extend base instead of implementing partial
Can see code changes in files ending `.ts` (but not `.spec.ts`) - I've never found a good way to filter these out but there's not too many changed files to quickly look through and check
The spec test code updates are non-breaking (full set of spec tests included in PR testing)
I've slowly been migrating most mock services to extend original services instead of partially implementing methods as I feel like in the long term this will be less prone to breakage and better at catching knock-on issues when core methods changed on underlying …

Chore: ng test ci and mock updates

---

src/app/shared/components/template/components/map/map.component.ts

PR Checklist
When applying a filter based on changing the slider values, the values used are now rounded to 2 decimal places (previously 1 decimal place). In the future, the precision should be exposed as layer-level property to authors.
Closes #

chore(map): increase filter precision to 2 decimal places

---

src/app/shared/components/template/services/template-calc.service.mock.spec.ts
src/app/shared/components/template/services/template-calc.service.spec.ts
src/app/shared/components/template/services/template-calc.service.ts

PR Checklist
The `window.calc` accessor has been marked as deprecated, e.g. `@calc(window.calc.pick_random([1,2,3]))`
Any methods available via `window.calc.xxxx` are already available directly, e.g. `@calc(pick_random)`, so use that way instead.
I can't see any examples of this being used in [example_calc](https://docs.google.com/spreadsheets/d/15TccctjzepSPPv9xrLp46fhYldNN0wrho1zA5voTYcg/edit?gid=1595229908#gid=1595229908), so assume this is mostly a legacy behaviour anyways
The only method that should still be accessed via the window is the `date_fns` utility library, e.g. `@calc(window.date_fns.add_days(...))`
Changes merged from #2772 for easier review, a handful of updates to the `template-calc.service` which handles authored `@calc(...)` statements, specifically
Beyond the marked …

refactor!: template-calc service

---

src/app/shared/services/auth/auth.service.ts
src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts
src/app/shared/services/userMeta/userMeta.service.ts

PR Checklist
As part of the work on this PR we need a way to create and expose to author data that has been created as part of internal services (in this case the list of auth profiles available for restoration). 
For convenience, I've kept the same `@data` convention for these internal lists, but used the prefix `app_` to mark as internal, so that the auth service populates an `app_auth_profiles` list that authors can read via `@data.app_auth_profiles`. 
This has the breaking knock-on that means any other lists that an author creates named starting `app_` will not be processed correctly (would be assumed internal and not attempt to load initial data from sheets)
- Add support for data created by internal app services to be exposed to to authors `@data` references (using prefixed `app_` …

Feat!: auth restore data

---

packages/api/package.json
packages/api/src/main.ts
packages/server/docker/docker-compose.yml

PR Checklist
increases the size limit on body payloads posted to API server. This is required to resolve an issue where attempting to sync user data would result in a `413 (Payload Too Large)` response to the POST request to the server.
Solution taken from [this answer](https://stackoverflow.com/a/59978098).
The value of 32mb was chosen to match the `client_max_body_size` as specified in `packages/server/docker/config/nginx/templates/server.conf.template`, but could likely be much lower.
Closes #

server: increase payload size limit

---

src/app/shared/services/auth/auth.service.ts

PR Checklist
Fixes a minor issue where the list of auth profiles available to be restored were not sorted correctly by the `updatedAt` property.
I'm assuming that the original logic was an error as I don't see the significance of the comparison, although I may well be missing something. It's also worth noting that the author can sort the list themselves, see the example of this in the [settings_login](https://docs.google.com/spreadsheets/d/1hy3nSqXZaLjVFRCQgayZjzSMVCX26P3HNuR_KtKjE3c/edit?gid=56143870#gid=56143870) template on the `plh_kids_kw` deployment:
Closes #

fix: auth restore profiles order

---

src/theme/themes/plh_facilitator_mx/_overrides.scss
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Fixes an issue on the `plh_kids_kw` deployment where the lock icon/favourite toggle that displays within the activity button cards within the [activity_library](https://docs.google.com/spreadsheets/d/1V8iYNvVVc0whiZ3p--ulL_93DiOEH_SKwwwSqLX6OE4/edit?gid=0#gid=0) template would not be positioned as expected on iOS.
As this is a minor change, I propose we trust my initial testing and merge. I will publish a build to appetize in anticipation of the next `plh_kids_kw` release, and you can test then @esmeetewinkel 
The issue is seemingly due to the way that webkit browsers (I was able to replicate on my desktop safari browser) handle cascading and inheritance of multiple stylesheets in terms of setting the `top`, `bottom` etc. positioning properties. It seems webkit browsers do …

fix: plh_kids_kw activity lock button position on ios

---

packages/data-models/appConfig.ts
packages/data-models/deployment.model.ts
src/app/shared/components/template/services/instance/template-action.service.ts
src/app/shared/services/db/db-sync.service.ts
src/app/shared/services/server/server.service.ts

PR Checklist
Targets branch of #2822
Refactor server sync frequency to deployment-level API config
The main change here is to move the server sync configuration to deployment-level config instead of runtime, as it makes more sense for this to be a fixed value instead of template-dependent. As mentioned in the target issue, if wanting to block syncing for whatever reason I think we should probably build on top of this with a public method and/or authoring action that can disable sync.
I've also refactored the `db-sync.service` a little to share sync schedule with the `server.service`. I was initially confused why there were two services performing similar tasks, but then remembered the original server service was designed for syncing to the `app_users` table and the db-sync any other table …

Review: app config sync properties

---

.github/workflows/reusable-app-build.yml
.github/workflows/reusable-ios-build.yml
ios/Gemfile

PR Checklist
- Add `reusable-ios-build` action to handle build of ios app
- Improve reusable build action to support custom post-build scripts and artifact upload. This enables triggering things like ios configuration scripts following the app build, so that follow-up runner doesn't have to manage deployment-specific code.
Once this PR is merged similar actions as the one in the debug repo PR can be added to other content repos to generate ios simulator builds. As the action depends on the latest version of the main code repo, the content repo variable for `APP_CODE_BRANCH` will also need to be set to one that includes these merged changes
The action does not (currently) upload automatically to testflight, nor can they generated artifacts be uploaded to the app store (requires follow-up …

feat: reusable-ios-build action

---

packages/components/plh/parent-point-box/parent-point-box.component.scss
packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.scss
src/app/shared/components/template/components/button/button.component.scss
src/app/shared/components/template/components/task-card/task-card.component.scss
src/theme/overrides.ios.scss

PR Checklist
- Fixes an issue with the `plh_module_list_item`, where the component would not display properly on iOS (see https://github.com/ParentingForLifelongHealth/plh-kids-app-kw-content/issues/174).
- Fixes related undocumented issues for some other components:
- `task_card`
- `button` (`card-portrait` variant)
The underlying issue is with the CSS `filter: drop-shadow` on iOS. Similar issues are noted in various places (e.g. [1](https://stackoverflow.com/questions/65801487/drop-shadow-not-working-properly-on-ios-safari), [2](https://www.reddit.com/r/css/comments/bweqdc/safari_bug_css_dropshadow_after_elementhover_issue/)), although not well documented. 
There are two possible workarounds for this issue:
1. Refactor the styling to replace `filter: drop-shadow` with `box-shadow:`
- …

fix: ios visual bugs on elements with drop-shadow

---

src/app/shared/components/template/components/task-card/task-card.component.scss

PR Checklist
Fixes a regression issue introduced by #2842 whereby a task card component with completion status "notStarted" would display a shadow for an invisible progress badge.
Closes #2849
[comp_progress_path](https://docs.google.com/spreadsheets/d/14BBKG07nqUWDmcscdUMv1AKYSWGBUPCNDT-VcSERHyU/edit?gid=569531329#gid=569531329) template:

fix: task card badge not-started

---

packages/data-models/appConfig.ts
src/app/app.component.html
src/app/shared/components/header/header.component.html
src/app/shared/components/header/header.component.scss
src/app/shared/services/app-config/app-config.service.spec.ts
src/app/shared/services/app-config/app-config.service.ts
src/app/shared/services/skin/skin.service.spec.ts

PR Checklist
- Renames some app config properties for consistency. After merge, the new names should be used going forward.
- `APP_FOOTER_DEFAULTS.templateName` -> `APP_FOOTER_DEFAULTS.template`
- `APP_HEADER_DEFAULTS.colour` -> `APP_HEADER_DEFAULTS.background`
- Introduces a way to handle renaming app config properties such as these in such a way as to continue to support deprecated names
There should be no functional changes. 
Test all templates within [feature_app_layout](https://docs.google.com/spreadsheets/d/1Z46gTluTPeffqpiAZMapYo0imm59GU03j0sW9UChvPM/edit?gid=3937162#gid=3937162), e.g. [feat_app_layout_custom_footer](https://docs.google.com/spreadsheets/d/1Z46gTluTPeffqpiAZMapYo0imm59GU03j0sW9UChvPM/edit?gid=569531329#gid=569531329), to ensure header and footer overrides are still …

chore: rename some app config properties; add deprecation migration system

---

packages/data-models/fields.ts
src/app/app.component.ts

PR Checklist
Adds a new protected field to track the platform that the app is currently running on. This is accessible through the `_platform` field, e.g. `@fields._platform`.
This field has three possible values: `"web"`, `"ios"` or `"android"`. These can be used for string comparison, e.g. in a condition on a row: `@fields._platform === "ios"`, to only show that row when the app is running on an ios device.
Note that when running on web, "web" will always be the returned value, even when devtools device mode is set to an android or ios device.
Closes #2870
Demos of [example_protected_fields](https://docs.google.com/spreadsheets/d/1X10C5YWsqJ7NRJp-pSiaYjdAoV4hl5-scvisiBThmq8/edit?gid=460679842#gid=460679842) template (previously called "example_hardcoded_fields")
[appetize …

feat: add 'platform' protected field

---

capacitor.config.template.ts
ios/.gitignore
ios/App/App/App.entitlements
packages/data-models/deployment.model.ts
src/app/shared/services/auth/auth.service.ts
src/app/shared/services/auth/providers/base.auth.ts
src/app/shared/services/auth/providers/firebase.auth.ts

PR Checklist
Enables sign in via Apple using Firebase auth.
To enable the feature for given deployment, additional configuration is required in both the associated project in the Firebase console and the associated app in the Apple Developer console. See Firebase docs, with links to relevant Apple docs, [here](https://firebase.google.com/docs/auth/ios/apple).
- [iOS appetize link](https://appetize.io/app/b_yswli5qmzbdnltj7dmf6pdmhlq?device=iphone14pro&osVersion=16.2&toolbar=true)
- Web funcitonality can be tested by checking out this feature branch, syncing debug content, and running the app locally
- The functionality is not currently working on web preview for me via the web preview for this PR: I get an "unauthorised domain" error, despite having added the URL to the whitelisted …

Feat: apple auth

---

src/app/shared/components/template/services/instance/template-process.service.ts
src/app/shared/components/template/template-container.component.ts

PR Checklist
Fix issue where startup templates would fail to load due to updated way angular checks templates before render (likely following #2900)
When running as a standalone template the signal input isn't actually used, but it appears the angular compiler has gotten more sensitive to the potential of using when not in injection context. So simple workaround is to just pass an injection context to the standalone templates (even if not used)
Now that the container is created in an injection context it's possible to remove the previous workaround for handling effect injection context
Closes #2906

fix: template-injection-context

---

src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts

PR Checklist
**TODO**
Part of #2899 tidying
Fix issue where dynamic data would not delete correctly
The issue is related to the way the state persist methods would compare what is currently stored in the indexeddb vs what is in cache, relying on looking at keys in hashmaps such as `{data_list: {list_1 : {row_1: ...}}}`. 
There main problem was that the comparison only looked one level deep, so would detect if an entire list was added/removed, but not individual rows. So to fix I've refactored to generate a flatter hashmap, where every entried is keyed by a combination of flow_type, list_id and row_id, e.g. `{data_list__list_1__row_1:{...}}`
I don't think this has much impact for current apps as resetting flows to original state still work as expected (would only have been noticed if …

Fix: dynamic data delete

---

src/app/shared/components/template/components/base.ts

PR Checklist
From [mattermost](https://chat.idems.international/all/pl/1zzd7a456inmbkwygpf5d7o5kw) - fix implementing option (1)
---
The issue appears related to the use of rowSignal, which is currently set to only update when the templated row changes, i.e.
```ts
rowSignal = signal<FlowTypes.TemplateRow>(undefined, { equal: isEqual });
```
However, as this is passing reference to local variables which is evaluated in the component itself, e.g. (`@local.some_var`) that means external changes to the local variables do not trigger re-evaluation
So the options are either
1) Remove the isEqual optimisation, which will force reprocessing whenever the parent component re-renders (which happens after every set_field action)
or 
2) Add specific listeners to the data-items service to track …

fix: data items external field

---

src/app/feature/shared-data/shared-data.service.ts
src/app/shared/services/asyncService.base.ts

PR Checklist
Fix issue where shared-data service would attempt to register even when not in use. E.g. shared-data
Confirm that `shared-data` service no longer tries to initialise (which throws error on any deployment without firebase enabled)
Looking at the async service base, it appears that all services were set by default to call their init function after a random delay, with an optional override to call immediately. I think both of these options are somewhat part of legacy code (now pretty much all services explicitly await `ready` calls which in-turn triggers init if not already triggered), however I'm slightly wary of refactoring right now in case of unintended knock-ons
As such I've added a new option to `defer` init, which will explicitly prevent the delayed init being called. …

fix: service init defer

---

src/theme/themes/plh_facilitator_mapa/_overrides.scss
src/theme/themes/plh_facilitator_mx/_overrides.scss
src/theme/themes/plh_kids_kw/_overrides.scss

PR Checklist
Fixes an issue where the icon in the accordion component would appear fully aligned to the end of the element, for themes based on the `plh_kids_kw` theme. This was presumably an unexpected knock-on from #2890.
The themes affected are:
- `plh_kids_kw`
- `plh_facilitator_mx`
- `plh_facilitator_mapa`
As we don't currently have inheritance between these themes, I've just made the minor update manually to each theme.
Closes #2921
Demo of [comp_accordion](https://docs.google.com/spreadsheets/d/1He3nS_qWno-_kJrzizhcUdC1vONKWaluPzC1rr-RfSw/edit?gid=569531329#gid=569531329) for `plh_kids_kw` theme:
| LTR | RTL |
|---|---|
| <img width="640" alt="Screenshot 2025-05-01 at 12 35 04" src="https://github.com/user-attachments/assets/109c8fe0-1e3c-498a-8750-67cc41c5530d" /> | <img …

fix: accordion style for kw-based themes

---

packages/data-models/fields.ts
src/app/app.component.ts

PR Checklist
Adds two new generated fields for `_app_environment` and `_app_hostname` for use in metadata tracking
`_app_environment` will show up either as `development` when running locally, or `production` when running either as native app or web preview. Specifically this value represents the app build process, where a development build is used to run locally and a production build when deploying to web, web-preview or native app runtimes.
`_app_hostname` refers to the URL hostname if the app is being delivered on web. When running locally this will show as `localhost`. When running in web/web-preview it will display the partial URL (without http/https and trailing path), such as `plh-teens-app1--pr2885-feat-plh-progress-pa-9jd4wzx2.web.app` for a preview link or `idems-debug.web.app` …

feat: add app env fields

---

src/app/shared/components/template/components/combo-box/combo-box.component.ts

PR Checklist
Fixes an issue where the combo box instance would not correctly handle an initial value passed in via a field in the case that the value was a number (#2964).
Closes #2964
[debug_combo_box_value](https://docs.google.com/spreadsheets/d/13h4OJiMok3XG9DklnRzVmUue_9cXydVTclI4Ixb5nAo/edit?gid=1916689711#gid=1916689711):

fix: handle numerical value passed to combo-box via field

---

src/theme/themes/plh_facilitator_mapa/_index.scss

PR Checklist
I repurposed the `orange` and `dark_orange` round button styles to have the desired accent colours (coming from the theme).
The names are a bit awkward, but I'm not sure we want to do more effort on this. @jfmcquade let me know what you think. 
Related to content issue https://github.com/ParentingForLifelongHealth/plh-facilitator-app-ph-content/issues/92

[Mapa theme] Add round button colour overrides

---

packages/data-models/fields.ts
packages/data-models/flowTypes.ts
packages/shared/src/models/jsEvaluator/jsEvaluator.ts
src/app/feature/campaign/campaign.service.ts
src/app/feature/notification/README.md
src/app/feature/notification/notification.actions.ts
src/app/feature/notification/notification.module.ts
src/app/feature/notification/notification.service.spec.ts
src/app/feature/notification/notification.service.ts
src/app/feature/notification/notification.types.ts
src/app/feature/notification/pages/notifications-debug/notifications-debug.page.ts
src/app/shared/services/notification/local-notification-persist.adapter.ts
src/app/shared/services/notification/local-notification.service.ts

PR Checklist
Creates a new notification system designed to work with authored actions. 
This creates a new `notification` action namespace, with child actions to `create` , `cancel` , `cancel_all` and `request_permission` for notifications. Authors are able to keep track of scheduled notifications within the `_notifications` data_list.
Functionality is demonstrated in new feature sheet [feat_notification_actions](https://docs.google.com/spreadsheets/d/1m_q57wKk7rWCzW5J2DQu8IH4DNYM_rILbDifrN-d_iQ/edit?gid=1107968849#gid=1107968849)
See https://github.com/IDEMSInternational/open-app-builder/issues/3007
See examples in [feat_notification_actions](https://docs.google.com/spreadsheets/d/1m_q57wKk7rWCzW5J2DQu8IH4DNYM_rILbDifrN-d_iQ/edit?gid=1107968849#gid=1107968849)
This sheet can be used to …

Feat: notification actions

---

src/app/shared/components/template/components/text-bubble/text-bubble.component.html

PR Checklist
- Adds validation for the `speech_bubble` image. If image is non-existent, bubble fills the screen
Closes #3043

[Bug Fix] Speech Bubble: Add Image asset check

---

src/theme/themes/plh_facilitator_my/overrides.scss

PR Checklist
The `plh_facilitator_my` theme included additional margins around the task card component. This is removed in this PR, as the default spacing should be sufficient. There is an additional question of whether data-items rows should include default vertical margin/padding, for which I've added a new issue, #3069.
@esmeetewinkel had effectively already resolved this as part of the issue description.
The other themes based on the KW theme also include this additional margin, which should be removed. However, I understand that this is, at least in some cases, being counteracted by authoring negative margins in some production templates. Rather than include changes to all affected themes, which would potentially require authoring changes for all associated deployments, I think it …

style: remove extra whitespace around task-card for plh_facilitator_my theme

---

src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss

PR Checklist
Fix text wrapping in radio-button-grid component
Not entirely sure why width isn't working with default, I'm guessing something to do with the nested `<p>` inside the `<div>` - could probably just be a single span although I don't want to make any breaking changes to the component so hopefully for now setting the width should fix
Closes #3114
Closes https://github.com/ParentingForLifelongHealth/plh-kids-teens-app-za-content/issues/176
`plh_kids_teens_za` - `/template/module_oneononetime` (a few pages in)

fix: radio-button-grid text wrapping

---

src/app/shared/components/template/components/layout/popup/popup.component.scss

PR Checklist
- Removes padding around content within a pop-up in the case that the pop-up is fullscreen
- Exposes a new `--pop-up-padding` property to theming. Currently no theme overrides this, so the default value of `20px` will be used, maintaining consistency with the current styling.
This will cause visual changes to all fullscreen popups, reducing the padding to more closely match that around content on a non-pop-up page.
The padding around the pop-up content padding is necessary for non-fullscreen pop-ups to display the content sensibly within the pop-up container:
However in the case of fullscreen pop-ups, the pop-up container padding is sufficient because the visible container goes to the very edges of the screen.
Closes #2865
Fullscreen pop-up launched by Button 5 on …

style: remove additional padding around pop-up content for fullscreen pop-ups

---

src/app/shared/components/template/components/text-area/text-area.component.html

PR Checklist
Follow up to PR https://github.com/IDEMSInternational/open-app-builder/pull/3121, addressing an issue higlighted in https://github.com/IDEMSInternational/open-app-builder/issues/3051#issuecomment-3155633251.
Closes #
Before / After (`comp_text_area` template):

style: remove excess top margin on text-area component

---

src/app/shared/components/template/components/audio/audio.component.html
src/theme/themes/plh_facilitator_mx/_overrides.scss
src/theme/themes/plh_facilitator_my/overrides.scss
src/theme/themes/plh_facilitator_ph/_overrides.scss
src/theme/themes/plh_kids_kw/_overrides.scss
src/theme/themes/plh_kids_tz/_index.scss
src/theme/themes/plh_kids_tz/_overrides.scss

PR Checklist
Fixes some issues with spacing around the audio component that led to inconsistencies.
- `default` theme:
- removes excess whitespace at top of audio component (https://github.com/IDEMSInternational/open-app-builder/pull/3125/commits/71d8a1be12b54002fdb570391f63d2590c61e7ff)
- `plh_kids_kw` theme and its descendants:
- fixes issues with display of audio component title
- removes excessive vertical spacing around audio component
- refactors styling overrides
- applies consistency in colours across variants and themes, see screenshots below
The KW-based themes override the core structure of the component, moving the title from inside the demarcated area to outside. Previously, this was achieved with a workaround that absolutely positioned the title, which was brittle. This is …

Fix: audio component styling

---

src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
src/app/shared/services/dynamic-data/dynamic-data.service.ts
src/app/shared/services/remote-asset/remote-asset.service.ts

PR Checklist
Targerts branch of #3156
- Replace `upsertAndMerge` with simpler `{upsert: true}` flag available on `update` method
- Move empty object check to apply on all `update` method calls
- Fix broken test
Can also target onto master and merge from here if happy with changes and don't want to be delayed waiting on my review to original PR

Review: 3156 updates
